### ISSUE TITLE
Add more bots?

### ISSUE THREAD

**Issue by sesam** [googleapis/repo-automation-bots#1026]
> Thanks for stopping by to let us know something could be better!

Hi, why, thanks to you too!

I was just botanising around various bots, and imagined everyone is just cooking their own, but today I stumbled on this repo. Coming in from Google, I had assumed the table here would list various bots.

Read too quickly :( and can't seem to find anything fresher than ~3 years old. Why, internet, why?

The list over here https://github.com/mairieli/awesome-se-bots#probot-bots seems even worse than yours, so at least there's that.

Oh, and if someone would start a new list of bots that would also include non-probot-bots, are you up to some kind of cooperation? Probably more or less linking from here to there, and there to here, could be a way. Or just fight it out in the SERs. Ok, have a great one, ktnxbai :)

**Comment by chingor13** [comment]
This repository is a collection of bots that we maintain primarily for our own usage (although many can be installed by anyone from the install links on the README). It's not meant to be a list of bots that we are necessarily advocating for folks in the community to use.

**Comment by sesam** [comment]
Thank you. Good to know. I've since started a (15th) effort at collecting all bots, and trying to figure out a good way to compare and evaluate them, located here: https://github.com/these-are-the/github-bots-youre-looking-for
Thanks again :)
