### ISSUE TITLE
FR: Status check to tell me if I'm breaking cloud.google.com

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#103]
We keep our samples for cloud.google.com and developers.google.com on the GitHub.  I have several times broken samples, deleted region tags, or moved files in a way that cloudsite was unable to publish due to my changes.  It would be awesome if I had a GitHub status check that told me when I was about to break things.

The devrel samples tracker should have much of the data we need :)

**Comment by orthros** [comment]
This is something I've wanted for a long wile and have brought up with other team members. There are some "guidances" on writing snippets, and I think putting them out into a linter would be a good first start. In terms of "are we about to break cloud.google.com"... that might have to be a kokoro job as the infra to detect that might not be available to our production environment.

As a follow up: one of these bots could detect if a region was changed for a snippet, and comment on the PR with what the new "state" of the snippet would be based on the changes in the PR.

**Comment by tmatsuo** [comment]
This is now implemented as a warning in a issue comment on the PR.
My plan is to change it to failing status check.

**Comment by tmatsuo** [comment]
It's finally done
