### ISSUE TITLE
Release Please Bot should trigger CI

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#104]
I was looking at this PR created by the release-please bot:
https://github.com/googleapis/sloth/pull/328

And noticed that it didn't trigger a kokoro run.  I'm not sure what Kokoro uses to decide if jobs should be run, but we should find a way to have PRs created by our bots automagically trigger CI if applicable.

**Comment by chingor13** [comment]
I think a trusted-tester bot could work for this. The repository would maintain a `.github/trusted-tester.yml` with a list of approved users.

On `pull_request.opened` or `pull_request.synchronized` the bot would add the `kokoro:force-run` label to the PR.

@crwilcox

**Comment by JustinBeckwith** [comment]
The problem with that approach is that we would need to re-trigger CI every time there is an update to master.  Renovate does a good job of auto-updating it's own PRs (which we should consider regardless).

**Comment by bcoe** [comment]
this is becoming a bit of a hassle, specifically for release-please bot, it would be nice to look into whether we can at least get that bot whitelisted, such that tests kick off whenever it opens a PR.

**Comment by JustinBeckwith** [comment]
Happy to say this is working swell now ;)
