### ISSUE TITLE
Refactor auto-label bot for readability

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/repo-automation-bots#1045]
Language/path-labeling and product-labeling code are a bit disparate at the moment.

Work items: 
- [x] Standardize `label exists` checking across both
- [x] Refactor product label functions to helper.ts (or alternative)
- [ ] Update [Github App](https://github.com/apps/product-auto-label) site to reflect new functionality

**Comment by sofisl** [comment]
@nicoleczhu, I added myself as well, happy to help on this!

**Comment by nicoleczhu** [comment]
I split this task into two, new issue for backfilling language/path labels here: #1187
