### ISSUE TITLE
header-checker-lint: cannot view more details

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#105]
See PR https://github.com/googleapis/nodejs-monitoring/pull/305/checks?check_run_id=245512794

Following `View more details on License Header Lint GCF` link sends me to https://us-central1-repo-automation-bots.cloudfunctions.net/header_checker_lint which says 'Bad Request'.

**Comment by bcoe** [comment]
fixed, this was a bad configuration setting for the bot; we should make sure to set the `Homepage` URL to the repository, not the webhook.
