### ISSUE TITLE
Have rule for verifying commit includes tests for new code

### ISSUE THREAD

**Issue by gguuss** [googleapis/repo-automation-bots#108]
We've had a number of commits into the python-docs-samples repo recently from contributors who are not including tests. It'd be great if we had a bot that enforced coverage / tests for new code.

One approach could be to also use the `nox --missingtests` functionality.

**Comment by tmatsuo** [comment]
My 2 cents.

This is reasonably hard to implement this feature for various languages.
Also there are coverage tools which has github integrations for most of the languages.

I think it's better to use such tools. Closing, but feel free to reopen.
