### ISSUE TITLE
merge on green: 'not-mergeable' comment left on merged PR

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#1088]
https://github.com/googleapis/python-billingbudgets/pull/53

Yesterday (11/04/2020)
- I opened the above PR.
- I added (and then removed) the `automerge` label.
- I merged the PR.

Today (11/05/2020)
- About 24 hours after the merge, gcf-merge-on-green commented with the below:

> Merge-on-green attempted to merge your PR for 6 hours, but it was not mergeable because either one of your required status checks failed, or one of your required reviews was not approved. Learn more about your required status checks here: https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks. You can remove and reapply the label to re-run the bot.

There is no impact to my workflow, but I wanted to report this in case it was indicative of some other issue.

**Comment by busunkim96** [comment]
Similar behavior obsereved https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4946. On this PR the bot is commenting much more frequently.

**Comment by bcoe** [comment]
@sofisl if you're so inclined, please feel free to make a case for this being `p2` 😄

**Comment by sofisl** [comment]
@busunkim96, thanks for bringing this up! I will look into this ASAP.

**Comment by busunkim96** [comment]
Closed by #1091. Thanks @sofisl!
