### ISSUE TITLE
Have the merge-on-green bot optionally do "Rebase and merge" instead of "Squash and Merge".

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/repo-automation-bots#1097]
On the [google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet) repo we use the commit messages to generate release history information (example [here](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Dlp.V2/docs/history.md)).

Using the `automerge` label on a PR ends up in a "Squash and Merge" which means all the PRs commits, and its messages, are lost (replaced by the PR description).

Would it be possible to configure the use of "Rebase and Merge"? It's fine if this is done with a new label (`autorebasemerge`) or via a config file living in the repo.

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
