### ISSUE TITLE
MoG: not merging an approved PR

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#1104]
https://github.com/GoogleCloudPlatform/golang-samples/pull/1821 is approved and all checks have passed. MoG reacted with :eyes:. But, the PR hasn't been merged.

**Comment by sofisl** [comment]
@tbpg, it looks like the issue is that you commented after you approved. Github stacks your history, so it reads your last action as 'commented' vs. 'approved'. This one is going to be tricky to address, since someone might comment something legitimate that should be blocking after approving

**Comment by tbpg** [comment]
Got it. In that case, it probably makes sense to close this as working as intended.
