### ISSUE TITLE
Snippet bot is exhausting memory in Cloud Functions

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#1134]
Seeing this in the logs today:

```
Error: memory limit exceeded. Function invocation was interrupted.
```

Search query for logs: 
```
severity=ERROR
resource.labels.function_name="snippet_bot"
```

**Comment by tmatsuo** [comment]
Not 100% sure, but it seems like it is happening on few repos:

googleapis/google-api-python-client
and
googleapis/go-genproto

I'll try to debug the bot with my clone.

**Comment by tmatsuo** [comment]
Hm, I'm buffled.

The bot works perfectly fine with a test PR:
https://github.com/googleapis/go-genproto/pull/494

So it's not repo specific. Maybe the payloads are somehow corrupted and it causes some kind of infinite loop?

**Comment by tmatsuo** [comment]
I think I spotted a PR which likely caused the memory death:
https://github.com/googleapis/go-genproto/pull/493

3443 files were deleted in a single PR.

**Comment by tmatsuo** [comment]
Downgrading to P2 since it's not a widespread issue.

**Comment by tmatsuo** [comment]
The bot is using parse-diff which accepts a string for the diff. We pass around the 75MB of string several times. I guess that the string is copied multiple times.

**Comment by JustinBeckwith** [comment]
I bumped the function from 512MB to 1GB - let's do that, and keep an eye on the loggies

**Comment by tmatsuo** [comment]
The other one is: https://github.com/googleapis/google-api-python-client/pull/1059

2704 files affected. The diff is ~180MB.

**Comment by tmatsuo** [comment]
The request for the above PR went through, amusingly it took 539 seconds (almost 9 minutes).
```
snippet_boturs0tuecwwy6 Function execution took 538793 ms, finished with status code: 200
```

**Comment by tmatsuo** [comment]
Interestingly the go-genproto pr took about 10 seconds.

```
l5rfsoage2jn Function execution took 10902 ms, finished with status code: 200
```

This is because this PR only deletes the files whereas the other one modifies the files (and the bot is fetching all the files).

**Comment by tmatsuo** [comment]
It's still possible that we'll see similar memory errors, but I feel good now because the bot can handle such significant PRs without dying now.
