### ISSUE TITLE
GitHub Actions CI flakiness

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#1156]
See https://github.com/googleapis/repo-automation-bots/runs/1424133746?check_suite_focus=true.

```
Error: Command failed: git diff --name-only origin/
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Seems to be related to the new setup from #626.

cc @JustinBeckwith @bcoe @tmatsuo

**Comment by bcoe** [comment]
@tbpg @JustinBeckwith the problem is that `github.base_ref` isn't populated for `push` (which is what fires when commits land on the main branch).

I think we might need to use an alternate approach to see what files changed.
