### ISSUE TITLE
Merge-on-Green: sometimes misses pull requests

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1159]
We've noticed (especially when tagging in bulk) that merge-on-green sometimes misses PRs:

Some examples:
googleapis/java-scheduler#277
googleapis/java-redis#260
googleapis/java-pubsub#430
googleapis/java-dialogflow#366 (comment)
googleapis/java-cloudbuild#321 (comment)
googleapis/java-asset#446 (review)

I suggest we introduce a second cron that looks for issues tagged with the automerge labels and adds them to the db to watch if they are not already watched. This will catch any missed pull request (due to quota or possibly failed webhook delivery)

See more information: https://github.com/googleapis/java-cloud-bom/issues/735

**Comment by bcoe** [comment]
Calling this a `p2`, since there's the workaround of manually landing; but we will work to prioritize this (in less than the 180 days `p2` implies).

**Comment by chingor13** [comment]
This is causing a bunch of pain. In the interim, can we change the "eyes" reaction to a separate label like `automerge: watching`. This would allow us to use the API to find PRs tagged `automerge`, but not tagged with the `automerge: watching` label. AFAIK, you cannot query for the reaction.

**Comment by chingor13** [comment]
#1217 should fix this, closing.
