### ISSUE TITLE
ops: header-checker lint has had a high queue depth for several hours

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1165]
We're seeing this error:

```
HttpError: Resource not accessible by integration
at (/workspace/node_modules/@octokit/request/dist-node/index.js:66)
at runMicrotasks (<anonymous>)
```

It seems to be due to a private repository having installed the bot.

**Comment by chingor13** [comment]
From the error report, it's making a call to `https://api.github.com/repos/[redacted]/[redacted]/git/blobs/[some sha]` on a private repo.

**Comment by chingor13** [comment]
It looks like there were conflicting permissions (single file reads of `header-checker-lint.yml` vs. read access to the repo). Apparently, the single file condition overrides the read access to the repo. I removed the single-file permission from the app configuration which should allow the read permission to correctly pass.
