### ISSUE TITLE
trusted-contribution: Add configuration file

### ISSUE THREAD

**Issue by crwilcox** [googleapis/repo-automation-bots#117]
As mentioned in comment at https://github.com/googleapis/repo-automation-bots/pull/114/files/f432c262d2344b20717c24357e1f71f2578c186e#diff-f8fbe6dc6a42af4c5efddeeeab43531bR34

We should add configuration file support to allow users to specify the trusted contributors.

A thing to also think about before implementing: would it be useful to restrict the file/filetype editable by each account? For instance, renovatebot should only ever need to edit `package.json` files.

**Comment by chingor13** [comment]
Fixed in https://github.com/googleapis/repo-automation-bots/pull/273
