### ISSUE TITLE
blunderbuss can assign multiple times (race condition)

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1171]
Since blunderbuss listens to a couple of events, it's possible for a single pull request or issue to be assigned multiple times.

A per issue lock would likely solve this.

Example: https://github.com/googleapis/java-vision/pull/332 assigned the pull request twice (likely from the pull_request.opened event and then the pull_request.labeled event).

**Comment by kurtisvg** [comment]
Reopening as this is still happening.

**Comment by tmatsuo** [comment]
Ah, I didn't mean to close this and edited the issue comment on the PR. I guess however, github closed this issue based on the commit message.

**Comment by kurtisvg** [comment]
Following up on this from https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5784#issuecomment-842919084, I think what happens is that:

1. Blunderbuss triggers once when the PR is opened
2. Bluderbuss is triggered again when a label is added 

![image](https://user-images.githubusercontent.com/31518063/118688868-ad5d2300-b7c3-11eb-8526-f4b009837031.png)

**Comment by tmatsuo** [comment]
Yeah it is still confusing to understand what happened because the sample label is added 14 days ago, and two assignees were assigned 6 days ago.

However, I think I understand the code now, and got the fix in:
https://github.com/googleapis/repo-automation-bots/pull/1786
