### ISSUE TITLE
New Bot: Freshness Checker

### ISSUE THREAD

**Issue by grayside** [googleapis/repo-automation-bots#1178]
In various discussions about keeping guidelines/documentation content on Github, the concern that has come up is how to avoid the content becoming stale, especially without any note that it might be out of date.

A freshness bot could help:

* Identify README or dependency content that hasn't been updated in a long time
* Open issues to review & correct that content, serving as a reminder for maintainers that may have lapsed into inactivity

**Comment by tmatsuo** [comment]
It might be worthwhile to design a generic cron-executor bot. Repo owners can configure the bot to execute some command (maybe docker image?) periodically and file issues when the command find something.

**Comment by tmatsuo** [comment]
It turned out that we want to have individual bots for single task. I think it's still worthwhile to design a pattern for such a bot. Maybe we can make it easy to create a similar bot easily (likely with the generate-bot script).

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
