### ISSUE TITLE
Snippet bot: TypeError: Cannot read property 'owner' of null

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#1180]
We are seeing instances of this in the logs for snippet-bot:

```
TypeError: Cannot read property 'owner' of null
        at scanPullRequest (/workspace/build/src/snippet-bot.js:226:289)
        at /workspace/build/src/snippet-bot.js:464:15
        at runMicrotasks (<anonymous>)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:203:21
```

**Comment by tmatsuo** [comment]
https://github.com/googleapis/python-crc32c/pull/34

says:
```
crwilcox merged 1 commit into googleapis:master from unknown repository
```

pull_request.head.repo is null in this case.

I think it's probably because the head branch is already deleted.
I think we can safely ignore this case.

**Comment by JustinBeckwith** [comment]
Oh interesting.  Is there a chance we're running the scan on PRs that are currently closed/merged as well?  I'm guessing `.head.repo` existed before the merge happened, but probably not right after the merge occurred (with auto branch deletion)

**Comment by tmatsuo** [comment]
Wired, but the event says pull_request is open. Probably the events are not serialized on the server side, and if you edit the PR then merge just after the edit, the pull_request.edit event has a slight chance to have the null head repo?

**Comment by tmatsuo** [comment]
Or, is it because the head repo is private?

**Comment by tmatsuo** [comment]
I think probably what happened was that the PR author deleted their clone just after merging it.
Anyways, we can ignore these cases.
