### ISSUE TITLE
Accept both 'yml' and 'yaml' in bot configs

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#1208]
I initially added a `sync-repo-settings.yml`to `python-asset` (https://github.com/googleapis/python-asset/pull/121) because it matched the other configs already in the python repos: `release-please.yml` and `snippet-bot.yml`. 

It would be nice if both extensions were accepted by the bots that use yaml configs.

**Comment by tmatsuo** [comment]
Sorry about the confusion. I have a plan to solve the issue.

It will likely be solved by having a common library for configuration file, and it will give bot the ability to submit failing status check if the file extensions is wrong.

(Technically we can accept both, but it will make the logic complex, especially combined with org level config file.)

**Comment by tmatsuo** [comment]
#870 is the issue for common config library.

**Comment by tmatsuo** [comment]
FYI, many other bots have implemented this feature.
But unfortunately sync-repo-settings has not yet.

**Comment by tmatsuo** [comment]
It's also done for sync-repo-settings.

So now if you try to add `snippet-bot.yaml` (which is a wrong name of the snippet-bot config), the bot will warn you.

@busunkim96 I'm going to close this, but feel free to reopen.
