### ISSUE TITLE
product-auto-label reapplied incorrect product label to issue

### ISSUE THREAD

**Issue by grayside** [googleapis/repo-automation-bots#1226]
## Actual

In the issue https://github.com/googleapis/google-auth-library-python-oauthlib/issues/96, @JustinBeckwith removed the `api: run` label, the next day the product-auto-label bot reapplied it.

This label is correct based on the issue title pattern matching, but is an edge case (matching off a function name that happens to start with `run_`, as opposed to something associated with Cloud Run).

## Expected

If the label is removed, it stays removed.

In the case where the auto-label is re-run in bulk, it notes the most recent manual change to the label in question and defers to that instead of overriding.

**Comment by tbpg** [comment]
Thanks for the issue. The label was not replaced with a different `api:` label. So, we can't use that as a signal to not add one.

The next idea I have is to make another GH API call (https://developer.github.com/v3/issues/events/) to get the issue events and skip this PR if it's already been labeled by the bot. I'm generally hesitant to make another API call, but I can't think of a better way to go about it.

**Comment by grayside** [comment]
This may not have been replaced with another label because there's not a clear product for auth. It seems like maybe there should be a couple "cloud horizontals" with product labels. In this case, Justin might have replaced `api: run` with `api: auth`?

**Comment by tbpg** [comment]
Yeah, I think it's reasonable to not want to add an `api:` label. Not sure the right way to handle that. I'd want to make sure we want/need any info we're asking issue maintainers to add.

@JustinBeckwith

**Comment by tmatsuo** [comment]
`api: N/A`?

**Comment by tmatsuo** [comment]
If that workaround works, we can add it to the user manual.

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall OoSLO soon.

**Comment by tmatsuo** [comment]
I'm closing this. The workaround I suggest will likely to work and we haven't seen similar reports.

**Comment by sofisl** [comment]
Reopening just for tracking, but yes, I think we should implement @tmatsuo's suggestion!
