### ISSUE TITLE
Tests have octokit instances that do retries

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#1234]
At some point, as we migrated to the new versions of Octokit and Probot I noticed failing tests started to get very slow.  I suspect this is because the new testing strategy with `const TestingOctokit = ProbotOctokit.plugin(config);` still does retries on call failures.  The result is that all tests which are going to fail instead timeout.  Let's figure out how to get back to a naked Octokit instance that doesn't do retry stuff.  Adding @gr2m in case he has thoughts here too :)

**Comment by gr2m** [comment]
Yes the APIs changed for testing a bit. See https://probot.github.io/docs/testing/

I can check in detail tomorrow

**Comment by gr2m** [comment]
I saw https://github.com/googleapis/repo-automation-bots/pull/1236/files, did that resolve the problem for you?

**Comment by JustinBeckwith** [comment]
Yup we're all set now :) Thank you for the reminder about that doc!
