### ISSUE TITLE
snippet-bot's region tag check should consider commit pinning

### ISSUE THREAD

**Issue by ace-n** [googleapis/repo-automation-bots#1283]
Currently, `snippet-bot` flags PRs that delete snippets even if those snippets' include statements are pinned to a specific commit hash.

Ideally, we'd still warn the user about these - but make it clear (in the bot's responses to PRs) which tags are (or aren't) pinned.

### Example
Consider [this comment](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1259#issuecomment-761298168) by `snippet-bot`. The cited use of `move_uploaded_file` tag is pinned to a particular branch, so removing the existing sample from the main branch will not affect the docs. (That said, it's still useful to know that unpinning that sample may break the docs!)

**Comment by tmatsuo** [comment]
@ace-n Thanks for filing the issue.

Re: pinning

I think it's pinned to a specific commit. I have a question. Is "pinning" going to be a good practice in the future?
If yes, I think we should handle this situation better.
However, considering that publishing is automated, can we consider "pinning" as deprecated?

**Comment by tmatsuo** [comment]
@ace-n I also would like to hear the use-case of "pinning". When and how often do you use it?

**Comment by ace-n** [comment]
The main value of branch/version pinning is when we want to keep a specific version of a sample in the docs while making changes to the underlying code.

Some common rationales for this that I've seen are:
- a product needs to have a sample set for an old version (pinned) and a new one (not pinned) side-by-side
- code snippets are undergoing a major refactor (e.g. folder moves), and we don't wish to disrupt their use in the docs

**Comment by tmatsuo** [comment]
@ace-n 

For the first case:
> a product needs to have a sample set for an old version (pinned) and a new one (not pinned) side-by-side

Can you have the sample in a different directory?

For the second case:
> code snippets are undergoing a major refactor (e.g. folder moves), and we don't wish to disrupt their use in the docs

It's doable by having redundant sample code and then delete the old one.

I think use cases you listed are all achievable without pinning. Let me know if I miss something. 
Also there is a downside of "pinning"; we tend to forget to "unpin".

WDYT?

**Comment by ace-n** [comment]
> we tend to forget to "unpin"

I very much agree w/this.

IMO, different directories are too much hassle when we're "breaking out"/rescoping an existing sample into two versions - in that situation, we have to update *both* GitHub and the docs.

Another suggestion - could we have an automatic bug system to remove pinning, that lets (or ideally, *requires*) you specify a "time-to-live" in the docs source? E.g. "remove this pin after 2021Q2" (For things we want to keep around for awhile - we can even say something like "10 years from now" and reevaluate it then.)

That way, the appropriate context is documented immediately instead of folks having to hunt it down months (or even years) later.

**Comment by tmatsuo** [comment]
@ace-n 
Ya, I like your suggestion (actually I came up the same idea).

**Comment by tmatsuo** [comment]
Now the bot distinguishes the region tag with a commit hash:
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1280#issuecomment-777711479
