### ISSUE TITLE
Provide more information about PR's impact on semver/release notes

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1288]
Either in release-please or conventional-commit-lint, add more details about the proposed commit's impact on semantic versioning and release notes.

Ideas: maintain a comment on the PR or use the details of a GitHub check.

**Comment by tbpg** [comment]
Could we automatically add a milestone for each release?

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
