### ISSUE TITLE
header-check-lint: support source code files without extension

### ISSUE THREAD

**Issue by aabmass** [googleapis/repo-automation-bots#1342]
**Is your feature request related to a problem? Please describe.**
I have some repos with bazel BUILD files and Makefiles. AFAICT, there is no way to tell header-checker-lint to check these files because the configuration exposed is `sourceFileExtensions`.

 **Describe the solution you'd like**
A source files glob or regex pattern in addition to `sourceFileExtensions`. Documentation says `ignoreFiles` already supports globs.

 **Describe alternatives you've considered**
N/A

 **Additional context**

**Comment by sofisl** [comment]
Closing for now due to PR, feel free to reopen if necessary.

**Comment by aabmass** [comment]
The PR was just mentioning this issue so I think it should be reopened. Is there some workaround or something I'm missing in the docs?

**Comment by minherz** [comment]
There is no good way to enforce linting for files without extensions like scripts that mimic to executable.
Looking into [code][1] it seems that an empty string will not be sufficient.

[1]: https://github.com/googleapis/repo-automation-bots/blob/cbc0d8f7a6a1c10df027d3ad046c2463d770dd97/packages/header-checker-lint/src/header-checker-lint.ts#L53-L55
