### ISSUE TITLE
sync-repo-bot ignored my sync-repo-settings.yaml and re-enabled branch protection

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1348]
My PR: https://github.com/googleapis/googleapis-gen/pull/2/files

Then, the next morning:
![image](https://user-images.githubusercontent.com/11778530/106782843-7e011c80-65ff-11eb-99ce-805638ac2db7.png)

**Comment by tmatsuo** [comment]
There is a following log entry:

```
2021-02-03T09:01:09.657Zsync_repo_settings 3r9q1rgtjsr4 Success updating master branch protection for googleapis/googleapis-gen
```

Looking at the code:
https://github.com/googleapis/repo-automation-bots/blob/b44aa437c04b54ad648835c8795604e413e70f80/packages/sync-repo-settings/src/sync-repo-settings.ts#L66-L79

https://github.com/googleapis/repo-automation-bots/blob/b44aa437c04b54ad648835c8795604e413e70f80/packages/sync-repo-settings/src/sync-repo-settings.ts#L283

I think your configuration was merged to the default configuration.

Is it possible to have a full set of properties in your config file?

**Comment by tmatsuo** [comment]
I mean, the bot is always updating the branch protection rule for master when there's `branchProtectionRules` defined.

https://github.com/googleapis/repo-automation-bots/blob/b44aa437c04b54ad648835c8795604e413e70f80/packages/sync-repo-settings/src/sync-repo-settings.ts#L248-L262

**Comment by SurferJeffAtGoogle** [comment]
The .yaml file looks like this:

```.yaml
# Rules for master branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `master`
- pattern: master
  # Is pushing to matching branches restricted.
  restrictsPushes: false
```

I expect the `restrictsPushes: false` to override the defaults, but that is not what's happening.

**Comment by tmatsuo** [comment]
I think now I understand why.

https://github.com/googleapis/repo-automation-bots/blob/b44aa437c04b54ad648835c8795604e413e70f80/packages/sync-repo-settings/src/sync-repo-settings.ts#L290-L310

It seems like the code is **not** using `restrictPushes` property at all.

**Comment by tmatsuo** [comment]
I suggest that you remove the `branchProtectionRules` property from the config file. I think the bot won't update the branch protection rule if there's no `branchProtectionRules`.

https://github.com/googleapis/repo-automation-bots/blob/b44aa437c04b54ad648835c8795604e413e70f80/packages/sync-repo-settings/src/sync-repo-settings.ts#L251

I'll create a PR.

**Comment by tmatsuo** [comment]
I think you can have a custom config file without `branchProtectionRules` in order to tell the bot not to update the branch protection rule. Closing.
