### ISSUE TITLE
Make review optional for merge-on-green bot

### ISSUE THREAD

**Issue by samtstern** [googleapis/repo-automation-bots#1394]
Currently the merge-on-green bot requires an approving review from a reviewer with write+ access to the repository. This could be an optional check, just as "require reviews" is optional within GitHub itself.

Two ways I could see this done:

1. The bot could take cues from GitHub itself. If the repo has review requirements enabled under branch protection then the PR will not be mergeable after CI passes, there's no need for separate enforcement on the part of the bot.
2. This could be a user-supplied option via a config file or something like that.

The alternative is a workaround like this one:
https://github.com/googleapis/discovery-artifact-manager/blob/master/.github/workflows/autoapprove.yml

These are cumbersome because of the need to upload a secret token and configure on per-repo basis.

**Comment by tmatsuo** [comment]
We have no plan to add features to merge on green bot
