### ISSUE TITLE
Snippet bot should ignore repeated region tags

### ISSUE THREAD

**Issue by ace-n** [googleapis/repo-automation-bots#1436]
Based on [this comment](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4711#issuecomment-781631594), `snippet-bot` does not appear to detect repeated region tags within a file.

For example - the following should be considered as one `region_tag_foo` region tag, not two:
```
// File: foo.js

// [START region_tag_foo]
console.log('Part 1 of 2');
// [END region_tag_foo]

console.log('Not supposed to be in the sample');

// [START region_tag_foo]
console.log('Part 2 of 2');
// [END region_tag_foo]
```

**Comment by tmatsuo** [comment]
Is this really a problem? For the purpose of checking mismatched region tags, the bot should think them as separate pairs.
The bot is also smart enough to tell if you are really trying to remove a region tag, for example, let's say you have this file:

```js
// File: foo.js

// [START region_tag_foo]
console.log('Part 1 of 2');
// [END region_tag_foo]

console.log('Not supposed to be in the sample');

// [START region_tag_foo]
console.log('Part 2 of 2');
// [END region_tag_foo]
```
Then in a PR, you're trying to remove the second part and the final form is:
```js
// File: foo.js

// [START region_tag_foo]
console.log('Part 1 of 2');
// [END region_tag_foo]

console.log('Not supposed to be in the sample');
```

In this case, the bot understands that the final form of the file contains the region tag `region_tag_foo`, so this is not considered as a removal of that region tag.

**Comment by tmatsuo** [comment]
I'll close this, but feel free to reopen with an explanation of why this is a problem.
