### ISSUE TITLE
Sync repo settings failing to update settings?

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1444]
https://github.com/googleapis/google-api-java-client/pull/1717#issuecomment-782274306

**Comment by stephaniewang526** [comment]
Also observed this issue in java-bigquerystorage when [this change](https://github.com/googleapis/java-bigquerystorage/blob/fc2d137001ac0db05bc13943a604db5965e2a2ab/.github/sync-repo-settings.yaml#L49) did not sync successfully and manual changes were needed.

**Comment by sofisl** [comment]
I published a -debug version to gcf-utils and changed it on SRS, but would like to get this passed as well to formally publish the fix: https://github.com/googleapis/repo-automation-bots/pull/1461
