### ISSUE TITLE
Add cron handling to canary bot

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1470]
It would be good to add a cron task to canary bot, to ensure that we don't accidentally break cron behavior during a probot upgrade.

We could perhaps make the cron comment to an issue on _repo-automation-bots_ as well?

**Comment by chingor13** [comment]
We could have the cron handler write a log or metric and set up an alert to make sure we see it

**Comment by tmatsuo** [comment]
Yeah, Idea for issue comment.

The bot can open a new issue for the first run, then the bot will re-use the same comment after that.

Everyday, canary bot can update the issue with version of its major dependencies (maybe all?) with the date, replacing the current content.

(Caveat: if we add the date in the comment, tests with `snap-shot-it` will fail)

**Comment by tmatsuo** [comment]
I'll likely want to have this feature soon, so I'll add it.
