### ISSUE TITLE
Have Snippet-bot report some region tags deletion differently.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/repo-automation-bots#1511]
Context: GoogleCloudPlatform/dotnet-docs-samples#1280

On this PR, Snippet Bot is reporting 22 possible violations. But according to @munkhuushmgl these tags need to be deleted first from GitHub before pages can be regenerated to pick up the change.

Feature request: Is it possible for the Snippet Bot to report these type of tags on an FYI section of the comment, instead of on the violations section, these could be acompannied by some text like: "Remember to regenerate docs pages after these tags have been deleted."

Thanks!

**Comment by tmatsuo** [comment]
snippet-bot already treats sample browser pages differently.

I took a look at the first violation `vision_product_search_import_product_images`.

This region tag is used indirectly from a file named `create-product-set.md` and another file named `create-reference-images.md`, both via another file named `___bulk-import.html`.

In this case, you can remove the `csharp` usage in `___bulk-import.html`.

Does it help?

**Comment by tmatsuo** [comment]
FYI, snippet-bot gave a FYI comment about the sample browser page for this region tag as folows:

> vision/api/ProductSearch/ImportProductSets.cs:24, tag vision_product_search_import_product_images(usage: page 1).

**Comment by tmatsuo** [comment]
I think we can close this issue.

**Comment by amanda-tarafa** [comment]
Yes, thanks Takashi, it just seemed that the tags couldn't be deleted in docs first so that's why I was requesting them to appear in a different section. But if they can actually be deleted from docs, then this is already working as intended.
