### ISSUE TITLE
Owl-Bot post processor should provide easy access to logs.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1523]
My post-processor failed, and I want to understand why.
The check in github provides no clues:
https://github.com/googleapis/nodejs-asset/pull/456/checks?check_run_id=2126287316
I'd like to see the log text, either inline or via a link.

This will help all language maintainers as they build their post processors.

**Comment by chingor13** [comment]
https://docs.github.com/en/rest/reference/checks#create-a-check-run

Looks like you can add a `details_url` or extra information in the `output` object (or both)

**Comment by SurferJeffAtGoogle** [comment]
This will be critical for maintainers of complex repos like Chris Wilcox, so I bumped to P1.

**Comment by SurferJeffAtGoogle** [comment]
Thank you @bcoe for fixing this.
