### ISSUE TITLE
owlbot's config files should be case-insensitive.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1573]
We should find all case variations of the following names:
.OwlBot.yaml
.OwlBot.lock.yaml
.OwlBot.yml
.OwlBot.lock.yml
owlbot.py

**Comment by tmatsuo** [comment]
What should it do when there're multiple variants? Then we should have a determined order, then we should have it tested.

Rather, how about to create a suggesting PR for renaming the config file(s) to the correct ones, and always use once single file name?

**Comment by tmatsuo** [comment]
Actually if we go that route, there might be a case where multiple variants exist.

In that case, we can file an issue and let the owner decide.

This way, we can always use the single file name, as well as catch most of the filename mistakes.

**Comment by SurferJeffAtGoogle** [comment]
This is a nice to have, and would make the code a lot more complicated.  I'm closing this as "Will not fix."
