### ISSUE TITLE
/synthtool/docker/owlbot/nodejs/entrypoint.sh: line 17: /root/.nvm/nvm.sh: Permission denied

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1585]
I see this error when I run:
```
$ docker run  --user $(id -u):$(id -g) --rm -v $(pwd):/repo -w /repo gcr.io/repo-automation-bots/owlbot-nodejs:latest
```

**Comment by chingor13** [comment]
nvm was probably installed as root, so non-root users cannot run it. We have a [temporary ugly hack for java](https://github.com/googleapis/synthtool/blob/572ef8f70edd9041f5bcfa71511aed6aecfc2098/docker/owlbot/java/Dockerfile#L37) to make python runnable by all until we fix the upstream image to install python for all users to run.

**Comment by SurferJeffAtGoogle** [comment]
This is blocking me, so I'll work on it now.
