### ISSUE TITLE
Failurechecker returning non-failing issues

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1587]
Example: https://github.com/googleapis/gaxios/issues/377

**Comment by sofisl** [comment]
@bcoe, I wonder if this has been resolved? Yoshi-live is looking normal today.

**Comment by bcoe** [comment]
@sofisl @chingor13 I'm pretty sure it's been resolved in so much that it's not opening issues for _anything_, I put a merged PR into a failing state and didn't see anything open.

**Comment by sofisl** [comment]
Can confirm, this is no longer an issue :) https://github.com/googleapis/nodejs-phishing-protection/issues/274
