### ISSUE TITLE
Scheduler Proxy appears to timeout on policy bot

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#1591]
Trying to debug an issue where policy bot only looks at ~400 or so of the ~520 repositories I expect to find.  I dug in the logs, and found this:
https://pantheon.corp.google.com/logs/query;cursorTimestamp=2021-03-31T16:50:19.227242644Z;query=resource.type%3D%22cloud_scheduler_job%22%20AND%20resource.labels.job_id%3D%22policy%22%20AND%20resource.labels.location%3D%22us-central1%22%0Atimestamp%3D%222021-03-31T16:50:19.227242644Z%22%0AinsertId%3D%221r9lrxsg31jw17s%22?project=repo-automation-bots

We're getting an HTTP 408 in the Cloud Run app that runs the proxy.  How does the proxy queue up requests to each individual repository event?

**Comment by bcoe** [comment]
The proxy just acts as a launchpad, creating a single HTTP request to the Cloud Function referenced in the POST body. The retrying logic, and fanning out to individual repos happens in the Cloud Functions. So, this would suggest a 408 trying to call the entrypoint for the policy bot.

**Comment by bcoe** [comment]
I bumped the policy bot up to 540 seconds timeout, from 60 seconds, my hunch is that the 408 was being reported from upstream.

**Comment by bcoe** [comment]
We no longer seem to be seeing timeouts in the latest iteration of the bot.
