### ISSUE TITLE
owlbot-nodejs post processor fails for repos that don't copy from googleapis-gen

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1600]
Examples:
https://github.com/googleapis/nodejs-bigquery-connection/pull/69
https://github.com/googleapis/nodejs-error-reporting/pull/553

@sofisl Any idea why 'gts fix' fails?

**Comment by bcoe** [comment]
Could this be related to https://github.com/googleapis/synthtool/pull/1017.

**Comment by SurferJeffAtGoogle** [comment]
@bcoe is fully booked right now, and this issue is blocking nodejs migrations, so I'm looking at it now.

**Comment by SurferJeffAtGoogle** [comment]
Still not fixed.
