### ISSUE TITLE
Failing to fetch signing key for scheduler proxy

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1609]
I'm seeing errors like this:

```
 2021/04/05 17:08:53 error getting bot secret: failed to access secret version: rpc error: code = PermissionDenied desc = Permission 'secretmanager.versions.access' denied for resource 'projects/repo-automation-bots/secrets/policy/versions/latest'
```

Along with addressing the underlying issues, we should verify that our signing logic is working as expected in the cloud function itself.

**Comment by tmatsuo** [comment]
Are we still seeing this?

**Comment by tmatsuo** [comment]
I can not find similar error logs any more. Can anyone provide a query for viewing the logs in question?

**Comment by tmatsuo** [comment]
Closing. Feel free to reopen with a link to a log viewer.
