### ISSUE TITLE
support(sync repo settings): Running in local triggering an error and not synching settings

### ISSUE THREAD

**Issue by oscard0m** [googleapis/repo-automation-bots#1615]
#### Environment details

  - OS: `macOS Big Sur 11.2.2`
  - Node.js version: `14.15.4`
  - npm version: `6.14.11`
  - `repo-automation-bots` version: Since it's local version pointing to `master`, this is the link of HEAD 6031ebb39440072c97f85be1354c118fd0fd8ddb

#### Steps to reproduce

  1. ✅ Install (`npm install`)
  2. ✅ Compile (`npm run compile`)
  3. ✅ Run (`npm start`) app locally as documentation suggests.  
  4. ✅ Once the app is running for first time, open link to install Github App in desired repository.
  5. ✅ Update Github App permissions and grant this new privileges to the installation of the Github App in the desired repository. These are the permission I'm providing to the app:
     * Events: `Push`, `Pull request`
     * Repository Permissions: 
           * `Administration` (read & write)
           * `Checks` (read & write)
           * `Contents` (read & write)
           * `Metadata` (read only)
           * `Pull Requests` (read and write)
           * `Webhooks` (read and write)
           * `Commit Statuses` (read and write)
  6. ✅ Restart the server as Probot's logs suggest:
  ```
   INFO (probot): Probot has been set up, please restart the server!
   ```
  7.  🔴 When restarted, I get the following output
  ```
  INFO (server): Running Probot v11.0.6 (Node.js: v14.15.4)
INFO (server): Forwarding https://smee.io/3IQugD3J83DSUu to http://localhost:3000/
INFO (server): Listening on http://localhost:3000
(node:68436) UnhandledPromiseRejectionWarning: TypeError: appFn is not a function
    at Server.load (/Users/*****/dev/repo-automation-bots/packages/sync-repo-settings/node_modules/probot/lib/server/server.js:49:15)
    at combinedApps (/Users/*****/dev/repo-automation-bots/packages/sync-repo-settings/node_modules/probot/lib/run.js:87:20)
    at async Server.load (/Users/*****/dev/repo-automation-bots/packages/sync-repo-settings/node_modules/probot/lib/server/server.js:49:9)
    at async Object.run (/Users/******/dev/repo-automation-bots/packages/sync-repo-settings/node_modules/probot/lib/run.js:90:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:68436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```
  8. ✅ Pushing changes to `.github/sync-repo-settings.yaml` on default branch. I get feedback on my running local server:
  ```
  INFO (server): Connected
INFO (http): POST / 200 - 6ms
INFO (http): POST / 200 - 1ms
INFO (server): POST http://localhost:3000/ - 200
INFO (http): POST / 200 - 1ms
INFO (http): POST / 200 - 1ms
INFO (server): POST http://localhost:3000/ - 200
  ```
  9. 🔴 No changes in the settings of the repository I'm working on

---

Would the error in `step 7` the reason why is not working to me or the message is an "expected error" and the app should be working fine? Is it only happening to me? If so, I could try to contact probot community with this issue.

**Comment by joantomas** [comment]
Hi,

we will really appreciate to have an answer on this issue, even if the answer is that you are not open to answer questions on this project due to, even being public, is not intended to be used outside your platform, which is perfectly fine.

Many thanks!

**Comment by chingor13** [comment]
This looks related to https://github.com/googleapis/repo-automation-bots/issues/1753 (so not a running local issue, something with the `push` event handling). It's been lower on our priority because the workaround is our running cron endpoint that is functioning.

**Comment by oscard0m** [comment]
The issue is solved now. Thanks!

**Comment by joantomas** [comment]
Many thanks @chingor13! This will help us a lot.
