### ISSUE TITLE
Automatically detect installation ids for crons

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1616]
We may have to re-wire gcf-utils to support this.

Idea: scheduled request hits a cron endpoint which fans out by requesting the [list of app installations](https://docs.github.com/en/rest/reference/apps#list-installations-for-the-authenticated-app) and dispatching new requests for each installation. These new requests would be routed to the probot handler function.

**Comment by tmatsuo** [comment]
Other ideas:

1. Have gcf-utils silently monitoring the payload and record the installation id in datastore?
2. Provide a function and let the bot use the register function.

2 is really easy, and maybe we can put the function call in the bot skeleton?

**Comment by chingor13** [comment]
Idea: 

* request to cron endpoint without an installation id will [request the list of installations](https://docs.github.com/en/rest/reference/apps#list-installations-for-the-authenticated-app) which can be done without an installation id
  * for each installation, queue a new request to the cron endpoint with the installation id
* request to cron endpoint with an installation id will request the list of installed repositories given the installation id
  * for each installed repository, queue a new request to the cron endpoint with the installation id and repository
* the cron handler acts only on a single repository not caring if it was from an org-wide installation or a single repository installation

Because we have bots that may want to act in aggregate over a bunch of repos, we would probably need to make these helpers that the cron handling endpoint can call rather than doing this magically.

**Comment by chingor13** [comment]
Created an internal design proposal for this: go/github-bot-cron-scheduling
