### ISSUE TITLE
Repos with OwlBot enabled need generated-files-bot installed

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1623]
@fhinkel was bitten by the fact that OwlBot kept reverting automatically generated template files:

> How do i prevent Owl bot from closing my PRs immediately? https://github.com/googleapis/nodejs-language/pull/556

We already have a bot written that would have helped notify @fhinkel about what was going on, [generated-files-bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/generated-files-bot). But, we need to enable this on our Node.js repos.

@parthea we should do this for Python too, as I think folks will bump into similar issues.

**Comment by danielbankhead** [comment]
Fixed in #1699 (via googleapis/synthtool@04573fd)
