### ISSUE TITLE
owlbot should be able to create the initial lockfile with the latest image

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1626]

**Comment by SurferJeffAtGoogle** [comment]
In what context should owlbot do this?

The Python and NodeJs migration scripts do it presently.

**Comment by SurferJeffAtGoogle** [comment]
@sofisl Is this part of the design for owl bot bootstrapper?

**Comment by SurferJeffAtGoogle** [comment]
Now that we're migrating to mono-repos, there's very little reason to implement this feature.
