### ISSUE TITLE
bug(release-please): release-please failed for private repo

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1636]
We found an instance where release-please failed for a private repo.

Our guess is that release-please is using public API and failed.

We still need to investigate further.

**Comment by bcoe** [comment]
@chingor13 I've been looking at the failing Cloud Tasks today, the failures for release please seem to mainly relate to its inability to run on private repositories, e.g., there are a few Java repositories which it attempts to update the BOM for daily and are private.

**Comment by chingor13** [comment]
We haven't seen these in the logs for quite some time. Release tagging is working on private repos (I set this up on a new private repo). Please make sure you have accepted any new requested permissions for the application.
