### ISSUE TITLE
bot error: https://github.com/googleapis/google-cloud-go/pull/3958/checks?check_run_id=2371616270

### ISSUE THREAD

**Issue by I-Cat** [googleapis/repo-automation-bots#1647]
Thanks for stopping by to let us know something could be better!

# Issue
  1. ) I made a pull request it brings me to an unswecure web site
  2. ) https://github.com/googleapis/google-cloud-go/pull/3958/checks?check_run_id=2371616270
  3. ) That is my error build wich is ok but I am not going to click accept so I will not beable to move forward because of this not working bot. 

Thanks for reading 
Signed off by -- @I-Cat 
Img provided below for convience

![image](https://user-images.githubusercontent.com/68921721/115128755-1a578000-9fae-11eb-9d01-2a0f669ed73e.png)

**Comment by chingor13** [comment]
Are you using a proxy? The URL https://conventionalcommits.org is a legit website that documents the Conventional Commit specification. It looks like Chrome is saying the SSL certificate is invalid (which it's not for me) so it leads me to think you're behind a SSL proxy

**Comment by JustinBeckwith** [comment]
Verified when following the link from the action it defaults to `https`.
