### ISSUE TITLE
snippet-bot: 500 error from huge PR

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#1658]
https://github.com/googleapis/google-cloud-go/pull/3969 caused snippet-bot to crash. The issue seems to be related to how many possible violations there are.

If you search the logs for `google-cloud-go 3969`, you can find the failures.

**Comment by tmatsuo** [comment]
Wow this is a huge PR and an extreme edge case :)

**Comment by tmatsuo** [comment]
> Function execution took 454730 ms, finished with status code: 500
It's still within the current timeout of 540s, although it's approaching.

> ERROR (HttpError): Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"} 

This is the root cause. Maybe we can upload the body of the comment to a storage bucket and put a link to the file?

**Comment by tmatsuo** [comment]
Or maybe just omit the very large comment and add `...` or sth.
