### ISSUE TITLE
Proposal: Bots should create their labels

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1673]
For bots that listen to label events (e.g. release-please's `release-please:force-run`), the bot should create the label on the repository it's installed on at some point (installation, or perhaps on a cron). It will help discoverability of those features (the label could even link to the bot in the description).

**Comment by tmatsuo** [comment]
Maybe provide a common library to do that and let the bot use the library?
`installation` hook is theoretically the best place, but probably not practical because we have many bots already installed.

The bot can call the library helper function in any of the popular handler.

It will add 1 datastore.read most of the time and when updating, datastore transactional read/write + few github API calls. It might be easier to use datastore lock.

**Comment by tmatsuo** [comment]
One more thoughts on this. Probably it's safer to share the lock (and probably logic) with label-sync bot.

**Comment by tmatsuo** [comment]
I came up with a really nice idea.

1. Build a common library for bot specific label
2. It provides a lightweight function for checking the label existence, and if not, file an issue on the repo informing about the bot's label.
3. Optionally that issue has a checkbox saying [ ] Create these labels.
4. If you want to use this feature, bot should listen to `issues.edited` events.
5. When user check the box, library will create these labels, then close the issue, report errors upon failure.

The most lightweight way of using the library is to use the function in 2. in the installation.
For already installed bots, bot can opt in calling the function 2 in its main event handler.

In any cases, a bot can opt in to use the checkbox and the automatic label creation.

**Comment by tmatsuo** [comment]
The easier option:

1. Build a common library for bot specific label
2. It provides an async function for checking and syncing labels. The bot can call it in the main handler and await at the end.

I'd prototype this easier version.

**Comment by tmatsuo** [comment]
Alright, snippet-bot opted in using the `@google-automations/label-utils` and now all the repos has the same labels.
Probably it is better to create a dedicated scheduler job because scanning GCP org taks like 3 minutes.

**Comment by tmatsuo** [comment]
I did a quick scan. I think here is the list of bots that have its own labels.

- [ ] blunderbuss
- [ ] flakybot
- [ ] merge-on-green
- [ ] owl-bot
- [ ] release-please
- [x] snippet-bot

**Comment by sofisl** [comment]
Adding myself in to implement for merge-on-green.

**Comment by tmatsuo** [comment]
I think we're syncing all of the bot labels now.
