### ISSUE TITLE
[trusted-contributions-gcf]: consider adding a /gcbrun comment

### ISSUE THREAD

**Issue by coryan** [googleapis/repo-automation-bots#1678]
**Is your feature request related to a problem? Please describe.**

When renovatebot creates a PR I have to manually start the GCB (Google Cloud Build) builds, while the Kokoro builds start automatically.

 **Describe the solution you'd like**

The `trusted-contributions-gcf` bot needs to insert a comment saying `/gcbrun`.

 **Describe alternatives you've considered**

AFAIK this is it, there is no other way to trigger GCB builds, but I would be happy to hear otherwise.

 **Additional context**

This could be a good example:

https://github.com/googleapis/google-cloud-cpp/pull/6357

/cc: @devjgm in case he has a better idea.

**Comment by devjgm** [comment]
It may be possible to have our `google-cloud-cpp-bot` detect that a PR is coming from renovatebot and then add a `/gcbrun` comment. Not sure if that's secure enough though.

I don't know what `trusted-contributions-gcf` is or if that's a better idea.
