### ISSUE TITLE
Owl Bot : Only close PRs that were opened by Owl Bot

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#1709]
Owl bot has a feature where it closes PRs that have no file changed. The feature should be adjusted to support `release-please`. @SurferJeffAtGoogle suggested the following to solve the issue:

- Owl bot should only close PRs that it opens
- A new label could be added to signal to owl bot that the PR should be ignored.

**More details**
Unrelated to owl bot, I opened a PR for `release-please` to change the version number using these [steps](https://github.com/googleapis/release-please#how-do-i-change-the-version-number).  As part of the process, a PR is opened with an empty commit. Unexpectedly, owl bot closed the PR. This issue repeated several times. See https://github.com/googleapis/python-security-private-ca/pull/42 and https://github.com/googleapis/python-security-private-ca/pull/43.

**Comment by bcoe** [comment]
This feels like a `p2` to me?

**Comment by SurferJeffAtGoogle** [comment]
@JustinBeckwith is suffering from this too:
https://github.com/googleapis/nodejs-service-control/pull/29
