### ISSUE TITLE
OwlBot Post Processor should open p1 issue when it fails

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1726]
When synthtool fails during its nightly generation it opens a `p1` issue, so that we prioritize fixing the issue.

Similarly we should consider opening a `p1` issue if a post processor fails, so that people fix the broken step in the post processor.

**Comment by SurferJeffAtGoogle** [comment]
Users see the failure in the pull request itself.  Opening a bug on code that hasn't been merged would probably be confusing.
