### ISSUE TITLE
Owlbot should be able to generate proto-only packages

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1730]
Some proto packages do not have gapic libraries (e.g. IAM, common protos). Owlbot currently only generates the `[lang]-gapic-assembly-pkg` targets which do not exist for proto-only packages.

We should still be able to use owl-bot for automation on proto-only packages.

**Comment by SurferJeffAtGoogle** [comment]
Could you provide more context?  An example java repo that Owl Bot will fail to generate correctly?

**Comment by chingor13** [comment]
https://github.com/googleapis/java-iam is a repo that creates artifacts for shared IAM protobuf messages. There is no gapic client at this time. There are a few other examples of this type of repo as well.
