### ISSUE TITLE
Owl-Bot postprocessor check reports failure but actually succeeds

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1743]
Example: https://github.com/googleapis/nodejs-dialogflow-cx/pull/110

Note that the recorded check on the first commit is marked as failure with "Unknown build failure". Perhaps the bot's webhook timed out before the GCB build completed?

**Comment by bcoe** [comment]
One potential solution for this would be migrating all of OwlBot to Cloud Run, and using the hour timeout we have on execution, vs., the 5 minutes we're limited to with Cloud Functions.

**Comment by sofisl** [comment]
@SurferJeffAtGoogle, this will go OOSLO soon.

**Comment by SurferJeffAtGoogle** [comment]
When was the last time we've seen this happen?

**Comment by SurferJeffAtGoogle** [comment]
Closing because we haven't seen this issue happen recently.
