### ISSUE TITLE
bug(owl-bot): updating .github/.OwlBot.lock.yaml may result in adding commits from master

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#1752]
I encountered an issue with owl bot when updating `.github/.OwlBot.lock.yaml` on an open PR which is not up to date with master. 

In https://github.com/googleapis/python-data-qna/pull/33/files, I updated the `.OwlBot.lock.yaml` file [in this commit](https://github.com/googleapis/python-data-qna/pull/33/commits/0eace15237b569d42172a3ffba3e8139c2adfb81) in the PR. At the time of the update the PR was not up to date with `master`. Owl bot merged changes from master [in this commit](https://github.com/googleapis/python-data-qna/tree/40a924f2f0b30c9a58fd1fee023a5aaf3b9ba858).

The issue is that owl bot will add commits from the `master` into the branch created by owl bot without fetching the `master` branch. This is a problem because Github shows the changes already in master in my open PR. For example, [see this change](https://github.com/googleapis/python-data-qna/commit/d4a5b935d101a593489f94a1a1db9ba32048f296) from `master` which appears in the diff of my PR [here](https://github.com/googleapis/python-data-qna/pull/33/files#diff-101f90f47ec2b1601c618f4a233a8c42e53e0c389441875dc2ec1e0d29574b6d).

**Comment by chingor13** [comment]
Here's an example from nodejs-dialogflow-cx: https://github.com/googleapis/nodejs-dialogflow-cx/pull/114
