### ISSUE TITLE
Allow bots to have hyphens in their names when created with generate-bot

### ISSUE THREAD

**Issue by crwilcox** [googleapis/repo-automation-bots#177]
Today, if you run the generate-bot and attempt to name a package with a hyphen ('-') it will fail.

```
✔ What is the name of the program? · trusted-contributions
✔ What is the description of the program? · blah
✔ This package will be saved in /packages/yourProgramName unless you specify another location and directory name here relative to /home/crwilcox/workspace/repo-automation-bots :  · /package/trusted-contributions

You used an invalid character, like a hyphen or an integer. Please try again.
```

While not necessary, it is a convention we have used to this point. It would be great if we could extend the generator to support this.

**Comment by bcoe** [comment]
👍 I'd love this functionality too, we will need to make sure to dig in to @orthros' deploy script to make sure we don't break any of the logic for keynames, etc.

**Comment by sofisl** [comment]
Thanks for mentioning Chris! Even though @orthos's script handles hyphens, I can't export the function to cloud functions with a hyphen.

Would it help if we allowed hyphens, but just had the bot change the hyphens to underscores? Or, open to any other suggestions you might have!

**Comment by tmatsuo** [comment]
I think it's possible now.
