### ISSUE TITLE
snippet-bot: consolidate the status checks into one single check

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1775]
Maybe provide a new option for consolidating them.

**Comment by tmatsuo** [comment]
@kurtisvg FYI

**Comment by tbpg** [comment]
I'd vote for a good default with no config.

**Comment by tmatsuo** [comment]
I agree. The good default might different from person to person.

**Comment by tmatsuo** [comment]
@tbpg What's the good default for you?

**Comment by tbpg** [comment]
I'd vote for a single check and no config.

Configs require documentation, understanding, and increased complexity. In this case, I don't think the benefit is worth those costs. But, perhaps there are users who want it?

**Comment by tmatsuo** [comment]
@tbpg Thanks, I like that. Unfortunately there's at least one user of `alwaysCreateStatusCheck` and the branch protection, so I can not make it configless right away, but I think I can change the default later.
