### ISSUE TITLE
Owl Bot lock updates never retry

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1777]
An owl bot lock update may fail due to a transient error, like a failed network connection to Gihub.  In such cases, owl bot never retries.  It should.

https://console.cloud.google.com/cloud-build/builds?query=trigger_id%3D%227f3c737e-9641-48c8-adae-eccb5b0d7ad5%22&project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
At the same time we make it automatically retry, we need to make the build tasks idempotent.

Manually clicking retry on a cloud build task today is not idempotent because it checks out the _latest version_ of the repository, makes changes, and creates a pull request.

Instead, when creating the cloud build job, owl bot must observe the current commit hash for the repo, and pass it to the build job, so the build job can checkout the repo at that build hash.  That code path starts here:
https://github.com/googleapis/repo-automation-bots/blob/241c4d04dea7032cb6ab991f3f5139285b6c3505/packages/owl-bot/src/handlers.ts#L84

**Comment by bcoe** [comment]
Here's another example of a repos where OwlBot.lock was on old version, and had to manually be updated:

https://github.com/googleapis/nodejs-bigquery-data-transfer/pull/467/commits/ff584f447f1f71fe8451943a6448faf7fa20952a

This seems to happen fairly often... I like the idea that we'd just always run `latest`.

**Comment by bcoe** [comment]
And another one:

https://github.com/googleapis/nodejs-service-management/pull/61/commits/1f4a5cd8cef429a135ad2b9011704fdb3bdf8eda

I didn't notice that many errors in Cloud Build while we were rolling out new versions of containers, makes me wonder if there's a silent failure to push we're sometimes bumping into.

**Comment by SurferJeffAtGoogle** [comment]
Acknowledged.
