### ISSUE TITLE
Code contributors outside Google can't run owl bot post processor images

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1790]
because the post processor images live in the private github project `github-automation-bots`.

We should move the post processor images to the `cloud-devrel-public-resources` project, and update the .OwlBot.yaml config files accordingly.

**Comment by SurferJeffAtGoogle** [comment]
Example: https://github.com/googleapis/python-pubsub/pull/411#issuecomment-841672268

**Comment by parthea** [comment]
I've set up a build trigger to push new owlbot post processor images to `cloud-devrel-public-resources`. I've updated the `.github/.OwlBot.yaml` file in `python-pubsub` to use the public post processor image `gcr.io/cloud-devrel-public-resources/owlbot-python:latest` [here](https://github.com/googleapis/python-pubsub/blob/master/.github/.OwlBot.yaml#L16) however owl bot is not opening PRs when a new post processor image is pushed. I believe that owlbot needs to be updated to scan `cloud-devrel-public-resources` in addition to `repo-automation-bots` for new images pushed to the container registry possibly related to this section of the [code](https://github.com/googleapis/repo-automation-bots/blob/master/packages/owl-bot/src/owl-bot.ts#L132).

**Comment by parthea** [comment]
Bumping to P1 as this is impacting the workflow for external maintainers.

**Comment by parthea** [comment]
I've confirmed that new owl bot PRs are created when there are new images published at `cloud-devrel-public-resources`. For example, see this PR: https://github.com/googleapis/python-datastream/pull/27

**Comment by parthea** [comment]
bumping back to p2 as we are now unblocked (functionality is working)

**Comment by SurferJeffAtGoogle** [comment]
I updated all our repos with an .OwlBot.yaml to point to cloud-devrel-public-resources.
