### ISSUE TITLE
bug(flakybot): can not fetch the config file correctly

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1794]
This can be fixed by using the new `@google-automation/bot-config-utils` package.

**Comment by SurferJeffAtGoogle** [comment]
I want to be able to verify this bug when it's fixed.  How do I observe its current, broken behavior?

**Comment by SurferJeffAtGoogle** [comment]
> The difficulty of reproducing this bug is that nobody is using the config file :)
> 
> Maybe you can run it locally and somehow send the pubsub message so that you can verify.
> or find a repo that wants to use priority other than `p1` and actually try `p2` for example.

Ok.
