### ISSUE TITLE
FR: Include relevant commit messages when there are updates to the post processor image.

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#1876]
This feature request is to implement the `TODO` comment [here](https://github.com/googleapis/repo-automation-bots/blob/master/packages/owl-bot/cloud-build/update-lock-branch.yaml#L63).

In [python](https://github.com/googleapis/python-webrisk/pull/88) , [java](https://github.com/googleapis/java-resourcemanager/pull/500) and [nodejs](https://github.com/googleapis/nodejs-web-risk/pull/245) PRs are automatically created by owl bot with the title `'chore: new owl bot post processor docker image'`. We should also include the conventional commit messages from synthtool corresponding to the update of the docker image.

**Comment by SurferJeffAtGoogle** [comment]
Actually, the subjects will vary very soon to include details about the changes to the post processor.  However, all PRs will be created with the "owl-bot-update-lock" label, so I think you can filter an that.

**Comment by SurferJeffAtGoogle** [comment]
Update the python stuff this way:
https://github.com/googleapis/synthtool/commit/d543abd7c1f500bdbe530a35ca174ee374fde8f6

**Comment by SurferJeffAtGoogle** [comment]
The mechanism to do this is now in place in Owl Bot.  It's up to language teams to add a post-processor-changes.txt to their docker image.
