### ISSUE TITLE
bug: Owl-bot post processor check missing in PR from `python-dialogflow`

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#1877]
In [this PR](https://github.com/googleapis/python-dialogflow/pull/304) from `python-dialogflow` the owl bot post processor didn't run.  I've seen the owl bot check run successfully in [another PR](https://github.com/googleapis/python-dialogflow/pull/298) that I reviewed. How do I go about troubleshooting why the owl bot check was missing? I triggered the post processing check to run by adding the label `owlbot:run` so we don't block the API feature from being merged.

**Comment by sofisl** [comment]
@SurferJeffAtGoogle, I've labeled this as a docs issue, but feel free to relabel as appropriate.

**Comment by SurferJeffAtGoogle** [comment]
I expected owl bot post processor to run, but it never did.

**Comment by bcoe** [comment]
I dug into the specific issue having trouble, and the reason `owlbot:run` did not run on subsequent runs was that the branch was deleted.

Please let us know in chat if this happens again, and we can look at the build history and see why the trigger failed.
