### ISSUE TITLE
sync-repo-settings not updating branch protection rules for Node.js repo

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1881]
The repo https://github.com/googleapis/nodejs-serviceusage should have branch protection rules configured for it, running sync-repo-settings does not appear to set them.

One theory is that the language is being reported incorrectly by the GitHub API, or the wording has changed.

**Comment by tmatsuo** [comment]
To be clear, other nodejs repos are working fine without configuration, and you're expecting sync-repo-settings should work with this new repo without repo configuration, right?

**Comment by tmatsuo** [comment]
Now local run raises an error:

```
$ sync-repo-settings --repo=googleapis/nodejs-service-usage
```
401: url: 'https://api.github.com/repos/googleapis/nodejs-service-usage/contents/.github%2Fsync-repo-settings.yaml',

**Comment by tmatsuo** [comment]
If I specify the config file, it runs, but it doesn't set the branch protection rule:

```
$ sync-repo-settings --repo=googleapis/nodejs-service-usage --file=${HOME}/googleapis-sync-repo-settings.yaml
{"severity":"INFO","level":30,"message":"updating settings"}
{"severity":"INFO","level":30,"message":"Update team access for googleapis/nodejs-service-usage"}
{"severity":"INFO","level":30,"message":"Updating commit settings for googleapis/nodejs-service-usage"}
{"severity":"INFO","level":30,"message":"name: nodejs-service-usage"}
{"severity":"INFO","level":30,"message":"owner: googleapis"}
{"severity":"INFO","level":30,"message":"enable rebase? true"}
{"severity":"INFO","level":30,"message":"enable squash? true"}
{"severity":"WARNING","level":40,"message":"updateRepoTeams: warning received 401 updating googleapis/nodejs-service-usage"}
{"severity":"WARNING","level":40,"message":"updateRepoOptions: warning received 401 updating googleapis/nodejs-service-usage"}
```

**Comment by tmatsuo** [comment]
I think what is happening is that, after we added the following file:
https://github.com/googleapis/.github/blob/master/.github/sync-repo-settings.yaml

24 days ago, all the sync-repo-settings call for googleapis repos has been broken if you don't have the config in the repo.

**Comment by tmatsuo** [comment]
I think it's fixed by https://github.com/googleapis/.github/pull/10
