### ISSUE TITLE
Migrate bots to Node 14

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#1885]
We should update bots to Node 14 to update dependencies. But, we need to be careful when upgrading bots that it does not break when deploying to GCF.

**Comment by tmatsuo** [comment]
Note: gcf-utils has node 10 as the engine param. Maybe it doesn't matter, but maybe we want to change it too?

Also, can we make sure with canary bot first?

**Comment by bcoe** [comment]
I noticed on Friday this behavior:

1. I tried to switch owlbot to Node 14 through the UI.
2. the deployment failed, so the Cloud Function was not actually upgraded.

Later that day I tried editing code to test a bug, and noticed the exact same issue, **without upgrading to Node 14.**.

This makes me think that the bug I'm bumping into is with deploying using the UI, not the upgrade to Node 14.

## Alternate way to upgrade

Perhaps we can instead pass in the Node version as a parameter to the `gcloud` command we use to deploy? With it defaulting to Node 10.

> gcf-utils has node 10 as the engine param

Once we switch everything over to 14, I think we can update the engines' field post-hoc, Node 14 should be backwards compatible to Node 10.

**Comment by tmatsuo** [comment]
I'd like to still start with canary bot.
"It should be fine" and "It's proven to be working" is a different thing.

**Comment by bcoe** [comment]
> It should be fine" and "It's proven to be working" is a different thing.

I agree, I would rather we update at least a few of the bots one at a time, to make sure the upgrade is smooth, before we make the swap widely -- as the runtime is a significant change.

**Comment by tmatsuo** [comment]
canary bot works with Cloud Function node14 runtime.
