### ISSUE TITLE
Auto-Approve: Block Releases from being merged on holidays

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#1896]
See #1891 for more context cc @parthea

**Comment by tmatsuo** [comment]
Is it closed by #1891?

**Comment by sofisl** [comment]
No, that only covers weekends!

**Comment by sofisl** [comment]
I think we already have a solution for this with the addition of the env variable: #2914 
Closing for now, unless we want to add in some kind of hard-coded dates for blocking merges
