### ISSUE TITLE
Snippet bot considers moving a region tag to be an add/remove

### ISSUE THREAD

**Issue by leahecole** [googleapis/repo-automation-bots#1906]
Hey! I noticed that snippet bot said I was an adding a region tag where I didn't think I was, and when I looked further, noticed that it said I was also removing it. In reality, it just changed lines - not sure if this is intended behavior but wanted to file anyways

[Screenshot](https://screenshot.googleplex.com/5x2ZbdpCfR5f6NL)
[Link to comment](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5782#issuecomment-831576242)

**Comment by tmatsuo** [comment]
Yeah the bot just parse the diff of the PR and machinery categorize add/delete from the diff.
It's an intended behavior unless you're annoyed by a false positive failing status checks.

Thanks,
