### ISSUE TITLE
Bots should validate the config schema upon config retrieval

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1914]
Currently bots are fetching the config file and load with the yaml library. This doesn't ensure anything about the config schema.
Since bot-config-utils started to support config schema validation upon config retrieval, all the bots should use that feature so that bots are always 100% certain the config object is correct.

- [x] auto-label
- [x] blunderbuss
- [x] flakybot
- [x] generated-files-bot
- [x] header-checker-lint
- [x] release-please
- [x] snippet-bot
- [x] trusted-contribution
- [x] sync-repo-settings

**Comment by sofisl** [comment]
@tmatsuo, I downgraded this to P2 as it's not currently breaking all the bots, but feel free to work on it/upgrade as necessary.

**Comment by tmatsuo** [comment]
auto-approve is tracked at https://github.com/googleapis/repo-automation-bots/issues/1809

Other than that bot, it's done
