### ISSUE TITLE
We should turn off the blunderbuss cron job.

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#1922]
I don't think blunderbuss uses it at all, right @kurtisvg?

**Comment by tmatsuo** [comment]
One useful thing we can do is to sync labels (blunderbuss:assign) to repos. snippet-bot is doing this.

**Comment by kurtisvg** [comment]
AFAIK, blunderbuss currently isn't doing anything with cron. 

In addition to @tmatsuo's idea, it could also look for OOSLO or un-triaged issues via the 🚨  label and attempt to assign those.

**Comment by tmatsuo** [comment]
I deleted the original scheduler job. I'll create new scheduler jobs for syncing labels in #1945
