### ISSUE TITLE
process-cloud-functions, process-github-data, process-logs, and process-task-que-data scheduled tasks are failing

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1923]
All four tasks have been failing for the past 7 days at least.

![image](https://user-images.githubusercontent.com/11778530/120398001-36a94500-c2ee-11eb-897a-feb8002dd9de.png)

If they are important, we should fix them.

If they are not important, we should remove the scheduled tasks so bilge pumper doesn't see them.

Thank you @sofisl for helping diagnose.

**Comment by tmatsuo** [comment]
I deleted them
