### ISSUE TITLE
bug(policy-bot): created a PR adding a file that already exists

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1924]
An example:
https://github.com/googleapis/go-genproto/pull/610

**Comment by tmatsuo** [comment]
I think the code is working as written. If the request to the raw URL fails for any reason, it's considered to be "missing".
https://github.com/googleapis/repo-automation-bots/blob/f0b159cd5c5ef3adce0b1676a4093b6c570f1d24/packages/policy/src/policy.ts#L152-L175

**Comment by tmatsuo** [comment]
We can make it less often with retrying, but hard to make it always work.

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall OoSLO soon.
