### ISSUE TITLE
New bot idea: meta-info-bot

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1935]
A bot which runs daily job for collecting metadata and store them in datastore (or firestore).
Candidates for the metadata:
- whether a repo has the Kokoro webhook 
  https://github.com/googleapis/repo-automation-bots/issues/131#issuecomment-728327886
- top 3 list of language used in the repo
  https://github.com/googleapis/repo-automation-bots/blob/f0b159cd5c5ef3adce0b1676a4093b6c570f1d24/packages/sync-repo-settings/src/sync-repo-settings.ts#L84-L111

I only have those 2 in mind, but there might be more useful metadata.

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
