### ISSUE TITLE
Bug(some bots): Seems like some bots are dying with a big PR

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1949]
An example:
https://github.com/googleapis/google-api-php-client-services/pull/363

- [ ] Function timeout while determining whether the config file was modified (whether or not to validate)
- [ ] GitHub API request timeout while paginating through pull request files

**Comment by tmatsuo** [comment]
I think these bots are erroring:
- [ ] snippet-bot
- [ ] blunderbuss
- [x] generated-files-bot
- [ ] auto-label

That PR has multiple commits and each commits are adding a new payload, all of them are failing.

**Comment by tmatsuo** [comment]
I found one example of error logs in snippet-bot:

```
message: "
    HttpError: request to https://api.github.com/repositories/53168835/pulls/363/files?per_page=100&page=23 failed, reason: connect ETIMEDOUT 140.82.112.5:443
        at /workspace/node_modules/@octokit/request/dist-node/index.js:109:11
        at runMicrotasks (<anonymous>)
        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:437:12)
        at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:62:26)
        at async ConfigChecker.validateConfigChanges (/workspace/node_modules/@google-automations/bot-config-utils/build/src/bot-config-utils.js:75:23)
        at async /workspace/build/src/snippet-bot.js:554:9
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21"
```

I also see errors like:

```
Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging Function invocation was interrupted.
```
In this case, there are no other useful info in the log, I highly suspect it's timing out.

**Comment by tmatsuo** [comment]
I don't think these bots are useful for this particular PR, so marking as P2.

**Comment by bshaffer** [comment]
I just rebased it also, to keep the changes in one PR. We can come up with another solution to roll the changes out gradually as well, if you'd like. I'm not a fan of such a big PR but fortunately this is a very rare situation.

**Comment by tmatsuo** [comment]
@bshaffer Yeah I think it's very rare.

Anyways congratulations for 1 million line PR!

**Comment by chingor13** [comment]
The example linked is in the bot-config-utils where it's paginating through all the changed files. The pull request list files endpoint does not let us directly see if the file was included in the pull request without pagination. Perhaps a GraphQL could compare commits that touch that file in the pull request branch to the commits in the target branch to see if that file was touched in the pull request.

**Comment by chingor13** [comment]
> Perhaps a GraphQL could compare commits that touch that file in the pull request branch to the commits in the target branch to see if that file was touched in the pull request.

GraphQL cannot effectively across forks.

Another option is to fetch the file twice (at HEAD of the pull request branch) and against the target branch and see if the files differ.

**Comment by sofisl** [comment]
@chingor13, this is now OOSLO

**Comment by SurferJeffAtGoogle** [comment]
This issue is once again approaching OoSLO.
