### ISSUE TITLE
bug(auto-label): emits `ERROR` logs upon non-critical errors

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1950]
An example log:

```
"HttpError: Validation Failed: {"resource":"Label","code":"already_exists","field":"name"}
    at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:437:12)
    at async Function.addLabeltoRepoAndIssue (/workspace/build/src/auto-label.js:152:9)
    at async Function.autoLabelOnPR (/workspace/build/src/auto-label.js:186:9)
    at async /workspace/build/src/auto-label.js:305:9
    at async Promise.all (index 0)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21"
```

This is when the bot is trying to create a `sample` label which actually exist.

Two issues for me:
1. Why the bot failed to detect the existence of the label?
2. The bot report it as `ERROR`s, but it clutters the log when you look for more serious errors.

Maybe we can downgrade these non-critical errors as `WARNING`?
Also it is great if we can figure out why the bot fails to detect the label existance.

**Comment by chingor13** [comment]
> 1. Why the bot failed to detect the existence of the label?

Auto-label is [naively always attempting to create the label on the repo](https://github.com/googleapis/repo-automation-bots/blob/21138aac7b187fc3876aa3a0e2ddfcee9710bf5c/packages/auto-label/src/auto-label.ts#L102-L116). These labels are normally synced by the label-sync bot. The bot shouldn't even need to create the labels on the repo.

> 2. The bot report it as `ERROR`s, but it clutters the log when you look for more serious errors.

I agree this could probably be a warning.
