### ISSUE TITLE
trusted-contributions: force-push to PR branch does not trigger bot

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#198]
renovate-bot has a feature to rebase/retry the PR which does a force push to its branch. This does not seem to trigger an event that the trusted-contributions bot listens to.

**Comment by bcoe** [comment]
@chingor13 @crwilcox there have been _a lot_ of updates to our libraries over the holidays, and I think a fix to handle the rebases/pushes of renovate bot PRs would be really valuable, I've been adding the `kokoro: run` label all over the place.
