### ISSUE TITLE
Auto-label, blunderbuss, failurechecker, labelsync, policy, release-please, snippet-bot, all have cron jobs failing

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#1984]
<img width="1546" alt="Screen Shot 2021-06-09 at 11 26 47 AM" src="https://user-images.githubusercontent.com/55454395/121393078-99fe2d00-c915-11eb-90c7-d99548ddd5b8.png">

**Comment by tmatsuo** [comment]
The tasks are mostly passing. blunderbuss-googelapis is still failing, but I think it's failing for another reason. Closing.
