### ISSUE TITLE
Owl bot has been failing consistently for the last day

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2013]
<img width="1154" alt="Screen Shot 2021-06-10 at 3 01 56 PM" src="https://user-images.githubusercontent.com/55454395/121589598-dfe1f080-c9fc-11eb-99d0-b816e2684cfd.png">
Since commit d006bad0b5aa39b62914881b930fc544adc1bc6e

**Comment by sofisl** [comment]
Update, it still seems to be failing on java-ai-platform
![Uploading Screen Shot 2021-06-11 at 12.08.14 PM.png…]()

**Comment by parthea** [comment]
I can reproduce the issue with owlbot locally just by running the owlbot-cli docker container on `java-aiplatform`

1. `git clone https://github.com/googleapis/java-aiplatform`
2. `cd java-aiplatform`
3. `docker run --rm --user $(id -u):$(id -g) -v $(pwd):/repo -w /repo gcr.io/repo-automation-bots/owlbot-cli:latest copy-code`
4. Owlbot-cli crashes with the error below. Maybe a `try/catch` [here](https://github.com/googleapis/repo-automation-bots/blob/master/packages/owl-bot/src/copy-code.ts#L287) will help
```
Error: ENOENT: no such file or directory, stat '/repo/google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1beta1/DatasetServiceClient.java'
    at Object.statSync (fs.js:1127:3)
    at internal/fs/utils.js:709:32
    at hidden (internal/errors.js:294:14)
    at Object.rmSync (fs.js:931:13)
    at copyDirs (/usr/src/app/build/src/copy-code.js:249:16)
    at Object.copyCode (/usr/src/app/build/src/copy-code.js:184:5)
    at Object.handler (/usr/src/app/build/src/bin/commands/copy-code.js:49:27) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/repo/google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1beta1/DatasetServiceClient.java'
}

```

On subsequent runs on `java-aiplatform`, owlbot-cli succeeds, but I can get it to fail again if I run `git clean -dfx` and `git reset --hard`

**Comment by SurferJeffAtGoogle** [comment]
Thank you Sofia and Tony for reporting and diagnosing this issue.  I'm working on a fix.
