### ISSUE TITLE
auto-approve: if config is updated in pieces, auto-approve should check if the other half of the config is correct in main branch.

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2022]
https://github.com/googleapis/repo-automation-bots/pull/2020

If a PR editing the config comes in, auto-approve _only_ checks the PR to see if the config coming in is right. However, in this case, it's happening in pieces, i.e., auto-approve.yml on master is right, and CODEOWNERS on the branch is right.

**Comment by tmatsuo** [comment]
Consider using bot-config-utils
