### ISSUE TITLE
Snippet Bot: Should report when files are renamed

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#2034]
See https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1363

When a file with a region tag is renamed, this will break the docs unless the sample includes is updated in the backend.  It would be _really_ helpful to have the snippet-bot call this out, so that a renamed file doesn't accidentally cause a break in the backend (which happened in the case of the above PR).

This is more of a Feature Request than a Bug, but it's an important one!

**Comment by tmatsuo** [comment]
Yeah there was a bug, but I thought I fixed it.
I'll check the event timestamp and figure out why your case didn't catch the bot's attention.

**Comment by bshaffer** [comment]
That PR was merged 16 days ago (but I just realized we broke the docs today). So it's very possible that you've fixed it since!

**Comment by tmatsuo** [comment]
Yeah, snippet-bot's last comment on that PR is 16 days ago.
We fixed this [8 days ago](https://github.com/googleapis/repo-automation-bots/pull/1942).

So the bot should catch similar case in the future!

**Comment by tmatsuo** [comment]
Thanks for reporting!

**Comment by bshaffer** [comment]
Confirmed it was fixed in a new PR I did. Thanks @tmatsuo !!

https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1384
