### ISSUE TITLE
owlbot should create a status check for copy-code PRs to ensure they are merged in order

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2055]
Consider: owlbot opens PRs `A` and `B`, both of which have contextual commit messages.
PR `B` is a superset of changes that include the changes from `A`.
You could merge PR `B` and skip PR `A`, but then we fail to track the context from `A`.

We can set up a policy that maintainers should merge the oldest PR first, but it might be better to enforce via code.

**Comment by SurferJeffAtGoogle** [comment]
It now adds additional commits to open PRs, so they can't be merged out of order.
