### ISSUE TITLE
bug: owl-bot didn't submit a PR for this update for a V1 surface

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2067]
I got a bug to update this V1 surface for nodejs-asset: https://b.corp.google.com/issues/189362793

Why wouldn't owl-bot have created this PR? https://github.com/googleapis/nodejs-asset/pull/504

**Comment by bcoe** [comment]
I believe this was an issue with the generator that has since been fixed, let's keep an eye out for this happening again for a library, and if it does we should try to find the corresponding job in Cloud Build that failed to copy the files.
