### ISSUE TITLE
`npm run start` should use functions framework

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2085]
We don't run `probot start` in GCF, so we should use the functions framework bootstrapper when starting a local instance for testing.

`probot start` has extra functionality that we don't get in production on GCF.

**Comment by bcoe** [comment]
Is this still something we want to do, if we're moving to Cloud Run gradually? perhaps this would be the better refactor.

**Comment by chingor13** [comment]
We don't run the `probot` CLI in Cloud Run either.

Example: https://github.com/googleapis/repo-automation-bots/blob/2dbccb064e6b10bd7f10ea452bb2bf73b986e0cb/packages/release-trigger/package.json#L22
