### ISSUE TITLE
FR(bazel-bot): The Compute API doesn't have a generated client in googleapis-gen

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2089]
The compute API doesn't have a generated client in [googleapis-gen](https://github.com/googleapis/googleapis-gen/tree/master/google/) so I'm unable to migrate [python-compute ](https://github.com/googleapis/python-compute) from autosynth to owlbot. The protos don't appear to be in [googleapis/googleapis](https://github.com/googleapis/googleapis/tree/master/google/). They live [here](https://github.com/googleapis/googleapis-discovery/tree/master/google/cloud/compute/v1).

**Comment by SurferJeffAtGoogle** [comment]
Fixed.
