### ISSUE TITLE
process(auto-approve): eventually we should phase out the json validation schema

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2090]
[This schema](https://github.com/googleapis/repo-automation-bots/blob/master/packages/auto-approve/src/valid-pr-schema.json) will soon become unwieldy with more PR use cases we acquire. We should start thinking about how to decide which PRs should be automerged in a smarter way.

**Comment by tmatsuo** [comment]
Using json schema itself is still useful.

The restrictions by `if` and `then` are too strict IMO.

**Comment by sofisl** [comment]
Greatly improved by #2949
