### ISSUE TITLE
flakybot: keeps opening/closing new bugs for same issue

### ISSUE THREAD

**Issue by shollyman** [googleapis/repo-automation-bots#2105]
Have an issue in google-cloud-go that's essentially being triggered by a progressive rollout, so the issue is destined to be intermediately flaky for days to weeks.  This is manifesting as failures in a test.

Flakybot is flagging the failures as expected, but using a new issue each time and referencing a much older issue (3612) as the rationale for opening a new bug each time.

instances:
https://github.com/googleapis/google-cloud-go/issues/4277
https://github.com/googleapis/google-cloud-go/issues/4279
https://github.com/googleapis/google-cloud-go/issues/4285

**Comment by tmatsuo** [comment]
Thanks for your report! I suspect the bot is looking for the issue with the same title in a wrong order, maybe.

**Comment by tmatsuo** [comment]
The code that sorts the issues is as follows:

```typescript
flakybot.issueComparator = (
  a: IssuesListForRepoResponseItem,
  b: IssuesListForRepoResponseItem
) => {
  if (a.state === 'open' && b.state !== 'open') {
    return -1;
  }
  if (a.state !== 'open' && b.state === 'open') {
    return 1;
  }
  // The issues are either both open or both not-open.                                                                                                             
  if (flakybot.isFlaky(a) && !flakybot.isFlaky(b)) {
    return -1;
  }
  if (!flakybot.isFlaky(a) && flakybot.isFlaky(b)) {
    return 1;
  }
  const aClose = parseClosedAt(a.closed_at);
  const bClose = parseClosedAt(b.closed_at);
  if (aClose && bClose) {
    return bClose - aClose; // Later close time first.                                                                                                             
  }
  return a.number - b.number; // Earlier issue number first.                                                                                                       
};
```

**Comment by tmatsuo** [comment]
The original issue (#3612) was marked as "flaky", and the next issue (#4277) is not marked as flaky (it says "Note: #3612 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.").

So flakybot is picking the `flaky` one. I think we can remove the following code from the bot:

```
  // The issues are either both open or both not-open.                                                                                                             
  if (flakybot.isFlaky(a) && !flakybot.isFlaky(b)) {
    return -1;
  }
  if (!flakybot.isFlaky(a) && flakybot.isFlaky(b)) {
    return 1;
  }
```

**Comment by tmatsuo** [comment]
The Comparator is used in 2 different places and probably we can introduce a new one for finding existing issue.
