### ISSUE TITLE
owlbot: make OwlBot a required check for Python repositories

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2113]
If OwlBot doesn't run on a pull request, it can result in a bad merge to the main branch, e.g., merging the staging directory.

OwlBot should be made a required check for languages that are using OwlBot. If OwlBot ever fails to run:

* we would be grateful if you'd notify the GitHub automation chat immediately _(if we can catch OwlBot in the act of not running, we might be able to pin down an edge case that you're bumping into)_.
* after we've made an effort to diagnose the issue, add the `owlbot:run` label to your PR to manually run OwlBot.

Refs: #1714

**Comment by parthea** [comment]
Closing as obsolete.
