### ISSUE TITLE
owl-bot: owlbot-maybe-create-pull-request-for-lock-update job fails on private repositories

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2127]
Here's an example of a failing job due to repository being private:

https://pantheon.corp.google.com/cloud-build/builds;region=global/be3800f8-b376-42af-87e0-5fd98cf14d12?project=repo-automation-bots

## Expected behavior

OwlBot authenticates appropriately and can run against private repositories.

---

to @SurferJeffAtGoogle for triage.

**Comment by tmatsuo** [comment]
Is it different from: https://github.com/googleapis/repo-automation-bots/issues/2088 ?

**Comment by parthea** [comment]
@bcoe  The issue should be resolved with #2091. Please can you confirm by checking if the issue still exists?
