### ISSUE TITLE
serverless-scheduler-proxy: should be able to proxy to a Cloud Run instance

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2143]
See #1817

Cron payloads look something like:
```json
{
  "Name":"canary_bot",
  "Type":"function",
  "Location":"us-central1"
}
```

**Comment by chingor13** [comment]
I see 2 options here:
1. Support `Type: run`
  a. Support looking up the URL via the Cloud Run go apiary client (with caching) to avoid lookup on every request
  b. Hard-code the url `<service-name>-<some-prefix-for-project>.a.run.app`
2. Support `Type: url` and add a `Url` field with the URL to proxy too. It would be the responsibility of the cron deployment to grab the target Url and put into the cron payload.

**Comment by chingor13** [comment]
We could provide a `PROJECT_HASH` environment variable to the proxy at runtime which it can use to programmatically build the URL.

**Comment by orthros** [comment]
`Type: url` has the most flexibility but also more risks from the security standpoint if a URL is mis configured.

I think 1.a has the best chance of succeeding long term
