### ISSUE TITLE
release please: change version number in existing PR

### ISSUE THREAD

**Issue by danielduhh** [googleapis/repo-automation-bots#2151]
Release please does not submit commit to change version number when following the custom version number procedure for open release please PRs.

Example PR: https://github.com/googleapis/java-storage/pull/891 (I had to manually apply code changes to honor the version - https://github.com/googleapis/java-storage/pull/891/commits)

#### Steps to reproduce

  1. Submit change to prompt a release-please PR
  2. Submit a commit with a custom release tag in the commit message
  
 ```bash
  git commit --allow-empty -m "fix: library should released as 1.111.3" -m "Release-As: 1.111.3"
```

 3. The existing PR will change the PR description and changelog (from 1.112.0 to 1.111.3) to reflect custom tag release, however the readme, pom files, and version.txt files go unchanged.

**Comment by chingor13** [comment]
That commit needs to go to the main/target branch. release-please will always force-push to the release PR branch and will wipe away any extra commits to it.

**Comment by bcoe** [comment]
@chingor13 is there a different series of steps @danielduhh could have taken to release as an alternate version, with assets updating appropriately?

Perhaps you can grab some time with them, and we can also update the usage instructions.

**Comment by chingor13** [comment]
Yes, you can make a commit to the release branch (not the release PR).
