### ISSUE TITLE
Kokoro tests are not running

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2152]
I often need to remove and re-add `kokoro:run` and `kokoro:force-run` because the kokoro status has not updated for several hours. It would be useful to remove the `kokoro:run` label after several hours if the kokoro job has not started. 

[Example PRs](https://github.com/search?q=org%3Agoogleapis+label%3Akokoro%3Aforce-run+is%3Aunmerged+is%3Aopen+status%3Apending&type=Issues) where the Kokoro job is pending. Some of these PRs likely have a stale kokoro status where the `kokoro:force-run` label is not adding value.

**Comment by parthea** [comment]
I often need to remove and re-add `kokoro:run` and `kokoro:force-run` because the kokoro status has not updated for several hours. It would be useful to remove the `kokoro:run` label after several hours if the kokoro job has not started.

**Comment by parthea** [comment]
I'm seeing the same issue with the `owlbot:run` label where the label is stale. I have to remove it and re-add it to get owl bot to run. As an example see https://github.com/googleapis/python-access-context-manager/pull/48

**Comment by SurferJeffAtGoogle** [comment]
Even the kokoro:force-run label has no effect.
Examples:
https://github.com/googleapis/nodejs-retail/pull/67
https://github.com/googleapis/nodejs-dns/pull/469

**Comment by chingor13** [comment]
For googleapis/nodejs-dns#469,

The webhook was delivered to Kokoro and returned a 200. The only possible weird thing is that it aggregated a few events. Here's the `labels` section of the pull_request.labeled event:
```
    "labels": [
      {
        "id": 1814682779,
        "node_id": "MDU6TGFiZWwxODE0NjgyNzc5",
        "url": "https://api.github.com/repos/googleapis/nodejs-dns/labels/api:%20dns",
        "name": "api: dns",
        "color": "537f0d",
        "default": false,
        "description": "Issues related to the googleapis/nodejs-dns API."
      },
      {
        "id": 720791782,
        "node_id": "MDU6TGFiZWw3MjA3OTE3ODI=",
        "url": "https://api.github.com/repos/googleapis/nodejs-dns/labels/cla:%20yes",
        "name": "cla: yes",
        "color": "0B7601",
        "default": false,
        "description": "This human has signed the Contributor License Agreement."
      },
      {
        "id": 1032500348,
        "node_id": "MDU6TGFiZWwxMDMyNTAwMzQ4",
        "url": "https://api.github.com/repos/googleapis/nodejs-dns/labels/kokoro:force-run",
        "name": "kokoro:force-run",
        "color": "C1FFB2",
        "default": false,
        "description": "Add this label to force Kokoro to re-run the tests."
      },
      {
        "id": 3054743786,
        "node_id": "MDU6TGFiZWwzMDU0NzQzNzg2",
        "url": "https://api.github.com/repos/googleapis/nodejs-dns/labels/owlbot:run",
        "name": "owlbot:run",
        "color": "84D2D4",
        "default": false,
        "description": "Add this label to trigger the Owlbot post processor."
      }
    ],
```

**Comment by sofisl** [comment]
According to our OKR discussion yesterday, this seems like something we might start looking into but is not in our immediate scope. Downgrading this to a P3.

**Comment by parthea** [comment]
Closing as obsolete. We still have issues with Github Quota however there are workarounds such as reducing the number of PRs as a result of template updates or switching to a mono repo. For python we're seeing the issue less frequently as we've migrated a lot of checks to Github Actions.
