### ISSUE TITLE
owlbot: triggering post-processor "Updates were rejected because the tip of your current branch is behind"

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2154]
Noticed this error during bilge pump duty:

```
Updates were rejected because the tip of your current branch is behind
```

Refs: https://pantheon.corp.google.com/cloud-build/builds;region=global/7ce74f33-a0ef-4f7b-a683-3f4e058c5819?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
Implementing retry, as described in https://github.com/googleapis/repo-automation-bots/issues/1777, will fix this issue.  So I'm closing this issue as a duplicate.
