### ISSUE TITLE
releasetool: relesetool is having issues interacting with GoogleCloudPlatform

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2188]
We are seeing failures in releasetool which seem to stem from permission issues on repositories that reside on GoogleCloudPlatform:

<img width="1070" alt="Screen Shot 2021-06-25 at 1 49 51 PM" src="https://user-images.githubusercontent.com/194609/123483926-66c9c800-d5bc-11eb-938b-62c8b9e45c51.png">

Refs: https://fusion.corp.google.com/label/63856640

**Comment by SurferJeffAtGoogle** [comment]
@chingor13 This issue will fall out of SLO in 2 days.
