### ISSUE TITLE
owlbot: keep license header on .Owlbot.lock.yaml when file is updated

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2190]
I added a license header to `.Owlbot.lock.yaml` in `googleapis/python-dataflow-client` but [owl bot](https://github.com/googleapis/python-dataflow-client/commit/c5c95333083c9c805cdd09287b4c1fc3c8e005cb#diff-28faeab193819b6210664df33e757a79c3b066449bc2b5cce3ebe463ec1e4f3f) removed it. The license header is required by OSPO.

**Comment by SurferJeffAtGoogle** [comment]
Acknowledged.
