### ISSUE TITLE
owlbot: owl bot labels should have consistent naming

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2191]
owlbot labels should be consistent where we use the prefix `owlbot` or `owl-bot` but not both.

![image](https://user-images.githubusercontent.com/5184014/123510388-282e1f00-d649-11eb-9ec4-79e794dd1146.png)

**Comment by SurferJeffAtGoogle** [comment]
I agree the inconsistent naming is annoying, but there are better ways to use my time than fix this issue.  I'll try to be more consistent in future naming.
