### ISSUE TITLE
bug(m-o-g): Doesn't collect installation IDs for hanging PRs

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2206]
We are not saving installation IDs for hanging PRs, we just use the bot's own installation ID.
https://screenshot.googleplex.com/Ab4YXMcohBwWhsS
Also, we pick up PRs from repos that are not on allowlist.

**Comment by chingor13** [comment]
The cron infrastructure for `schedule.installation` is populating the `installation.id` params.
