### ISSUE TITLE
auto-approve(bug): @googleapis/github-automation is not supported outside of googleapis

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2290]
Our team @googleapis/github-automation is not recognized outside of googleapis. This causes a problem for codeowners files where we are the owners ([example](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5645)). 

I don't think that the solution here is to create another team, as this will cause more overhead and cannot scale with more repos. For now, I'm asking teams to add me personally as an owner, until we can resolve this issue.

**Comment by lesv** [comment]
If you set up the group from an MDB group, you can easily mirror to both org's.
