### ISSUE TITLE
feature-request(auto-approve): autoapprove owl-bot template changes

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2297]
Per our conversation with @parthea, we have a provisional sense of what these requirements would entail:

1. If changes are from owl-bot, 
2. Do not have a piper-origin ID, 
3. Have type `GAPIC_AUTO` in .repo-metadata.json, so as to avoid automerging template changes for handwritten PRs.

**Comment by chingor13** [comment]
Make sure it's not a fix/feat for unintentional version bumps.

**Comment by SurferJeffAtGoogle** [comment]
SGTM.
