### ISSUE TITLE
feature-request(auto-approve): autoapprove upstream-API-changes that owl-bot proposes

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2298]
Per our conversation with @parthea, we have a provisional sense of what these requirements would entail:

1. No breaking changes
2. If there are other owl-bot PRs in the repo, don't autoapprove (so as to not merge out-of-order)
3. Must have a piper-origin ID
4. Must not have any other commits from other sources.

We also have an idea to autoapprove template changes: #2297

**Comment by parthea** [comment]
Please also include 

- Have type GAPIC_AUTO in .repo-metadata.json, so as to avoid automerging changes for partially handwritten libraries.

**Comment by SurferJeffAtGoogle** [comment]
SGTM.
