### ISSUE TITLE
snippet-bot: accept product prefix contactcenterinsights

### ISSUE THREAD

**Issue by TrucHLe** [googleapis/repo-automation-bots#2325]
contactcenterinsights is the correct product prefix for Contact Center Insights so snippet-bot shouldn't flag this prefix. For example, snippet-bot flagged it here[1] but it shouldn't have done so.
[1] https://github.com/googleapis/python-contact-center-insights/pull/11#issuecomment-891939473

**Comment by busunkim96** [comment]
Just to add on, [DevRel Services](https://devrel.corp.google.com/admin/products/483?t=snippets) seems to list `contactcenterinsights` as the expected region tag.

**Comment by tmatsuo** [comment]
Ah this is a known pitfall. [The product in DevRel Services](https://devrel.corp.google.com/admin/products/483) is marked as "not" public. Once the product is marked as public, the prefix will be accepted.

**Comment by busunkim96** [comment]
Ohhh that makes sense. Opened a request internally to flip that switch (see 195944890).

Thanks @tmatsuo!
