### ISSUE TITLE
Owlbot ran on a PR with the `owlbot:ignore` label

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#2357]
See https://github.com/googleapis/python-pubsub/pull/471.

I added the label `owlbot:ignore` label but owlbot still pushed to the PR. I'm not sure if this makes a difference, but the PR was in a "Draft" state.

**Comment by SurferJeffAtGoogle** [comment]
My first guess is that the Owl Bot post processor build was kicked off before the owlbot:ignore label was applied.  It should still respect the label in that case.

**Comment by mosesojero** [comment]
packages/owl-bot/README.md
