### ISSUE TITLE
(Java) Release please should support additional versioning for alpha/beta clients

### ISSUE THREAD

**Issue by kolea2** [googleapis/repo-automation-bots#2381]
We are currently releasing java-bigtable-hbase with the following versioning scheme:
2.0.0-alpha1
2.0.0-alpha2-SNAPSHOT
2.0.0-alpha2
...

I've been editing the versions manually since the versions are getting bumped in release please as 2.0.1-alpha1, for example. It would be great to add additional support for this type of release.

Examples:
https://github.com/googleapis/java-bigtable-hbase/pull/3169
https://github.com/googleapis/java-bigtable-hbase/pull/3193

**Comment by chingor13** [comment]
@kolea2 Do you still need this? This would be implemented on the underlying `release-please` library. In v13, we abstracted the versioning strategy into its own a interface and so we can simply re-use the same java-yoshi language strategy and mix it with a new versioning strategy.

**Comment by chingor13** [comment]
This should be fixed in v13 of release-please (available in app).
