### ISSUE TITLE
auto-approve: please add the following patterns to auto approve

### ISSUE THREAD

**Issue by lesv** [googleapis/repo-automation-bots#2424]
* `com.google.cloud.tools:`     GoogleCloudPlatform/java-docs-samples#5890
* `com.google.cloud.functions:` GoogleCloudPlatform/java-docs-samples#5889
* `com.google.cloud.*:` Would probably be good as well.
* `com.google.apis:`  GoogleCloudPlatform/java-docs-samples#5888

**Comment by lesv** [comment]
*   add `io.grpc:` GoogleCloudPlatform/java-docs-samples#5917

**Comment by sofisl** [comment]
@lesv, to confirm the additional rules we'll want to add:

1. It looks like these prs (https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5890/files, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5889/files, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5917/files)
Main difference is that their files end in `build.gradle`, and the three regex patterns we'll be checking would be like these examples:

- classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.2'
- invoker 'com.google.cloud.functions.invoker:java-function-invoker:1.0.2'
- def grpcVersion = '1.40.1'

Is it OK to say that the build.gradle file can have any of these regexes?

2. Currently, we're checking that the title and dependency upgraded contain `com.google`. Do you want to make it more restrictive, and only pass dependencies that contain `com.google.cloud.*` in them, or are we adding a new case?

**Comment by lesv** [comment]
I'm happy w/ com.google, as that will include guava, gson, and others
