### ISSUE TITLE
bug: owl-bot is grabbing an old version of a library

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2434]
See this PR: https://github.com/googleapis/nodejs-retail/pull/94

Owl-bot is grabbing a version that breaks links. Those links no longer exist in the protos, they were fixed in CL #392712211. When attempting to regenerate the PR, I get the same version.

**Comment by sofisl** [comment]
Although it is not a blocker to many APIs, it is keeping this library from receiving a critical auth update, so it would be nice if it were resolved something like a ~p 1.5 :)

**Comment by SurferJeffAtGoogle** [comment]
A later owl-bot-copy PR was merged: https://github.com/googleapis/nodejs-retail/pull/95, so https://github.com/googleapis/nodejs-retail/pull/94 would rollback those changes.  Just close https://github.com/googleapis/nodejs-retail/pull/94.
