### ISSUE TITLE
bug: owl-bot post-processor did not submit a passing requirement on a repo w/o owlbot config

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2440]
We had to force-merge this PR without the post-processor since it was kept as pending: https://github.com/googleapis/google-api-nodejs-client/pull/2732

This PR, on the same repo at the same time, ran the post-processor fine: https://github.com/googleapis/google-api-nodejs-client/pull/2733

It may be a transient failure, opening this issue in case it is reproduced.

**Comment by bcoe** [comment]
This appears to have corrected itself now, I think it was perhaps a GitHub issue.
