### ISSUE TITLE
deleting templates in owlbot is difficult

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2447]
OwlBot templates are only additive (it does not track files like autosynth did). For client library files, we completely wipe out source directories and add code back during the copy phase. For templates, however, owlbot cannot remove files where the template was removed.

Scenario:
1. remove the unnecessary template in synthtool
2. a new owlbot image is created
3. owlbot runs the image against the repo and sees no changes so it skips opening a PR to bump the image
4. a person sends a PR to remove the unnecessary file
5. the old owlbot image runs and restores the unnecessary file.

In order to delete the old file, we have to force update the owlbot image to one that no longer contains the removed template.

**Comment by SurferJeffAtGoogle** [comment]
No doubt this is a frustrating experience, but it's not the responsibility of owl bot.  Owl bot runs the specified docker image.  It's up to the docker image to decide what files to preserve and delete.

Today, that code lives in synthtool, so perhaps this bug should be filed on the synthtool repo.  A more strategic, long-term alternative is to build a post-processor completely independent of the synthtool code base.
