### ISSUE TITLE
owlbot: many failures for Java repos running `owlbot-maybe-create-pull-request-for-lock-update`

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2478]
I noticed there are many failures in Cloud Build for `owlbot-maybe-create-pull-request-for-lock-update`, they seem to correlate to Java repos:

https://pantheon.corp.google.com/cloud-build/builds;region=global/1aafe20a-7e41-482f-a608-bf9e9b1ed0d5?project=repo-automation-bots

https://pantheon.corp.google.com/cloud-build/builds;region=global/44c7a8a7-4dc5-4cf0-a903-ad47a77ce7d9?project=repo-automation-bots

https://pantheon.corp.google.com/cloud-build/builds;region=global/3e6ed69f-e555-45ff-841c-4e2759eecd1c;step=0?project=repo-automation-bots

**Comment by tmatsuo** [comment]
https://github.com/googleapis/repo-automation-bots/pull/2441 might be the culprit
