### ISSUE TITLE
Exception with OwlBot Java post-processor "could not find expected ':'"

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2513]
Seeing error:

```
    ^
    [--args='[--project_id "Your Goo ... 
  in "<unicode string>", line 6, column 1:
could not find expected ':'
    ^
    -PmainClass=com.google.cloud.exa ... 
  in "<unicode string>", line 5, column 1:
yaml.scanner.ScannerError: while scanning a simple key
    "could not find expected ':'", self.get_mark())
```

Refs: https://pantheon.corp.google.com/cloud-build/builds;region=global/8a71bbb8-cc96-4745-b40e-a3a24948684f?project=repo-automation-bots

**Comment by bcoe** [comment]
@chingor13 weird issue that jumped out during bilge pump, feel free to downgrade to `p2`.

**Comment by chingor13** [comment]
This is a super edge case. We have old generated samples like https://github.com/googleapis/java-talent/blob/master/samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchAutocompleteJobTitle.java which have a metadata section in the comments of the file which are intended to be yaml. However, often the command is too long and so the java formatter will fix the comment length to wrap (and do so incorrectly).

**Comment by chingor13** [comment]
It looks like those generated samples are indeed being used on cloudsite.

**Comment by bcoe** [comment]
Bumped down to `p2` since this is an edge case?

**Comment by lesv** [comment]
I've asked if we can delete those.
