### ISSUE TITLE
 MissingReleaseNotesError error thrown for java-assured-workloads

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2514]
Release-please failing on `java-assured-workloads` with following error:

`MissingReleaseNotesError: could not find changelog entry corresponding to release 0.5.3-SNAPSHOT`

Request-ID: hrgj1krozyh9

**Comment by chingor13** [comment]
This was a repository configuration error. A snapshot PR was labeled with autorelease: pending when it should not have been
