### ISSUE TITLE
owlbot: set source field on triggered post-processor jobs to be the working repository

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2661]
Currently the GCB jobs are triggered manually by the bot and the source field is set to repo-automation-bots. It would be nice if we could set that to be repository that's being run on -- then we can use the GCB list builds filter functionality to drill down to builds by repository.

**Comment by SurferJeffAtGoogle** [comment]
There is a "source" field we could set when creating the API: https://googleapis.dev/nodejs/cloudbuild/latest/google.devtools.cloudbuild.v1.IBuild.html

But I'm not sure what the API will do with it: reject it, ignore it, or try to find the build definition yaml file in that source directory.

**Comment by chingor13** [comment]
Note: this also causes Cloud Build to add status checks to the commit at that sha.

Example: https://github.com/googleapis/repo-automation-bots/commit/913364fb832a6f03b5f3a3a46c95a991a8bc5c9f has status checks reported for post-processor jobs on other repos and bazel bot as well

**Comment by chingor13** [comment]
Bazel bot should probably report its status checks on googleapis/googleapis and the post-processor jobs should report on the commit sha of the target repository as well.

**Comment by SurferJeffAtGoogle** [comment]
I don't think this is possible.  [source](https://cloud.google.com/workflows/docs/reference/googleapis/cloudbuild/v1/Overview#RepoSource) has a repoName field, but the documentation describes it as `string Name of the Cloud Source Repository`.  Our source repos are on github, not Cloud Source.
