### ISSUE TITLE
FR(owlbot): Owlbot should open an issue on a repo if owlbot fails to open a PR due to an error

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2709]
If owlbot fails to open a PR due to an error, the failure is currently not visible to repository maintainers. For example, if there is an issue when owlbot tries to run the post processor or configuration file in a repository, a PR will not be opened by owlbot. There is likely an entry in the owlbot log files somewhere about this error but It would be great if owlbot could open an issue in the repository itself to notify maintainers that owlbot failed so that the issue in the repository can be fixed. Ideally, owlbot should not open an issue for transient failures during the retry period where owlbot is still attempting to create the PR. It should only open an issue when owlbot has given up on creating the PR.

**Comment by SurferJeffAtGoogle** [comment]
For copies from googleapis-gen, Owl Bot always creates the pull request so maintainers will see any error reported by the post processor.

For docker image updates, yes, this is still in issue.  But now, unlike October 14, Owl Bot will retry twice before giving up.

**Comment by SurferJeffAtGoogle** [comment]
Not switched on yet.
