### ISSUE TITLE
Build Cop: include enough information for making a report actionable

### ISSUE THREAD

**Issue by shollyman** [googleapis/repo-automation-bots#274]
Sample issue filed by build cop: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2800

It seems that the source log link is only available once all testing is concluded, so it's a bit confusing when it files issues that can't be acted on immediately.  In this case, its four hours later and the bug is still unactionable as the build is still in progress

Consider adding a link for another source (e.g. sponge/sponge2) or deferring issue creation until the artifacts are ready.

**Comment by tbpg** [comment]
The build URL is configured here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.kokoro/tests/run_tests.sh#L117

So, you can change it to whatever URL you prefer.

Perhaps we should allow more than one URL, that way we could have public and private links to logs?

**Comment by shollyman** [comment]
If we're able to generate multiple URLs, perhaps construct a history search URL as well so we can see the trend of a failing test over time (flakes, execution time, etc)?

**Comment by tbpg** [comment]
You should theoretically be able to put markdown into the URL field -- I haven't tried it. But, you can almost definitely just do space-separated links and have it work.

If an issue gets closed and the test fails again, the bot will reopen the issue. So, I don't think we need a link for history.

**Comment by tbpg** [comment]
I updated the logs field to include links to Build Status and Sponge. For example, see https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2894#issuecomment-588542426. Marking this as fixed.
