### ISSUE TITLE
Owlbot is installed on odd external repository

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2750]
OwlBot is installed on a strange external dependency:

```
 Error creating label owlbot:ignore in QPC-WORLDWIDE/bioconda-repodata-archive-old Repository is above its size quota.
Error creating label owlbot:ignore in QPC-WORLDWIDE/bioconda-repodata-archive-old Repository is above its size quota.
```

This appears to be interfering with our ability to complete the label sync job successfully.

**Comment by tmatsuo** [comment]
I'll take a look on Monday

**Comment by tmatsuo** [comment]
> Can people install Owl bot on repos outside the googleapis org?

I think so.

I'd like to know the list of google owned organizations, so that we can safely filter out the cron job.

But I think some of the bots are legitimately installed on repositories outside our org (release-please).

**Comment by tmatsuo** [comment]
Let's make it P1.

We should do the following for band aid:

- [ ] Limit cron requests to `googleapis` and `googlecloudplatform` for most of the bots
- [ ] Drop Github webhooks for anything other than `googleapis` and `GoogleCloudPlatform` in OwlBot

**Comment by SurferJeffAtGoogle** [comment]
This issue is now OoSLO and I have no time to work on it.  @tmatsuo, do you have time?

**Comment by tmatsuo** [comment]
@SurferJeffAtGoogle Sure
