### ISSUE TITLE
Flakybot does not appear to accept external_account permissions

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#2752]
I am trying to use Flakybot along with GOOGLE_APPLICATION_CREDENTIALS in a GitHub Action using our WIF/OIDC provider.  The credential file for OIDC will look something like this:
https://github.com/googleapis/google-auth-library-nodejs/blob/main/test/fixtures/external-account-cred.json

I am getting this error from flakybot while trying to use it:
```
[FlakyBot] Unable to connect to Pub/Sub: pubsub: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: unknown credential type: "external_account"
```

The failure is here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/runs/3972078689?check_suite_focus=true

And the CI config here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/workflows/healthcare-datasets.yaml#L41

**Comment by chingor13** [comment]
This looks like it's working: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/runs/4425468063?check_suite_focus=true
