### ISSUE TITLE
release-please closed a PR it did not open

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#277]
release-please bot closed a PR that it did not open. The PR updated a dependency in the setup.py.

See https://github.com/googleapis/python-storage/pull/45

![image](https://user-images.githubusercontent.com/8822365/74269832-008e1f00-4cbf-11ea-8b9b-254e6f37e764.png)

**Comment by chingor13** [comment]
Maybe fixed by: https://github.com/googleapis/release-please/pull/358
