### ISSUE TITLE
`google-cloud-policy-bot` is removing `api: bigquery` label

### ISSUE THREAD

**Issue by tswast** [googleapis/repo-automation-bots#2782]
1) Is this a client library issue or a product issue?

`google-cloud-policy-bot`

2) Did someone already solve this?

Not found in https://github.com/googleapis/repo-automation-bots/issues?q=is%3Aissue+google-cloud-policy-bot+is%3Aclosed

3) Do you have a support contract?

N/A

#### Environment details

N/A

#### Steps to reproduce

  1. Make a repo out-of-compliance, such as by enabling merge commits.
  2. Notice that `product-auto-label` adds the `api: bigquery` label and `google-cloud-policy-bot` removes it once every 24 hours.

![example of a bot fight](https://user-images.githubusercontent.com/247555/138754089-c32044cc-a8ac-4c6f-b142-3cdb460c3101.png)

See: https://github.com/googleapis/python-bigquery/issues/1020

**Comment by JustinBeckwith** [comment]
Pretty sure I fixed this one earlier in the week :)
