### ISSUE TITLE
bug: experiencing timeout in a bazel bot cloud build

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2786]
Example build:
https://pantheon.corp.google.com/cloud-build/builds;region=global/c20ef490-5b9a-4217-bc43-42e910e7a9b3;step=1?project=repo-automation-bots

**Comment by bcoe** [comment]
@tmatsuo this goes out of SLO relatively soon, mind checking and seeing if it's continuing to happen.

**Comment by tmatsuo** [comment]
It's not happening often
