### ISSUE TITLE
bug(owl-bot): owlbot tries to run on archived repo 

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2796]
https://github.com/googleapis/python-identity-toolkit is archived (read-only). Owlbot shouldn't run on repos that are read-only.

See [build log](https://pantheon.corp.google.com/cloud-build/builds;region=global/ad428821-3625-418f-9254-8345081556c1?project=repo-automation-bots).

**Comment by parthea** [comment]
Also see https://pantheon.corp.google.com/cloud-build/builds;region=global/745ceeda-98e8-4d6f-b032-166c757ec2cb;step=11?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
I haven't figured out why this build was triggered.  The corresponding branch doesn't exist and I find no pull request that would have triggered it.

There is logic in Owl Bot to not create pull requests on archived repos.
