### ISSUE TITLE
FR(OwlBot): OwlBot should not open a PR in the first place if it's going to be a noop

### ISSUE THREAD

**Issue by dazuma** [googleapis/repo-automation-bots#2834]
Currently, if OwlBot detects that, after post-processing, the pull request that it is opening would result in no changes (either because the postprocessor nullifies them, or because the changes have already been applied from a separate PR), it closes the PR automatically. Here's an example: https://github.com/googleapis/google-cloud-ruby/pull/15743

It's great that OwlBot closes the PR automatically so we don't have to do it ourselves. It would be MUCH better if OwlBot could detect this condition up front before opening the pull request, and not open it in the first place.

This would be useful for monorepo workflows in which a microgenerator change results in a trivial modification to _all_ generated libraries. Normally, when the Ruby team releases such a microgenerator change, it would result in OwlBot opening hundreds of pull requests in response, one per library, which we then have to deal with (using some custom scripts we've written). However, since we have a monorepo, we've also experimented with kicking off a custom Bazel/OwlBot run outside the normal process when switching the microgenerator version, resulting in a _single_ pull request that includes the expected changes from all libraries, i.e. it aggregates the diffs from all those hundreds of pull requests into a single PR that we can merge at once. This has worked great, except that OwlBot then runs anyway, opening all those hundreds of pull requests, and then immediately closing them because our single mega-pr had already made the changes, resulting in a lot of useless noise in our repo, as well as a lot of useless load on our CI. (This also, incidentally, is how #2829 originally manifested.)

**Comment by SurferJeffAtGoogle** [comment]
Some points that make this non-trival:
1. It will take a lot of work because Owl Bot has to run the post processor to know that there will be no changes.
2. We'll have to record that Owl Bot generated the code but did not create a pull request in a database, and look at that database later when deciding what work needs to be done.

**Comment by dazuma** [comment]
I understand it's not trivial. The current behavior is still annoying, though. The latest incident is that when the year turned over to 2022, bazelbot regenerated every library with changed copyright years, which triggered OwlBot to attempt to open pull requests for every library. Ruby's OwlBot postprocessor preserves the original copyright year, so all the pull requests ended up being noops, and were closed, but now the Ruby team has ~300 additional useless closed pull requests in our repo, and ~300 x 5 = ~1500 additional useless email notifications from github in our inboxes today.

**Comment by jskeet** [comment]
+1 to this FR. Some additional benefits to not opening the PR until the final result is ready:

- Users are disturbed (by notifications) just once
- The link generated in the GitHub email will be useful, instead of referring to an invalid commit
- The emails generated will be much smaller, certainly for C# - the first email (before post-processing) always contains a large number of files, because they're all in the staging directory (so are all new). The email is much more useful if it shows the *actual* files that have been changed.

**Comment by SurferJeffAtGoogle** [comment]
A pathological case:
1. PR A introduces a bug.
2. PR B rolls back PR A an hour later.

With the proposed fix, assuming PR A lingers for a few hours, Owl Bot would never open PR B.  It would only open PR A.   A maintainer would merge PR A and never see PR B.  The code would not get rolled back until the next API change happened to arrive.

With the current Owl Bot implementation, a maintainer will see PR B open and close.

@dazuma and @jskeet Do you prefer risking not seeing rollbacks over seeing noop PRs open and close?

**Comment by jskeet** [comment]
Ouch, that *is* a nasty situation. I suspect what I'd really like is for merging PR A to trigger OwlBot to think "Is this actually up-to-date" and run again (which would normally end up in a no-op; in the case you describe it would be a roll-back PR). Not sure that's the right way forward, but it's just a thought.

**Comment by SurferJeffAtGoogle** [comment]
With the "is it up to date strategy?" it was sometimes impossible to identify what triggered changes when the repo was not up to date.  Autosynth couldn't provide context in that situation.

**Comment by jskeet** [comment]
That makes sense - but I think it's still better to know "Something has caused this to change - you should investigate" than not know that it's up-to-date.
(Maybe that could just be a nightly check, indeed - just run OwlBot against everything as a precaution.)

**Comment by SurferJeffAtGoogle** [comment]
> That makes sense - but I think it's still better to know "Something has caused this to change - you should investigate" than not know that it's up-to-date. (Maybe that could just be a nightly check, indeed - just run OwlBot against everything as a precaution.)

That's a separate feature request.  For now, I'm seeking confirmation that we still want Owl Bot to not open noop PRs.

**Comment by jskeet** [comment]
But they're related... if it's a choice between "if something untoward happens, you may never, ever find out" and "you need to handle grungy emails and delete stale branches" I'd probably suck it up and take the annoying chores.

If it's a choice between "if something untoward happens, you may need to do some investigation" and handling grungy emails/branches, I'm happy to take the first option.

(I don't know how Daniel feels about any of this, of course.)

**Comment by SurferJeffAtGoogle** [comment]
Thanks,  I'll wait for Daniel's input.

**Comment by dazuma** [comment]
So for your pathological case:

> 1. PR A introduces a bug.
> 2. PR B rolls back PR A an hour later.
>
> With the proposed fix, assuming PR A lingers for a few hours, Owl Bot would never open PR B. It would only open PR A. A maintainer would merge PR A and never see PR B. The code would not get rolled back until the next API change happened to arrive.
>
> With the current Owl Bot implementation, a maintainer will see PR B open and close.

In practice, I suspect most language maintainers will not actually notice PR B open and close, as it will get lost in the noise. If something untoward happens, I definitely prefer a persistent, actionable state change like an open issue or PR over something transient, even if it means losing automatic context. In an abnormal case like this, I'd expect to have to do some investigation anyway, and I _want_ it to occupy my attention, so I think it's better if abnormal cases require more work if it means less noise and grunge for normal cases.

**Comment by dazuma** [comment]
...in other words, I think I still would rather Owl Bot not open noop PRs. I don't think it's significantly worse than the current behavior, even for the pathological case.
