### ISSUE TITLE
FR(OwlBot): A way to tell OwlBot to combine monorepo PRs for a particular commit

### ISSUE THREAD

**Issue by dazuma** [googleapis/repo-automation-bots#2835]
This may be a bit of a fringe use case, and I'm not entirely sure how feasible it is, but it would be very useful for certain monorepo use cases. Specifically, I'd like a way to annotate a particular commit (coming from googleapis) to tell OwlBot that, in the monorepo case, it should open a _single_ pull request aggregating the corresponding changes to _all_ of the libraries, rather than a separate pull request for each library. The default behavior should remain as it is currently, but in certain special cases, I'd really like the pull requests to be combined.

The specific use case this addresses, is when I push an update to the microgenerator that results in some trivial change to _all_ libraries in our monorepo. It would be nice for those to be rolled up into a single pull request rather than hundreds of separate pull requests that I have to deal with using scripting. I'm currently handling cases like this by running a [custom "bazel/owlbot" script](https://github.com/googleapis/google-cloud-ruby/blob/main/.toys/owlbot.rb) locally, opening a pull request and merging it manually before OwlBot runs. [Here is an example](https://github.com/googleapis/google-cloud-ruby/pull/15697) of such a pull request, corresponding to [this change](https://github.com/googleapis/googleapis/commit/1112610c52e16454fde0f1a28bfec7846e6e008d) to the Ruby microgenerator. (Note: as a result, OwlBot still opens its pull requests but closes them immediately since the change has already been made. [Here](https://github.com/googleapis/google-cloud-ruby/pull/15743) is an example of one of those pull requests. I'd also like for OwlBot not to open these pull requests in the first place if they are going to be noops, and have opened #2834 to that end.) What I'm hoping for here is a way to tell OwlBot to do this so I don't have to do it manually using my custom scripts.

**Comment by SurferJeffAtGoogle** [comment]
Working on it....
