### ISSUE TITLE
bug(m-o-g): `resource not accessible by integration` even though it works in other PRs in that repo

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2866]
https://github.com/googleapis/java-recaptchaenterprise/pull/630

^^ MOG fails with this log:

```2021-11-09 10:16:22.661 PST merge_on_green w7y8u16qn1ks Failed to merge "Resource not accessible by integration: " googleapis/java-recaptchaenterprise/630 Resource not accessible by integration```

https://pantheon.corp.google.com/functions/details/us-central1/merge_on_green?project=repo-automation-bots&tab=logs

Even though the next one passed: https://github.com/googleapis/java-recaptchaenterprise/pull/631

cc @lesv

**Comment by meltsufin** [comment]
A few more examples:
https://github.com/googleapis/java-service-management/pull/158
https://github.com/googleapis/java-data-fusion/pull/82
https://github.com/googleapis/java-billing/pull/558

**Comment by tmatsuo** [comment]
FWIW, failing examples are all from renovate, which means they are from a fork.

**Comment by tmatsuo** [comment]
Commit history for mog:
https://github.com/googleapis/repo-automation-bots/commits/main/packages/merge-on-green

**Comment by tmatsuo** [comment]
Message before dying:

```
message: "Is googleapis/java-recaptchaenterprise/630 mergeable?: true Mergeable_state?: clean"
```

Stack:

```
"HttpError: Failed to merge "Resource not accessible by integration: " googleapis/java-recaptchaenterprise/630

Resource not accessible by integration
    at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:466:12)
    at async merge (/workspace/build/src/merge-logic.js:310:20)
    at async mergeOnGreen (/workspace/build/src/merge-logic.js:437:13)
    at async /workspace/build/src/merge-on-green.js:308:32
    at async Promise.all (index 1)
    at async Function.checkPRMergeability (/workspace/build/src/merge-on-green.js:305:9)
    at async /workspace/build/src/merge-on-green.js:446:9"
```

**Comment by tmatsuo** [comment]
My current hypothesis is that Github changed something and we can not merge PRs from a fork now.

Let me know if you see successful merge on a PR from a fork.

**Comment by tmatsuo** [comment]
Support ticket filed:
https://support.github.com/ticket/personal/0/1391070

**Comment by SurferJeffAtGoogle** [comment]
Any news?  This issue will become OoSLO soon.

**Comment by tmatsuo** [comment]
Unfortunately no

**Comment by sofisl** [comment]
I'm investigating. 

Currently, I have reproduced the issue locally, and confirmed it's not just tied to Java repos, happens on Node repos as well.

**Comment by sofisl** [comment]
Further news, MOG can merge from forks on GoogleCloudPlatform, just not on googleapis. I'm not sure why, @chingor13 checked and there doesn't seem to be any significant difference in settings.

**Comment by sofisl** [comment]
I think this issue has resolved itself, see:

https://github.com/googleapis/java-cloud-bom/pull/3224
https://github.com/googleapis/java-cloud-bom/pull/3224

I will close for now, but ready to reopen if/when this starts happening again.

**Comment by bcoe** [comment]
This continues to happen periodically, and I suspect is us bumping into an undocumented secondary issue with GitHub's infrastructure.

We have an ongoing support case with GitHub.
