### ISSUE TITLE
bug(owl-bot): owlbot-scan-googleapis-gen-and-create-pull-requests hitting 2 hours timeout

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2868]
Past few builds had hit this limit (2 hours).
Example builds:

https://pantheon.corp.google.com/cloud-build/builds;region=global/b7413fa0-08b6-43af-823f-b7019633fbdd?project=repo-automation-bots

https://pantheon.corp.google.com/cloud-build/builds;region=global/f5148a62-10ca-45b7-ba30-25ca160ed7c0?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
Timing out is not a problem. It's useful to have a two-hour time out, because the process kicks off every hour, and having N overlapping jobs running at the same time won't improve throughput.

**Comment by SurferJeffAtGoogle** [comment]
In other words, a job that times out at 2 hours still makes some progress before the 2 hour deadline, so the next job has less work to do.
