### ISSUE TITLE
merge-on-green-sync-labels scheduled task is failing

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#2901]
![image](https://user-images.githubusercontent.com/11778530/141831500-8db9d2b1-3022-4939-ad62-8264297bc3dc.png)

**Comment by SurferJeffAtGoogle** [comment]
I see it failing again today.

**Comment by tmatsuo** [comment]
I think it fails for the same reason as #2902.
