### ISSUE TITLE
release-trigger : release was not triggered from branch 1.111.0-sp in java-pubsub

### ISSUE THREAD

**Issue by Neenu1995** [googleapis/repo-automation-bots#2903]
Java-pubsub needed a patch release from an LTS branch. But the releases were not automatically triggered in multiple release PRs. The following PRs track the retries before the final release.

1. [Release PR 1](https://github.com/googleapis/java-pubsub/pull/911) : release was not triggered and then manually triggered. Manually triggered release failed because it was still publishing to the old sonatype endpoint which has been turned off.
2. [PR](https://github.com/googleapis/java-pubsub/pull/918) to add release trigger : release-trigger.yml was added to make sure release trigger is enabled.
3. [Release PR 2](https://github.com/googleapis/java-pubsub/pull/917) : Manually triggered a release which failed. Then release-please tagged and triggered the release, but failed again(due to a known and expected reason).
4. Fixed the reason for release failure and tried again.
5. [Release PR 3](https://github.com/googleapis/java-pubsub/pull/923) : Did not trigger automatically. Triggered manually and release succeeded.

**Comment by chingor13** [comment]
The trigger bot looks for PRs labeled `autorelease: tagged`. For PR 1 & 3, these PRs were not labelled tagged. After correcting the release-please.yml config 

PR 2 is not an error case at all, it triggered but the actual release job failed (out of the bots' scopes).

The only issue here is PR 3 from yesterday. https://github.com/googleapis/java-pubsub/pull/921 should have made it so release-please would tag the github release which would have triggered the release-trigger bot.
