### ISSUE TITLE
bug: anthos dpe team PRs not labelled properly.

### ISSUE THREAD

**Issue by Shabirmean** [googleapis/repo-automation-bots#2986]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
```
- This is related to the following client-libraries:
    - [java-container](https://github.com/googleapis/python-container)
    - [nodejs-cloud-container](https://github.com/googleapis/nodejs-cloud-container)
    - [google-cloud-php-container](https://github.com/googleapis/google-cloud-php-container)
    - [python-container](https://github.com/googleapis/python-container)
```

2) Did someone already solve this?
```
- Nope, was directed here via @JustinBeckwith 
```
3) Do you have a support contract?
```
- Google internal team - Anthos/GKE 
```

#### Issue:
PRs from all the container client libs _(listed above)_ except `python-container`, are tagged as team `core` instead of the `anthos`. As a result the Anthos/GKE team dashboard is not showing any of these PRs. The problem here seems to be that the `api: container` label is not getting added in these repositories.

Is there a reason why this is not happening automatically? Is there something we (the Anthos/GKE team) has to do to get this happening?

**Comment by sofisl** [comment]
According to the thread, seems like this was addressed but we'll need to confirm before closing.

**Comment by Shabirmean** [comment]
This has been resolved as explained in the internal chat thread. @sofisl closing this!
