### ISSUE TITLE
feat(owl-bot): Add a subdirectory name to owlbot PRs on google-cloud-php

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3028]
We've migrated multiple APIs to owlbot on google-cloud-php repo.

An example PR:
https://github.com/googleapis/google-cloud-php/pull/4752

The title doesn't have the API name.
An example: `chore(bazel): Update gapic-generator-php to v1.2.1`

My suggestion is to add the API name after the colon like this: `chore(bazel): [Billing] Update gapic-generator-php to v1.2.1`

@bshaffer What do you think?

**Comment by bshaffer** [comment]
That would be perfect!

**Comment by bshaffer** [comment]
It would also be great to have the commit messages match this, so that when we merge the PR the commit also contains the API being updated.

**Comment by bshaffer** [comment]
See https://github.com/googleapis/repo-automation-bots/issues/3063 for more info

**Comment by SurferJeffAtGoogle** [comment]
I'm working on this now.

**Comment by tmatsuo** [comment]
To clarify, we still need to add a field in the config files in the php repo.
