### ISSUE TITLE
OwlBot PR / commit messages are long and get truncated

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#3039]
## Overview

See https://github.com/googleapis/google-cloud-php/pull/4851

The commit language is the concatenation of multiple CL messages. The result looks like this:

```
feat: add the AcknowledgeUserDataCollection operation which
acknowledges the terms of user data collection for the specified
property feat: add the new resource type DataStream, which is
planned to eventually replace WebDataStream, `IosAppDataStr...
```

## The Problem

1. concatenating multiple "conventional commits" is not (as far as I know) a valid way to use conventional commits
2. The "conventional commit" prefix comes from only the first one. If there was a `fix` followed by a `feat`, the PR would only be prefixed with `fix` (In the example above, a `fix!` commit is ignored in the update PR, so the BC-breaking flag is lost)
2. The commit message is too long (and extends past the PR title maximum length)
3. The commit message gets truncated, and extends into the message description, which then breaks formatting with the code-highlighting backticks (see the above linked issue)

## The Solution

When a PR contains multiple CL updates to the protos, make the PR title (and first line of the commit) generic, with the individual updates getting their own lines beneath it. Something like this:

```
[AnalyticsAdmin] feat: multiple updates
feat: add the AcknowledgeUserDataCollection operation which acknowledges the terms of user data collection for the specified property
feat: add the new resource type DataStream, which is planned to eventually replace WebDataStream, `IosAppDataStream`, `AndroidAppDataStream` resources
fix!: remove `GetEnhancedMeasurementSettings`, `UpdateEnhancedMeasurementSettingsRequest`, `UpdateEnhancedMeasurementSettingsRequest` operations from the API
feat: add `CreateDataStream`, `DeleteDataStream`, `UpdateDataStream`, `ListDataStreams` operations to support the new `DataStream` resource
feat: add `DISPLAY_VIDEO_360_ADVERTISER_LINK`,  `DISPLAY_VIDEO_360_ADVERTISER_LINK_PROPOSAL` fields to `ChangeHistoryResourceType` enum
feat: add the `account` field to the `Property` type docs: update the documentation with a new list of valid values for `UserLink.direct_roles` field
```
The parser would need to be updated to look at each commit and take the most meaningful semantic keyword. In this case, `fix!` would need to be combined with `feat` to create `feat!`.

**Comment by chingor13** [comment]
The root of this bug is in copybara - it should take the first line of the public commit message as the commit message and the rest as the extended body. Because the commit on the upstream commit is truncated, it might be difficult to reparse the message.

The workaround is to edit the message yourself and make sure the subsequent commit messages are in the body as footers of the merge commit to main. Here's an example: https://github.com/googleapis/nodejs-dialogflow-cx/pull/206 Release-please knows how to handle all of these messages in the release notes.

**Comment by bshaffer** [comment]
So how do we fix it? We'll need to submit a PR to google/copybara?
