### ISSUE TITLE
bug: update PR runs even if PR is up-to-date with main branch

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#304]
Now that _merge-on-green_ is a trusted contributor (hooray, thanks @chingor13 and @sofisl) I noticed that we never merge PRs, because every time we update a branch it re-kicks-off-tests.

There seem to be two potential fixes, a quick fix is to only `update` the branch if the merge fails:

```js
    if (checkReview === true && checkStatus === true) {
		let merged = false;
        try {
          	console.info(`attempt to merge ${owner}/${repo}`);
        	await mergeOnGreen.merge(owner, repo, pr, github);
          	merged = true;
        } catch (err) {
          console.info(err);
            await mergeOnGreen.updateBranch(owner, repo, pr, github);
        }
      	return merged;      
    }
```

This works because when an attempt is made to merge a PR that isn't up-to-date, the following error is thrown:

```bash
A 2020-02-20T06:20:50.733Z merge_on_green mz3c7l1c3kdv { HttpError: Pull Request is not mergeable merge_on_green mz3c7l1c3kdv 
A 2020-02-20T06:20:50.733Z merge_on_green mz3c7l1c3kdv     at response.text.then.message (/srv/functions/node_modules/@octokit/request/dist-node/index.js:66:23) merge_on_green mz3c7l1c3kdv 
A 2020-02-20T06:20:50.733Z merge_on_green mz3c7l1c3kdv     at process._tickCallback (internal/process/next_tick.js:68:7) merge_on_green mz3c7l1c3kdv 
A 2020-02-20T06:20:50.733Z merge_on_green mz3c7l1c3kdv   name: 'HttpError', merge_on_green mz3c7l1c3kdv 
```

---

A better fix might be to eventually determine whether or not a branch is up-to-date with `master`, and only call `update` if necessary.

I suggest that we land the quick fix first, but with our sights set to the more thorough fix.

**Comment by sofisl** [comment]
Hope it's ok to close these issues, assuming we've addressed the issues :)
