### ISSUE TITLE
Snippet bot is mad at datascienceonramp again

### ISSUE THREAD

**Issue by leahecole** [googleapis/repo-automation-bots#3050]
Hi! 

I thought that https://github.com/googleapis/repo-automation-bots/pull/1739 meant that we support the `datascienceonramp` product prefix in snippet bot, but snippet bot is currently saying I'm in violation for that product prefix reason on https://github.com/GoogleCloudPlatform/python-docs-samples/pull/7301. Any insights as to why would be appreciated! 🤖 ❤️

**Comment by tmatsuo** [comment]
Oops I missed this issue. Looking into the internal database.

**Comment by tmatsuo** [comment]
The snippet bot refers to the devrel service database and uses `product` and associated `product prefix` registered in that service. I recommend that you register it there, but if you think it's not worth the effort, you can always add `snippet-bot:no-prefix-req` label to tell the bot to ignore the product prefix requirement.
