### ISSUE TITLE
owlbot: large /google/chromeos/uidetection lib in googleapis-gen failing to build

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3054]
There's a large library in `googleapis-gen` which seems to consistently fail to build:

https://pantheon.corp.google.com/cloud-build/builds;region=global/8fe4c8a0-355d-470e-ab90-29c5e19f627d;step=3?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
I think this was a temporary quota or auth issue.
```
    at async Object.getGitHubShortLivedAccessToken (/usr/src/app/build/src/core.js:213:18)
```
