### ISSUE TITLE
owlbot: strange behavior on regenerating an open PR

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#3069]
Related to #3068, but not the same. I've seen additional strange behavior when regenerating an open PR - sometimes, the previously generated changes disappear, as if new changes take precedence.

See https://github.com/googleapis/google-cloud-php/pull/4914
You'll see my review changes are "outdated" which were made in https://github.com/googleapis/google-cloud-php/commit/d0871b16261b73c4f545b67f2ae2a193d0be149a and no longer exist after the update https://github.com/googleapis/google-cloud-php/pull/4914/commits/359830f193ae9b631f133ec4db0c1d40da588f69, even though those lines still need to be removed from the PR as per `owlbot.py`. This happened in https://github.com/googleapis/google-cloud-php/pull/4989 as well (on the same lines of code)

In both cases, it was changes from `owlbot.py` which were ignored. To make the issue stranger, I've regenerated multiple PRs where this issue did not take place, and the changes were updated as expected.

**Comment by SurferJeffAtGoogle** [comment]
I'll try to paraphrase to confirm my understanding: The first set of changes to #4919 included changes to owlbot.py.  When you clicked the regenerate check box, you expected Owl Bot to use the new changes to owlbot.py.  Instead, Owl Bot used the original contents of owlbot.py.  Is my understanding correct?

**Comment by bshaffer** [comment]
This one is WAD. OwlBot generated TWO PRs for the same component, and I merged one and didn't realize it was for the same PR, so the changes that were in the other went away. My mistake.

This was the merged PR: https://github.com/googleapis/google-cloud-php/pull/4981
