### ISSUE TITLE
FR(OwlBot) Delete branches for auto-closed PRs

### ISSUE THREAD

**Issue by jskeet** [googleapis/repo-automation-bots#3071]
When OwlBot creates a PR with a staging directory, runs the post-processor, then closes the PR when it notices there aren't any actual changes, we get left with a branch in the repo.

It would be nice if OwlBot could automatically delete the branch.

**Comment by jskeet** [comment]
Today I need to delete 140+ branches because of this... and GitHub doesn't have "select all" in lists of branches :(

**Comment by SurferJeffAtGoogle** [comment]
#3150 logs when it would delete the branch.  I want to confirm that it's deleting the *right* branch by seeing a few log messages in production.
