### ISSUE TITLE
owlbot: new post-processor image PRs should strip issue number from the PR title

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3098]
Example PR: https://github.com/googleapis/release-please/pull/1228

The commit to googleapis/synthtool that created the new image was number 1085, but when this PR is created and automerged to the repository, it references an irrelevant PR in that repo.

Ideally, we strip the PR `(#1085)` part from the pull request message and (nice to have) put a full link to the source pull request in the PR body.

**Comment by SurferJeffAtGoogle** [comment]
I think @parthea implement this for Python.  Is there a flag that can be set?

**Comment by parthea** [comment]
This issue was fixed in the cloud build file for python `docker/owlbot/python/cloudbuild.yaml`. See https://github.com/googleapis/synthtool/pull/1137. Assigning to @chingor13 to take a look.

**Comment by chingor13** [comment]
Will that strip multiple conventional commit messages though?
