### ISSUE TITLE
bug: bazel bot job failed at 32 min

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#3115]
packages-bazel-bot-run-preview trigger failed

https://pantheon.corp.google.com/cloud-build/builds;region=global/015822a7-d3f7-4fc9-9d4f-1119828baa42;step=1?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
Strange.  I can't explain why it failed but it was transient, because later builds have succeeded.
