### ISSUE TITLE
release-trigger: release trigger has not been triggering for some publish jobs

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3120]
release-trigger has not been triggering for some publish jobs, e.g.,

https://github.com/googleapis/nodejs-spanner/pull/1557

This may relate to #3105, but also seems to correlate with lock added.

**Comment by chingor13** [comment]
There was a window of 15 hours or so when the bot didn't have permissions to use the lock which has since been fixed.

To force a trigger, you can add the `autorelease: triggered` label and then remove it.
