### ISSUE TITLE
FR(owlbot): Add a label that will trigger an owlbot PR to be regenerated

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3128]
PRs created by [owl-bot](https://github.com/googleapis/repo-automation-bots/tree/main/packages/owl-bot) currently have a checkbox with the text `Regenerate this pull request now`. Once the checkbox is clicked, owlbot adds comment `Owl bot is regenerating pull request X` and shortly after the PR is re-generated. It would be great to have the ability to add a label instead of having to click the checkbox.

**use case:**
The label will allow us to use the [repo](https://github.com/googleapis/github-repo-automation) tool to regenerate owlbot PRs in bulk, which is helpful when the owlbot PRs have conflicts that need to be resolved. These conflicts will automatically be resolved once the owlbot PR is regenerated.

Example usage with repo tool to regenerate all owlbot PRs with a specific title
`repo tag --author 'gcf-owl-bot[bot]' --title <your awesome title>  owlbot:regenerate`

One suggestion for the label name could be `owlbot:regenerate` but I don't have a strong preference.

**Comment by SurferJeffAtGoogle** [comment]
In a conversation on 3/14, Tony and I discussed how there isn't a pressing use case for this.
