### ISSUE TITLE
Occaissonal authentication error for Bazel Bot

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3134]
I've seen a few instances of the [this error](https://pantheon.corp.google.com/cloud-build/builds;region=global/36ed6ca4-a4a3-4edc-bbfd-d5d75f45ba6a?project=repo-automation-bots) in bazel bot:
```
Step #1: Cloning into 'googleapis-gen'...
Step #1: remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
Step #1: remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
Step #1: fatal: Authentication failed for 'https://x-access-token:null@github.com/googleapis/googleapis-gen.git/'
```

Which makes no sense because Owl Bot is using token authentication:
https://github.com/googleapis/repo-automation-bots/blob/9319304c05f4840870c26f7cd9e41f6d2d126c16/packages/bazel-bot/docker-image/docker-main.sh#L44

Perhaps the earlier `curl` command that fetches the token sometimes fails?

Not sure what's happening yet,  and bazel bot succeeds in the next run.

**Comment by bcoe** [comment]
Just following up that I've noticed this a few times over the past few days.
