### ISSUE TITLE
PHP: "Chore" messages fail to generate in release PRs

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#3145]
We've noticed that "chores" aren't showing up in the release notes for any component (see [cloud-contact-center-insights](https://github.com/googleapis/google-cloud-php/pull/5029))

However, they appeared correctly in the release notes for our release which contained [only compute](https://github.com/googleapis/google-cloud-php/pull/5022).

So I think maybe something broke in the parsing of the chores when the release contains more than one component.

**Comment by chingor13** [comment]
The `chore` commit only appears because it used a `Release-As` footer which was by design (I'm not sure from when). Other `chore` commits should be ignored.

**Comment by bshaffer** [comment]
But what if we don't want this behavior? Release notes are confusing when empty...
