### ISSUE TITLE
PHP: "gcf-owl-bot[bot]" appears twice in the commit message

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#3146]
As of this week, all commits from `gcf-owl-bot` show two authors in the commit message:

<img width="518" alt="Screen Shot 2022-01-27 at 6 08 32 PM" src="https://user-images.githubusercontent.com/103941/151995823-e10549e9-1ff6-4468-ad4b-b2f3a04f76a4.png">

This can be seen [in the commit here as well](https://github.com/googleapis/google-cloud-php/commit/eda71e56c5ab91ec9224770f17a2d16c2c46a025).

I believe this is because the `Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>` at the bottom, which I can manually remove, but I'm confused why this is there in the first place. Can we ensure it's not there by default?

**Comment by SurferJeffAtGoogle** [comment]
Owl Bot doesn't add the `Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>` text.  Github adds it.  What criteria does Github use to determine whether to add the text?

**Comment by SurferJeffAtGoogle** [comment]
Brent, this is certainly annoying, but as far as I can see, Github doesn't provide an avenue for us to fix it.  If you see one, please re-open this issue.
