### ISSUE TITLE
conventionalcommits bot linting feedback is very hard to see

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/repo-automation-bots#3155]
https://github.com/googleapis/python-aiplatform/pull/997/checks?check_run_id=5046838432

Can you spot the error?

![image](https://user-images.githubusercontent.com/1829149/152280117-b5e86c11-775f-4ad6-bfd4-c25adbaf1f6e.png)

**Comment by tmatsuo** [comment]
I agree. It seems like you somehow solved it. What was the problem causing it?

**Comment by Ark-kun** [comment]
I might have worked around the submission error issue, but that's not the point of this issue which is "conventionalcommits bot linting feedback is very hard to see". That issue is not solved.

If experienced developers like you and me are unable to see why `conventionalcommits` rejected a seemingly correct commit title, then we have a problem.

Sorry for playing the "can you spot it" game, but it's all in my screenshot.

**Comment by tmatsuo** [comment]
Ah it's already posting the reason, but it's at the bottom of the message. We can change the order then it's obvious.
