### ISSUE TITLE
FR(owl-bot): PR body is not updated when owlbot appends commits to an open PR

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3179]
Owlbot opened PR: https://github.com/googleapis/python-billingbudgets/pull/174 on February 10th. One day later, owlbot added commit `ade2836` (see screenshot below) which included conventional commit messages however these new conventional commit messages weren't added to the PR body. After I clicked the `Regenerate this pull request now` button , the owlbot regenerated the PR and the conventional commit messages appeared in the PR body. Ideally owlbot should append conventional commit messages to the PR body as new commits are added. Another solution is for owlbot to automatically regenerate the entire PR (similar to clicking the 'regenerate this pull request now' checkbox) rather than adding separate commits.

![image](https://user-images.githubusercontent.com/5184014/153645226-2fe36a1e-32c4-416e-baad-b07b5ae3ae92.png)

**Comment by SurferJeffAtGoogle** [comment]
The reason that Owl Bot doesn't automatically regenerate the PR is that a maintainer may have added some manual commits to the open PR.  Appending new commits preserves the manual commits, where as regenerating the PR would ablate them.
