### ISSUE TITLE
False positives for "Too many OwlBot updates created in a row"

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3196]
Now that Owl Bot creates additional commits to open PRs, it will generate more commits in a row.  It's working as intended and the post processor shouldn't refuse to run. 

Example: https://github.com/googleapis/nodejs-document-ai/pull/310

**Comment by SurferJeffAtGoogle** [comment]
The strategy we discussed today of examining the title may not work.  When we saw the infinite loop, wasn't it two bots flip flipping?

**Comment by SurferJeffAtGoogle** [comment]
I found the original fix for the infinite loop, but I haven't found a bug report.
https://github.com/googleapis/repo-automation-bots/pull/1496

**Comment by bcoe** [comment]
The bug that came up motivating the circuit-breaker was a bad Java image which flip flopped the date, history would be in synthtool repo.
