### ISSUE TITLE
No new post-processor PRs

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#3219]
While bilge pumping, I noticed we haven't created [any new owl-bot-update PRs](https://github.com/search?q=org%3Agoogleapis+label%3A%22owl-bot-update-lock%22+is%3Aopen
) in the last 7 working days (last one was 10 days ago). I don't think any new language has released a new image lately so this might make sense, but creating an issue to track and investigate.

**Comment by SurferJeffAtGoogle** [comment]
I see a bunch from 3 days ago.  I think it was just a lull.
