### ISSUE TITLE
release-please: Release please is ignoring commits in multi-commit owlbot PRs

### ISSUE THREAD

**Issue by Neenu1995** [googleapis/repo-automation-bots#3220]
Owlbot behaviour changed recently to add multiple commit to the same PR as opposed to multiple PRs. This appends multiple commits with their contexts in the PR body. Release-please used to pick up all commit messages with conventional commit prefix(feat, fix, deps etc) and add it to the release notes in release PR. Now it is only picking the commit message in the title and not in the body.
Example PR: https://github.com/googleapis/java-common-protos/pull/322

![image](https://user-images.githubusercontent.com/13271327/155615184-d1eb81bd-6352-449f-85f6-7c7ceb3a09f0.png)

Proposed release PR only has the title commit.

Example release PR: https://github.com/googleapis/java-common-protos/pull/326

![image](https://user-images.githubusercontent.com/13271327/155615320-d42f7136-ddd8-4080-9b91-77819914013a.png)

**Comment by parthea** [comment]
The only solution I have found for this issue is to use the `automerge` label to merge PRs. It would be great to have another solution as I've noticed `automerge` can take several minutes to merge depending on how large the backlog is.

**Comment by bcoe** [comment]
When merging a PR the content looks like this if it's not manually cleaned up:

```
* feat: Update Logging API with latest changes

PiperOrigin-RevId: 429289471

Source-Link: https://github.com/googleapis/googleapis/commit/acd5f89b8addd2ff54f41a7d43ff9b122bb43337

Source-Link: https://github.com/googleapis/googleapis-gen/commit/8a12622536ae2e9a8978198a151e89234b839b20
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiOGExMjYyMjUzNmFlMmU5YTg5NzgxOThhMTUxZTg5MjM0YjgzOWIyMCJ9

* 🦉 Updates from OwlBot

See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md

* feat: KMS configuration in settings
chore: formatting changes

PiperOrigin-RevId: 430243637

Source-Link: https://github.com/googleapis/googleapis/commit/95da686e8840cf3edf872ce3d095967e24e41bf6

Source-Link: https://github.com/googleapis/googleapis-gen/commit/a1f056b7689ccbe5aebc0bfdd318e9945ee7602a
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiYTFmMDU2Yjc2ODljY2JlNWFlYmMwYmZkZDMxOGU5OTQ1ZWU3NjAyYSJ9

* 🦉 Updates from OwlBot post-processor

See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md

* 🦉 Updates from OwlBot post-processor

See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md

Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>
```

This is by virtue of how GitHub handles multiple commits in a PR.

If you manually cleanup the commit message when merging, so that it looks like this:

```
feat: Update Logging API with latest changes
PiperOrigin-RevId: 429289471
Source-Link: https://github.com/googleapis/googleapis/commit/acd5f89b8addd2ff54f41a7d43ff9b122bb43337
Source-Link: https://github.com/googleapis/googleapis-gen/commit/8a12622536ae2e9a8978198a151e89234b839b20
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiOGExMjYyMjUzNmFlMmU5YTg5NzgxOThhMTUxZTg5MjM0YjgzOWIyMCJ9
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
feat: KMS configuration in settings
chore: formatting changes
PiperOrigin-RevId: 430243637
Source-Link: https://github.com/googleapis/googleapis/commit/95da686e8840cf3edf872ce3d095967e24e41bf6
Source-Link: https://github.com/googleapis/googleapis-gen/commit/a1f056b7689ccbe5aebc0bfdd318e9945ee7602a
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiYTFmMDU2Yjc2ODljY2JlNWFlYmMwYmZkZDMxOGU5OTQ1ZWU3NjAyYSJ9
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>
```

Then it will be parsed appropriately.

The problem is the additional newlines GitHub adds, and the `* ` that prepends the commits.

**Comment by chingor13** [comment]
As @bcoe explains, this is behaving exactly according to spec. We intentionally do not parse the default squash/merge commit format because usually if you are squash merging, you do not want all the intermediate commit messages to appear in the changelog.

When you are manually merging a commit, the onus is on the maintainer to correctly format the commit message.

If you do err when merging, you can override the message using: https://github.com/googleapis/release-please#how-can-i-fix-release-notes
