### ISSUE TITLE
bug(owl-bot): reduce number of commits on new owlbot PRs from 4 to 2

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3225]
Recently I've noticed that new owlbot PRs have 4 commits instead of 2. Each commit takes a hit on our github quota for status checks so we should the number of commits back to 2. I have noticed more issues with kokoro quota recently and I think this may be related.

Recently new owl bot PRs have 4 commits:
https://github.com/googleapis/python-dataproc/pull/350/commits
![image](https://user-images.githubusercontent.com/5184014/155841369-38c28b82-7643-49cf-9913-25684229a295.png)

About 2 weeks ago, new owl bot PRs had only 2 commits:
https://github.com/googleapis/python-dataproc/pull/342/commits
![image](https://user-images.githubusercontent.com/5184014/155841302-91ce7546-a3b7-4e19-9336-9e7a2672958a.png)

**Comment by SurferJeffAtGoogle** [comment]
This issue will pass out of SLO in 2 days.

**Comment by bcoe** [comment]
Introduced a lock that I've seen working in production. Let me know if you continue to see any issues.
