### ISSUE TITLE
owl bot closed a pull request that it should not have closed

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3269]
https://github.com/googleapis/nodejs-bigquery-connection/pull/162

**Comment by bcoe** [comment]
@SurferJeffAtGoogle if I click on the history of that PR, at the time when OwlBot closed the issue, there were 0 code changes:

![Screenshot 2022-03-08 1 19 14 PM](https://user-images.githubusercontent.com/194609/157300860-774e4258-2992-4dea-9c58-14d245d656e2.png)

**Comment by SurferJeffAtGoogle** [comment]
> @SurferJeffAtGoogle if I click on the history of that PR, at the time when OwlBot closed the issue, there were 0 code changes:
> 
> ![Screenshot 2022-03-08 1 19 14 PM](https://user-images.githubusercontent.com/194609/157300860-774e4258-2992-4dea-9c58-14d245d656e2.png)

There were zero code changes for that commit, but there were still files open in the PR, because the earlier commits had code changes.
