### ISSUE TITLE
Release-please failing to tag releases due to duplicate tags

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3271]
Release-please is failing with the following error in the logs:

![Screenshot 2022-03-08 1 09 15 PM](https://user-images.githubusercontent.com/194609/157299609-ad6755b3-b8fb-4e2b-bbd3-13d8255491b6.png)

Appears to relate to this PR:

https://github.com/googleapis/google-api-nodejs-client/pull/2897

**Comment by bcoe** [comment]
The last release of `google-api-nodejs-client` bumped into a similar issue:

* it didn't finish tagging every API.
* it never triggered the publication kokoro job.

**Comment by bcoe** [comment]
(_bumped down to P2, since this seems to only be causing issues for our apiary repo._)

**Comment by chingor13** [comment]
This should have been fixed in https://github.com/googleapis/release-please/releases/tag/v13.16.4
