### ISSUE TITLE
[owlbot]: release-conductor repository causing errors in logs

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3282]
👇 

![Screenshot 2022-03-10 11 43 57 AM](https://user-images.githubusercontent.com/194609/157712299-967dce08-617b-4d01-9b9b-60db5c23b50c.png)

**Comment by SurferJeffAtGoogle** [comment]
I think this is happening in the `app.on('pull_request.closed'` handler here:
https://github.com/googleapis/repo-automation-bots/blob/4cf80852e3e9f66789331362a65de10558868c59/packages/owl-bot/src/owl-bot.ts#L252

It's attempting to clone the repo, but the repo is private, so it needs a token.  The `context` provided to `app.on` contains an octokit, but I see no way to obtain a token.  @bcoe How can I get a token?

**Comment by SurferJeffAtGoogle** [comment]
Downgrading to P3 because although there's an error in the log, I don't intend to run Owl Bot on this repo nor or in the foreseeable future.

**Comment by bcoe** [comment]
@SurferJeffAtGoogle there's a `privateKey` available in the context of the service, which can be used to fetch a token. the GitHub API attached to the context itself hides the token.

**Comment by SurferJeffAtGoogle** [comment]
I archived https://github.com/googleapis/release-conductor.  Maybe we'll unarchive it in a few months.
