### ISSUE TITLE
Owl Bot's Copy-Tags can be engineered away

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3300]
In a pull request like https://github.com/googleapis/google-cloud-dotnet/pull/8257, Owl Bot lists two Copy-Tags.

When a new C# generator is released and updates hundreds of APIs, the pull request will contain hundreds of Copy-Tags; they'll dominate the body of the PR, and that's annoying.

Copy-Tags originally served two purposes:

**1. Record that a pull request was generated.**

When Owl Bot sees a new commit in googleapis/googleapis-gen, it must consider, "Have I already created pull requests for all the `.OwlBot.yaml` files that copy files changed in this commit?"  Copy-Tag encodes the source commit hash and path to `.OwlBot.yaml`, so Owl Bot searched through pull requests for a matching Copy-Tag.  When it found none, it created a new pull request.

After https://github.com/googleapis/repo-automation-bots/pull/3154 was merged, Copy-Tags are no longer used for this purpose.

**2. Tell Owl Bot which `.OwlBot.yaml`s to consult when deciding which files to copy when *regenerating* a PR.**

When someone clicks the  `Regenerate this pull request now`, Owl Bot reads the content of `.OwlBot.yaml`s to know which files to copy.  The Copy-Tags tell Owl Bot which `.OwlBot.yaml`s to read.  There is another way to gather which `.OwlBot.yaml`s to read by rerunning the logic that originally created the pull request.

**Comment by SurferJeffAtGoogle** [comment]
cc @jskeet @amanda-tarafa @dazuma

**Comment by jskeet** [comment]
FYI, while I definitely support getting rid of them, I'm not hugely bothered by them either - so if they hang around for a while, it's not going to be a problem (even for the occasional PR with hundreds).

**Comment by suztomo** [comment]
You can also use collapsed sections to hide the hundreds of them by default.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

**Comment by SurferJeffAtGoogle** [comment]
Thanks @suztomo.  I'll give that a try.

> You can also use collapsed sections to hide the hundreds of them by default.
> 
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

**Comment by SurferJeffAtGoogle** [comment]
I need to beware of a pathological case:

1. Owl Bot creates PR 123 for a change to the KMS API.
2. A new Ruby microgenerator is released, which affects the generated code for all the APIs.
3. Owl Bot pushes a new commit to PR 123 with the changes from the new microgenerator.
4. User clicks the `Regenerate me` checkbox.

Without Copy-Tags or something like them, Owl Bot must observe which `.OwlBot.yaml`s were affected by the change in step 1, yet copy code from the latest commit hash in step 3.  It's tricky logic to get right.  I'll try collapsing sections as recommended by @suztomo first.

**Comment by SurferJeffAtGoogle** [comment]
Probably never gonna fix it.
