### ISSUE TITLE
Convert bots to use cloud run front-end

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3313]
See #2114

- [x] auto-approve
- [x] auto-label
- [x] bazel-bot
- [x] blunderbuss
- [x] canary-bot
- [x] cherry-pick-bot
- [x] conventional-commit-lint
- [x] do-not-merge
- [x] failurechecker
- [x] flakybot
- [x] generated-files-bot
- [x] header-checker-lint
- [x] merge-on-green
- [x] label-sync
- [x] owl-bot
- [x] policy
- [x] release-please
- [x] release-trigger
- [x] repo-metadata-lint
- [x] secret-rotator
- [x] snippet-bot
- [x] sync-repo-settings
- [x] trusted-contribution

**Comment by tmatsuo** [comment]
Initially I thought it's better to have a shared frontend server. I think we can just deploy a dedicated frontend server for all the bots.

**Comment by tmatsuo** [comment]
Deployed Cloud Run frontend for all the bots 🎉
