### ISSUE TITLE
Owlbot multiple commit descriptions can miss release notes

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#3342]
This commit https://github.com/googleapis/nodejs-spanner/commit/d1a9d7c3da7c378b433dcdab459b0c46279a4fb2 has "fix: annotating some fields as REQUIRED" in the description. Apparently this commit has multiple "PiperOrigin-RevId:" associated with it and the first entry is "chore: update v2.14.1 gapic-generator-typescript".

<img width="758" alt="Screen Shot 2022-03-23 at 1 00 22 PM" src="https://user-images.githubusercontent.com/28604/159754943-8045e8a0-ce93-457a-bde2-46d0344e1536.png">

The commit was released as part of [v5.17.0](https://github.com/googleapis/nodejs-spanner/releases/tag/v5.17.0)

<img width="529" alt="Screen Shot 2022-03-23 at 1 01 00 PM" src="https://user-images.githubusercontent.com/28604/159754986-e84af8c4-14d3-45db-b3b8-558d42047249.png">

However, the v5.17.0 release note https://github.com/googleapis/nodejs-spanner/releases/tag/v5.17.0 does not have the entry "fix: annotating some fields as REQUIRED".

<img width="700" alt="Screen Shot 2022-03-23 at 1 03 39 PM" src="https://user-images.githubusercontent.com/28604/159755499-9c47adce-9d93-4352-8991-37b4c3e18b05.png">

Would you troubleshoot and fix the problem?

CC: @bcoe

**Comment by SurferJeffAtGoogle** [comment]
@chingor13  It looks like Owl Bot is behaving exactly as I expect it to, and Release Please is behaving exactly as you expect it to, but the net result is something @suztomo does not expect  :-).  We should chat.  I'll book a meeting.

**Comment by SurferJeffAtGoogle** [comment]
@chingor13  will define a separator or some other signal to release please to continue scanning the pull request text, and I'll implement it in Owl Bot once it's defined.

@chingor13 Please assign back to me after the separator is defined.

**Comment by SurferJeffAtGoogle** [comment]
@suztomo Jeff proposed https://github.com/googleapis/release-please/pull/1566 but I found the BEGIN/END markers to be quite intrusive.  What do you think?

**Comment by suztomo** [comment]
The markers do not interfere my job. So I'm ok with the design.

My also feel it's intrusive. But my preference or feeling is not important. The most important is whether the marker design works with other automation.

**Comment by SurferJeffAtGoogle** [comment]
We're working on it...

**Comment by suztomo** [comment]
Thank you!
