### ISSUE TITLE
merge on green: merge commits creating links to other PRs

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/repo-automation-bots#3343]
It appears that when MOG creates a merge commit for a PR, it copies the text verbatim. If the original PR has links to another issue or PR, it creates a reference to that original PR. This generates a ton of noise for these other projects. 

An example of this is in this PR: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/778, which copied the release notes for reactor-core and linked to each PR in the release. 

Here is a comment about a maintainer asking us to stop: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/778#issuecomment-1080410623

And here's the issue on renovate that they've opened: https://github.com/renovatebot/renovate/issues/14804

The solution to this might be to just not put the PR body into the commit context (or maybe there is some kind of fancy sanitation that can be done by switching `github.com` urls to `togithub.com` urls to avoid the automatic deferences.

**Comment by sofisl** [comment]
Hope it's ok if we downgrade this to P2, but I will get working on it probably in the next few weeks, since it's not actively breaking anything and is only affecting a narrow audience.
