### ISSUE TITLE
release-trigger front-end still running out of memory

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3352]
2022-03-29 around 11am, Java made a bunch of releases. release-trigger front-end ran out of memory and crashed.

From the logs:
```
Memory limit of 953M exceeded with 966M used. Consider increasing the memory limit, see https://cloud.google.com/run/docs/configuring/memory-limits
```

```
"The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#timeout-503
While handling this request, the container instance was found to be using too much memory and was terminated. This is likely to cause a new container instance to be used for the next request to this revision. If you see this message frequently, you may have a memory leak in your code or may need more memory. Consider creating a new revision with more memory."
```

The memory graph does not appear to have a memory leak:

![AVdYgnUEvdpN7aF](https://user-images.githubusercontent.com/32483/160929196-b263c55c-bdfe-480b-a6be-4d7aa74209b1.png)

**Comment by chingor13** [comment]
This frontend Cloud Run service is using the same release-trigger image which is bigger (has the python runtime installed), but should never handle workloads which would call out to python.

**Comment by tmatsuo** [comment]
what was the concurrency?

**Comment by chingor13** [comment]
> what was the concurrency?

The release-trigger frontend is using the default concurrency (so maybe 80?)
