### ISSUE TITLE
bug(owl-bot): Owl bot failed to open PRs after python generator update. HTTP 401

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3416]
I noticed that owl-bot only created [16 PRs](https://github.com/search?q=org%3Agoogleapis+is%3Apr+author%3Aapp%2Fgcf-owl-bot+is%3Aunmerged+language%3Apython+is%3Aopen) for python after I updated the python generator version to 0.65.0. See the commit in googleapis-gen [here](https://github.com/googleapis/googleapis-gen/commit/b0c628a3fade768f225d76992791ea1ba2a881be). I was expecting to see ~100 PRs after this change.

I see `GaxiosError: Request failed with status code 401` in the cloud build logs for trigger 	
`owlbot-scan-googleapis-gen-and-create-pull-requests`. Under the response message it says `message: "'Expiration time' claim ('exp') is too far in the future",` 

I'm marking this as P1 as it is part of the pipeline for receiving changes from API producers.

**Comment by tmatsuo** [comment]
The next invocation is going well so far.

**Comment by tmatsuo** [comment]
The `exp` parameter is calculated at:

https://github.com/googleapis/repo-automation-bots/blob/a517dd9dd76faf85c3ba69639a416f5fa70c183a/packages/owl-bot/src/core.ts#L306

My guess is the clocks were out of sync between Github and Google side.

After obtaining the token, it seems like getting refreshed every 5 minutes:
https://github.com/googleapis/repo-automation-bots/blob/a517dd9dd76faf85c3ba69639a416f5fa70c183a/packages/owl-bot/src/octokit-util.ts#L87

So reducing the initial expiration duration to something like 8 minutes might prevent it from happening again (unless the clocks become out of sync more than 2 minutes).

**Comment by tmatsuo** [comment]
Downgrading to P2
