### ISSUE TITLE
release-please: google-api-nodejs-client monorepo fails to tag releases

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3428]
Release please is exiting with a critical error when running for `google-api-nodejs-client`, the error logs indicate:

```
HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

Logs can be looked up using identifier `zjmi0izngu9p`.

**Comment by chingor13** [comment]
This should have been fixed in #1433
