### ISSUE TITLE
Have a validator for region tag characters

### ISSUE THREAD

**Issue by ckim328** [googleapis/repo-automation-bots#3475]
**Is your feature request related to a problem? Please describe.**
Recently region tagged with a script that grabs info from a yaml file and its hiearchy. I didn't get a warning for when I initially merged my PR that a region tag was incorrectly formatted, and in fact snippet bot recognized it as a valid region tag (https://github.com/GoogleCloudPlatform/anthos-config-management-samples/pull/42)
 **Describe the solution you'd like**
I really like snippet-bot, it would be great to have the bot also validate against incorrect characters so that region tags only contain letters, numbers, underscores, and ~hyphens~. Hopefully this could be a small clean and could prevent others in the future for merging a PR with incorrect region tags
 **Describe alternatives you've considered**
n/a
 **Additional context**
![Screen Shot 2022-04-21 at 5 14 18 PM](https://user-images.githubusercontent.com/35876108/164553372-276a955d-a7fc-486b-ae77-0d2194303808.png)

**Comment by tmatsuo** [comment]
Can a hyphen be in region tags? I found an internal doc about Code Snippet 101 and region tags need to meet the following criteria:

- Contains only underscores and lowercase letters
- Globally unique - no other code snippet should have the same region tag
- Valid product prefix

**Comment by ckim328** [comment]
I don't think hyphens can be added to region tags (I'll open a bug and request info to confirm)

**Comment by ckim328** [comment]
Awesome!!! thanks so much @tmatsuo!!  💯 🤩
