### ISSUE TITLE
bug(owl-bot): PRs were not opened in downstream repos for a given commit in googleapis-gen

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3507]
I noticed that owlbot PRs weren't opened in downstream python repos for this recent commit in googleapis-gen: https://github.com/googleapis/googleapis-gen/commit/16eb36095c294e712c74a1bf23550817b42174e5

See this link for [open](https://github.com/search?q=org%3Agoogleapis+is%3Apr+author%3Aapp%2Fgcf-owl-bot+is%3Aunmerged+language%3Apython+is%3Aopen) python owlbot PRs.

**Comment by chingor13** [comment]
Bumping the timeout and improving the performance of the code scan appears to have fixed this.
