### ISSUE TITLE
Flakybot: build onboarding experience

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#355]
**Is your feature request related to a problem? Please describe.**
When you send a PR to enable the Build Cop Bot, it's a little scary. You have to enable it on nightly tests, but those don't run for pull requests. Maybe you run your system tests on the pull request branch, but then you may have issues filed when you don't want them to be, yet.

 **Describe the solution you'd like**
The bot could detect when it's being run against a PR, then comment on that PR with what the results were, rather than filing actual issues.

The Kokoro environment variables are slightly different for nightly/continuous tests and PRs. In particular, PRs don't have the `KOKORO_GITHUB_COMMIT_URL` env var, they have `KOKORO_GITHUB_PULL_REQUEST_URL`. We need to use that to get the repo. There is also `KOKORO_GITHUB_PULL_REQUEST_NUMBER`, which we could use to get the PR number (rather than extracting it from the URL).

I haven't checked the env vars for when system tests are run against a PR. There might not be a good solution for that.

 **Describe alternatives you've considered**
We could use the PR detection to decide whether or not to file issues at all. That way, people wouldn't need a Bash `if` statement to check that nightly tests are being run. But, this sounds brittle and like it would cause more problems than the current explicit setup that takes a couple extra lines of code.

**Comment by tbpg** [comment]
Maybe we could add a `-dry-run` flag to the binary? Not sure the best way to get the PR number and decide to comment on it in that case.

**Comment by tmatsuo** [comment]
How about to add an additional reporting mode? Let's say `onboard`, `aggregated`, `lite`, or whatever.
It works like usual, but it only creates one single issue with the summary.
WDYT?

**Comment by tbpg** [comment]
This hasn't come up much recently, so I'm not inclined to build something for it right now. Once we build it, it's harder to undo or go in a different direction. None of the solutions feel "right" yet.

**Comment by tmatsuo** [comment]
I think when someone is trying to start using flakybot, it's rather easy to implement "small start" strategy. For example, you can enable on one repo, or only report issues for one subdirectory, etc.

Let me close this, but feel free to reopen.
