### ISSUE TITLE
[snippet-bot] Tag format checker doesn't allow capital letters used by snippet-gen

### ISSUE THREAD

**Issue by dazuma** [googleapis/repo-automation-bots#3599]
snippet-gen (automated snippet generation for gapic clients) specifies a region tag format that can include capital letters. (See internal document go/snippet-gen-design and search for the "Region tag format" section.) Currently snippet-bot is flagging these as a bad tag format because its regex disallows capital letters.

/cc @amanda-tarafa

**Comment by tmatsuo** [comment]
Oops let's allow capital letters.

**Comment by amanda-tarafa** [comment]
Yep, we had https://github.com/googleapis/google-cloud-dotnet/pull/8444 being flagged this morning.
We are ignoring the error for now.
