### ISSUE TITLE
bug(auto-approve): auto approve bot didn't add the automerge label

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#3602]
In PR https://github.com/googleapis/python-apigee-connect/pull/111, auto-approve bot approved the PR but did not add the `automerge: exact` label.  The label was added successfully in https://github.com/googleapis/python-access-approval/pull/198.

**Comment by sofisl** [comment]
I think this is a weird problem where product label and yoshi-approver were racing to add labels. I will see if I can add some kind of retry.

**Comment by sofisl** [comment]
This issue is going to cause flakiness, so what I will attempt to solve it by adding a [`lock`](https://github.com/googleapis/repo-automation-bots/tree/main/packages/datastore-lock). I won't be able to get to it next week due to being OOO.

**Comment by tmatsuo** [comment]
I noticed that auto-approve doesn't have Cloud Run frontend. I recommend we run a dedicated frontend.

**Comment by chingor13** [comment]
From the logs, this was some kind of permission error:

```
data: {
  documentation_url: "https://docs.github.com/rest/reference/issues#add-labels-to-an-issue"
  message: "Must have admin rights to Repository."
}
status: 403
```

**Comment by sofisl** [comment]
I retested this with the exact same permissions, I don't think this is a permissions error, it [worked fine](https://github.com/googleapis/python-apigee-connect/pull/112) in repro.

I still believe this is probably a race condition occurring. I will fix using datastore lock.
