### ISSUE TITLE
OwlBot: handle DatastoreLockError

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3648]
We use a lock around the post processor for a given PR/SHA. If we fail to acquire the lock, datastore-utils is throwing a `DatastoreLockError`. We should handle this case rather than letting it error out.

Example:

```
DatastoreLockError: The lock for googleapis_nodejs-eventarc_73c4a518242e29cc8968979345164b80af0a7674 was acquired by another process.
```

**Comment by tmatsuo** [comment]
I think we can just return 200.

**Comment by chingor13** [comment]
I'm not sure how this is not being handled: https://github.com/googleapis/repo-automation-bots/blob/91fedb2ebf68f5af8dd758a644a89a5b59aacb03/packages/owl-bot/src/owl-bot.ts#L71-L81

The `DatastoreLockError` is being thrown from like 73.

It look like it should catch the error, and log at a warning level

**Comment by tmatsuo** [comment]
Is it when acquiring or releasing?

**Comment by tmatsuo** [comment]
I think it still throws DatastoreLockError when acquiring the lock.

**Comment by tmatsuo** [comment]
Actually, when it's throwing DatastoreLockError when acquiring the lock, the request should be retried.
So I think the current behavior is alright.
