### ISSUE TITLE
Several bots experiencing "HttpError: API rate limit exceeded for installation ID xxxxxx".

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3719]
I think this issue is normally fixed automatically thanks to Cloud Task, but we'd better handle this somehow in a long run.

**Comment by chingor13** [comment]
Related: #3773

**Comment by tmatsuo** [comment]
I implemented flow control for scheduler jobs. I think we should control the flow for Github webhook requests too.

**Comment by tmatsuo** [comment]
It turned out you can set rate limit on Cloud Task queues.

The default values are:

```
$ gcloud tasks queues describe snippet-bot
name: projects/repo-automation-bots/locations/us-central1/queues/snippet-bot
rateLimits:
  maxBurstSize: 100
  maxConcurrentDispatches: 2048
  maxDispatchesPerSecond: 500.0
retryConfig:
  maxAttempts: 100
  maxBackoff: 3600s
  maxDoublings: 16
  maxRetryDuration: 43200s
  minBackoff: 5s
state: RUNNING
```

**Comment by tmatsuo** [comment]
flakybot is tricky because the pubsub handler is directly sending the request to Cloud Function. I think we should migrate flakybot to Cloud Run.

**Comment by tmatsuo** [comment]
Filed #4424
