### ISSUE TITLE
release-please: "Error: Failed to validate the config schema at '.github/release-please.yml'"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3720]
> Error: Failed to validate the config schema at '.github/release-please.yml' :[ { "instancePath": "", "schemaPath": "#/additionalProperties", "keyword": "additionalProperties", "params": { "additionalProperty": "releaseLable" }, "message": "must NOT have additional properties" } ]
at .getConfig ( /workspace/node_modules/@google-automations/bot-config-utils/build/src/bot-config-utils.js:229 )
at .runMicrotasks

**Comment by chingor13** [comment]
This should have been fixed in #3667
