### ISSUE TITLE
Cloud Logging sink configuration error

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3721]
Cloud Logging sink configuration error in repo-automation-bots, sink github_triggered_logs: table_invalid_schema (This field: event is not a record.)

**Comment by chingor13** [comment]
I believe we are logging a list of lists of strings which is not supported by BigQuery in a logging sink.

**Comment by tmatsuo** [comment]
`repo-automation-bots.github_bot_logs.cloudfunctions_googleapis_com_cloud_functions` table's `event` field is a `string` field. I tried to change it to `record`, but it doesn't seem it's possible.

**Comment by tmatsuo** [comment]
It's somewhat intended. The failed logs are stored in a different table.
