### ISSUE TITLE
Release-please is opening PRs for the wrong version #

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#3730]
https://github.com/googleapis/nodejs-security-center/pull/488
https://github.com/googleapis/jsdoc-fresh/pull/109
https://github.com/googleapis/nodejs-datastore-kvstore/pull/318
https://github.com/googleapis/nodejs-media-translation/pull/227 --> should be a major bump

**Comment by dwsupplee** [comment]
We are seeing the same in PHP as well:

https://github.com/googleapis/google-cloud-php/pull/5280

Of interesting note, the PR was generated with the correct data yesterday (umbrella package version v0.181.0), but after a recent merge (https://github.com/googleapis/google-cloud-php/pull/5279) the PR was regenerated with an incorrect version number (v1.0.0). It appears some of the sub-packages are being reverted as well: https://github.com/googleapis/google-cloud-php/pull/5280/files#diff-a330c9108635ce55bad0b74d2cc2b2b85cca4facef419b64f67d2fe28e27893aR1

Release notes seem to be catching some oddities, too:
<img width="832" alt="Screen Shot 2022-05-18 at 11 10 53 AM" src="https://user-images.githubusercontent.com/2079879/169114945-ac64b53c-8d37-4304-bfb4-8072c56ac108.png">
