### ISSUE TITLE
Blunderbuss only on-demand, not by default

### ISSUE THREAD

**Issue by muncus** [googleapis/repo-automation-bots#3732]
**Is your feature request related to a problem? Please describe.**
Occasionally, I need a review from a member of a team, but I do not have a strong preference, and I'd like to let blunderbuss to assign to a random member of the team.

 **Describe the solution you'd like**
I'd like to be able to use a label or an assignee to get Blunderbuss to assign a PR. I'd like this to *only* happen when specifically triggered, not to all PRs by default.

**Describe alternatives you've considered**
Right now, I manually pick a team member. This leads to less-than-random choices. 😄

**Comment by tmatsuo** [comment]
One easy workaround is to add an assignee when creating a PR. Then blunderbuss doesn't mess with it.

**Comment by tmatsuo** [comment]
Technically we can implement a configuration option for `ondemand` mode, but I don't think it's worth spending our time because there is a very easy workaround of assigning someone when creating a PR.

Let us close this, but feel free to reopen if you think differently.
