### ISSUE TITLE
Conventional Commit Linter: Always lint PR Titles

### ISSUE THREAD

**Issue by grayside** [googleapis/repo-automation-bots#3733]
**Is your feature request related to a problem? Please describe.**

The current linter implementation scans commit messages for single-commit branches, and PR titles for multi-commit branches.

If someone makes a quick change without following the conventional commit standard, they cannot easily fix it via the GitHub UI. Instead, they need to go back to their development environment and amend the commit or add a spurious commit to sidestep the linter.

This friction especially impacts new contributors unfamiliar with conventional commits, folks trying to help with a quick change via the GitHub UI, or developers still building muscle memory on using conventional commit forms.

 **Describe the solution you'd like**

Change the default behavior or add a configuration option to always and only scan the PR title.

This makes the contribution experience easier, at the cost that the maintainer will need to be more thoughtful about checking the commit message before merging.

 **Describe alternatives you've considered**

Disable conventional commit linting.

**Comment by bcoe** [comment]
will make an effort to make this tweak this week.

**Comment by bcoe** [comment]
Update: did not have time to work on this today, but Monday should be relatively free.

**Comment by tmatsuo** [comment]
> (big feature) bot to amend commit message to match PR title

Implementation:

- add an event listener for `pull_request.edited`
- if there's one single commit and the first line of commit message is different from the PR title, add a comment including a checkbox for changing the commit message
- if that checkbox got checked, change the commit message and force push to the head branch

Introducing a new config means additional manual step for human beings. Even if it takes a longer time to implement, we should aim for more automation.

Just my 2 cents

**Comment by bcoe** [comment]
@grayside having brought this up with the Automation Team, it sounds like the fix is less straightforward than I was thinking initially.

Has this problem been continuing to bother your team, perhaps using an existing action is worth a shot if it unblocks you.

**Comment by tmatsuo** [comment]
Today I came up with a cheap solution for reducing friction.

When the bot detects the commit message and the PR title defer, it adds a comment saying "we detect that the commit message is different from the PR title. if you want to use the PR title, use Github's automerge feature with squashing, or use `automerge` label".

**Comment by tmatsuo** [comment]
Here is the comment from the ccl bot:
https://github.com/googleapis/repo-automation-bots/pull/3947#issuecomment-1155816426

I'm going to add `automerge` to that PR. Let's see how it goes.

**Comment by tmatsuo** [comment]
Yes, just after I added `automerge` label, the ccl bot submit a successful check :)

**Comment by tmatsuo** [comment]
@grayside 
Let me close this, but feel free to reopen.
