### ISSUE TITLE
Trigger Google Cloud Build builds with trusted-contributor-gcf

### ISSUE THREAD

**Issue by coryan** [googleapis/repo-automation-bots#3769]
**Is your feature request related to a problem? Please describe.**

The Cloud C++ team uses Google Cloud Build for most of its CI builds. When renovatebot sends us PRs the builds to do not automatically start.  For example https://github.com/GoogleCloudPlatform/cpp-samples/pull/199 

 **Describe the solution you'd like**

Just like `trusted-contributor-gcf` creates a `kokoro:force-run` label, it would be nice if it also inserted a `/gcbrun` comment.

 **Describe alternatives you've considered**

A configuration option to describe what actions to take would be really good, we have some repos with both Kokoro and GCB builds.

 **Additional context**

https://cloud.google.com/build/docs/automating-builds/build-repos-from-github#creating_github_triggers

**Comment by chingor13** [comment]
We already have this feature via configuring different annotation types.

Here's an exact example from this repository: https://github.com/googleapis/repo-automation-bots/blob/86032b3388391655f24b75038c764dc1556384d7/.github/trusted-contribution.yml#L2-L3
