### ISSUE TITLE
flakybot: dying with rate limit error

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3773]
Error message:
```
HttpError: API rate limit exceeded for installation ID 6370238
```

Some form of flow control is needed, I guess.

**Comment by chingor13** [comment]
Our retry mechanism (built-in Cloud Tasks retries) looks at the `X-CloudTasks-TaskRetryCount` header and stops if retries (by returning a 200) once it's hit a max retry count threshold.

We might be able to apply a bit of back pressure by globally handling rate limit errors and returning a 503: https://cloud.google.com/tasks/docs/common-pitfalls#backoff_errors_and_enforced_rates

**Comment by tmatsuo** [comment]
That's really a nice idea, I think

**Comment by SurferJeffAtGoogle** [comment]
Flakybot burns through more quota than any other bot.  I suggest we re-implement it as a Github Action.

**Comment by chingor13** [comment]
> re-implement it as a Github Action.

flakybot mostly handles pubsub requests which are coming from integration/sample tests on Kokoro.
