### ISSUE TITLE
Merge on Green: Handle PRs with dismissed reviews

### ISSUE THREAD

**Issue by crwilcox** [googleapis/repo-automation-bots#378]
It seems to me that PRs that have dimissed reviews aren't merging ever.
Example: https://github.com/googleapis/python-storage/pull/48

tseaver leaves request for changes
crwilcox dismisses
crwilcox approves
franknatividad approves.

Is it possible the request for changes is blocking despite the dismissal of the review?

**Comment by sofisl** [comment]
Hi Chris! From what I can tell, it looks like Ilya left comments and did not approve that PR. According to the logic, if anyone has reviewed and not approved, then it would not get merged. Do you have an example of a PR that has been approved and still has not merged? I'd imagine that's more on the order of a bug, in which case I'd be happy to review!

**Comment by sofisl** [comment]
As a heads up, I merged PR #390 which fixes a bug with reviewers: it will allow the PR to merge if the author has left comments. Maybe this was affecting the PR?

**Comment by sofisl** [comment]
Will close this due to inactivity, as I'm pretty sure this issue has been resolved! @crwilcox, feel free to reopen if you see this issue persist :)
