### ISSUE TITLE
canary-bot-global scheduled task has been failing failing for past 7 days

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3811]
![image](https://user-images.githubusercontent.com/11778530/171236597-d20dbb90-143e-481f-bcb6-4c5a4a633e42.png)

**Comment by chingor13** [comment]
I broke this testing #3786 with a bad JSON payload. This is now fixed manually and a subsequent cron deploy would fix it anyways.
