### ISSUE TITLE
Bot errors appear to be grouped incorrectly in Cloud Error Reporting

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3819]
We get grouped errors like:

![9cfyjZocRLK75JY](https://user-images.githubusercontent.com/32483/171689985-4cffff0e-2e0f-4f67-992e-589216944345.png)

But when you click through on the error group, you see other error types included.

![7H4vfvJifoPoPQb](https://user-images.githubusercontent.com/32483/171690879-8759091e-d2b6-461a-9441-6819fb648572.png)

My hunch is that Error Reporting is confused because these errors are actually `AggregateError` types from probot. The `jsonPayload` for there errors actually looks like:

![BHFSRqRg6yjcx4Q](https://user-images.githubusercontent.com/32483/171691506-82be4d5b-7633-4a20-8cce-80bd9ef25079.png)

and:

![55uv6CzkhfkjdKz](https://user-images.githubusercontent.com/32483/171691738-13f2ea58-0b29-4874-b69b-7756d0159b2c.png)

Both have the same `name` and first line of the `stack`.

**Comment by SurferJeffAtGoogle** [comment]
I imagine it's grouping based purely on the line where the exception was thrown.

**Comment by chingor13** [comment]
> line where the exception was thrown

That could be the case. The problem is that the framework is throwing this `AggregateError` from the same place. We actually care about the wrapped error's stack trace.

An option: if the `AggregateError` only contains a single error, rethrow that single error.

Note: probot uses an `AggregateError` because you can have multiple `app.on('some-event-name', handler)` handler functions. Probot will run all of them and will wrap any thrown errors from the handlers with an `AggregateError` (there could be one from each handler). In most of our bots, we only write a single handler function per event.
