### ISSUE TITLE
Merge on Green: handle cases where the branch protection doesn't quite match the statuses

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#383]
Example:

https://github.com/googleapis/google-api-php-client/pull/1796

MOG won't merge here because the branch protection is continuous-integration/travis-ci, and the status checks are continuous-integration/travis-ci/pr and continuous-integration/travis-ci/push

**Comment by bshaffer** [comment]
The convention for branch checks is either `[check-name]` or `[check-name]/[subcheck-name]`. Would it be possible to update the bot so that the protected branch checks will match for either of these?

**Comment by bshaffer** [comment]
Let me clarify my above comment. If a branch protection check matches either `[check]` or all `[check]/*`, then Merge on Green can merge.
