### ISSUE TITLE
Product label not being added for python-automl

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#388]
Looking at this issue here:
https://github.com/googleapis/python-automl/issues/17

I would expect the `api: automl` label to be automatically applied.  I double checked and the `product-auto-label` bot is enabled for the entire org.  This is causing SLO attribution problems.

**Comment by busunkim96** [comment]
In an older issue https://github.com/googleapis/python-automl/issues/2 the bot applied the `api: automl` label.

**Comment by bcoe** [comment]
this has been addressed 👍
