### ISSUE TITLE
Snippet bot not checking for already added branch(commit SHA) when removing region tags

### ISSUE THREAD

**Issue by vishwarajanand** [googleapis/repo-automation-bots#4025]
While working for PR: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1653, Snippet bot always throws a failure even when a `branch` is added and published to via devsite.

> Your change is now published at:
> https://cloud.google.com/storage/docs/streaming.

Upon checking [this code pointer](https://github.com/googleapis/repo-automation-bots/blob/33bcaea59e9b37d01d1fd3004a8094bc1b2a3256/packages/snippet-bot/src/violations.ts#L121-L130), it seems that removing a region tag will give a snippet bot failure no matter what process we follow.

Relevant Links: 
[cl/456603604](http://cl/456603604)
[b/191780034](http://b/191780034)

**Comment by tmatsuo** [comment]
The bot should ignore frozen (pinned to a commit hash) region tags. I'll investigate.

**Comment by tmatsuo** [comment]
BTW, there is a delay between publishing to devsite and snippet-bot starts to realize the change, up to a few hours.

I think this might be just a propagation delay.

**Comment by vishwarajanand** [comment]
Okay, thanks for looking into it @tmatsuo. 
I think I waited for a day, so propagation issues should not have been there. The time when I submitted the CL to add branch name was `Thu, Jun 23, 2022, 2:34 AM GMT+5` and the time for checking the GitHub PR was `23 Jun 2022, 20:33 GMT+5:30` which is ~18 hours. So, we can safely discard the publishing delay if `<1 day`

**Comment by vishwarajanand** [comment]
Yes, I did force run the snippet bot after publishing the branch tag, like below screenshot. Now that the PR is merged, i guess we can't retry that anymore?
<img width="986" alt="Screenshot 2022-07-02 at 11 02 35" src="https://user-images.githubusercontent.com/7369612/176987961-420edbad-34eb-42c1-90b1-a6ab57ae3375.png">


**Note:** I have also removed the branch tag, [cl/456801158](http://cl/456801158)

**Comment by tmatsuo** [comment]
Oops sorry, that "Re-run" link is not implemented.
Please use the checkbox in the snippet-bot comment, or add `snippet-bot:force-run` label.

**Comment by vishwarajanand** [comment]
Got it.. I will close this issue now.
