### ISSUE TITLE
Rebasing the master branch makes release-please bot confused

### ISSUE THREAD

**Issue by stastnypremysl** [googleapis/repo-automation-bots#4040]
I have basically the same problem as described here: https://github.com/googleapis/release-please/issues/713

Shortly said `git rebase -i HEAD~N` for rewording old enough commit and `git push -f` means, that Release Please bot starts malfunctioning and it is hard to get it back working without direct `bootstrap-sha` and Initial Version support.

I suggest, that `bootstrap-sha` and Initial Version to be added as a configuration parameter in `.github/release-please.yml` so it is not so hard to get release-please bot working after rebasing.

**Comment by chingor13** [comment]
Are you using a manifest (`release-please-config.json`)? Release-Please should be able to find the previous releases - it looks through commit history for a release PR, then falls back to finding the release tag specified in the manifest versions file. If it is not finding the right release version/tag, please open a new issue on the googleapis/release-please repo with more information so we can try to reproduce.

That said, we **highly** recommend not rewriting commits in your main/master branch. If you are using pull requests for all of your changes (also **highly** recommended and the one we use for Google open source), you can override the commit message that release-please uses: https://github.com/googleapis/release-please#how-can-i-fix-release-notes
