### ISSUE TITLE
Errors logged to structured logging not creating Error Reporting entries

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4061]
When we were logging `AggregateError`s in `gcf-utils` using `logger.error(errorObject)`, Cloud Error Reporting was finding these messages and creating entries in Error Reporting. We are no longer seeing new entries even though we see structured logging messages in the console (with ERROR severity).

Context: commit switching logging: https://github.com/googleapis/repo-automation-bots/commit/3266d1149fd05cdddeecb45d3f75f3cc9896e7ee

**Comment by chingor13** [comment]
I was looking into directly using the error-reporting API to report these errors, but I could not find a straightforward, manual client.

**Comment by chingor13** [comment]
Collecting information about the runtime is non-trivial. The resource information is an important part of the error reporting API.

**Comment by tmatsuo** [comment]
We deployed the error handler code (#4438) to all the bots, closing
