### ISSUE TITLE
[snippet-bot] What does "Some region tags do not have appropriate prefix" mean?

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#4093]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do

I'm trying to figure out the meaning of this error message.

> Some region tags do not have appropriate prefix
> There are 15 possible violations for not having product prefix.
> [java-network-security/samples/snippets/generated/com/google/cloud/networksecurity/v1beta1/networksecurityclient/create/SyncCreateSetCredentialsProvider1.java:19](https://github.com/googleapis/google-cloud-java/blob/74ef64b4c891caa24256dbb124e7b7cce8e07ebc/java-network-security/samples/snippets/generated/com/google/cloud/networksecurity/v1beta1/networksecurityclient/create/SyncCreateSetCredentialsProvider1.java#L19), tag networksecurity_v1beta1_generated_networksecurityclient_create_setcredentialsprovider1_sync

This is the pull request that failed the error https://github.com/googleapis/java-network-security/pull/183

- What code you've already tried

- Any error messages you're getting

The error above.

I created this issue to track my investigation of the error message. If somebody know the background, then I appreciate the input.

**Comment by suztomo** [comment]
@blunderbuss-gcf Assign this to me.

**Comment by suztomo** [comment]
It seems the violations come from the code around here https://github.com/googleapis/repo-automation-bots/blob/10fed5567bbceebba452ab8ddbc76107e5ab396e/packages/snippet-bot/src/violations.ts#L216

**Comment by chingor13** [comment]
The available product prefixes come from DRIFT's product database. It a convention/design used so we can associate the samples with a product. Without the prefixes, we get snippets floating around that are never included on our documentation pages.

**Comment by chingor13** [comment]
`networksecurity` does appear to be in DRIFT's database (product 501)

**Comment by tmatsuo** [comment]
That product is marked as "not" public. That's why the drift database doesn't have the region tag prefix `networksecurity`.

Please make the product public. After a while the bot will be happy. Use the "Update this comment" checkbox in the bot's comment for re-running the bot.

**Comment by chingor13** [comment]
The product is now updated to be public and will take a bit of time to roll out.
