### ISSUE TITLE
Snippet bot does not recognize 'quickstart' snippet tags

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#4123]
Snippet bot doesn't recognize 'quickstart' tags, see: https://github.com/googleapis/google-cloud-node/pull/3246

However, those tags are required for owlbot post-processor to put those samples into the README, see: https://github.com/googleapis/synthtool/blob/2adfcf9bed59bd2a9236f4790a0db7837aae45bf/synthtool/languages/node_mono_repo.py#L92

Adding an `ignore` label wouldn't be sufficient, since this will happen with every new API.

**Comment by chingor13** [comment]
I think we determined that the quickstarts still need to have a snippet product prefix
