### ISSUE TITLE
Configurable Default Branch Check for Policy Bot

### ISSUE THREAD

**Issue by iennae** [googleapis/repo-automation-bots#4170]
**Is your feature request related to a problem? Please describe.**

I want to be able to run Policy Bot on the cloud-code-samples repo, but it has a problem with Default branch not being main. I understand that the idea here is to remove master as the default branch, but this causes problems when the product is leveraging branching as a feature to ensure backwards compatibility and future proofing.

ex. https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/845

 **Describe the solution you'd like**

I'd like to be able to either configure the default repo or choose to ignore the check for the default repo name. 

 **Describe alternatives you've considered**

Disabling the bot? Seems problematic. 

 **Additional context**

https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/845#issuecomment-1095566603

**Comment by chingor13** [comment]
After more consideration, this seem to be counter to standard git usage. `v1` is a very weird branch name, but it is much more suitable for a git tag. Both are considered git references and supported by git (so you can fetch a repo at a tag). It is extremely common to keep a major version tag pointing to the latest released version of a repository.
