### ISSUE TITLE
[owlbot]: delete old database entries when .OwlBot.yaml deleted

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#4188]
OwlBot detects `.OwlBot.yaml` files in repositories, creating a database entry which is used to distribute code changes.

When a `.OwlBot.yaml` configuration file is deleted from a repository, we should remove this database entry.

**Comment by SurferJeffAtGoogle** [comment]
Actually, the current code removes the database entry.  There is one firestore document per repository, and that document is replaced daily when the repository is re-examined.  So, when an .OwlBot.yaml is deleted, the doc is replaced with a doc without a corresponding record of the .OwlBot.yaml.

Relevant code is here:
https://github.com/googleapis/repo-automation-bots/blob/7cb794cd449ba36660982b1cc68e520368813968/packages/owl-bot/src/handlers.ts#L281-L300
