### ISSUE TITLE
[BUG] Cherry-pick bot opens PR for unmerged base PRs

### ISSUE THREAD

**Issue by eddycharly** [googleapis/repo-automation-bots#4239]
In the cherry-pick bot docs:

> On Unmerged Pull Request
If you add/edit the comment on an unmerged pull request, it will not do anything immediately

From what I observe, a cherry-pick PR is opened even when the base PR is not merged yet.

**Comment by chingor13** [comment]
Repro: https://github.com/chingor13/release-please-test/pull/20#issuecomment-1230517368

Opened: https://github.com/chingor13/release-please-test/pull/21

**Comment by chingor13** [comment]
Interesting -- it looks like unmerged pull requests now include a `merge_commit_sha` value. I don't remember this happening previously as we were using the existence of that value as an indicator of merge status.

**Comment by eddycharly** [comment]
Sorry, I don't know what/when this changed. I hope it can be fixed though.

By the way, is there a way we can control the PR title ?
