### ISSUE TITLE
Merge-on-green: maintain a merge queue to reduce number of tests run

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4285]
When there are many pull requests pending merge on green and when the repository has "require up-to-date branches" enabled, there's a race for which pull request is merged first. All of the other pending branches are then updated from main and they race again to complete CI and potentially merge next. So if there are N approved and pending automerge PRs, we will run the CI suite `N * (N - 1) / 2` times (sum of 1 up to N).

**Comment by chingor13** [comment]
Example scenario: when we have our weekly dependency update script run, we get 20+ automergeable pull requests. We would like to be able to approve each one once and enable automerge on all of them. Instead, I approve each one, then apply the automerge label in batches (babysitting the process) which is what we're trying to avoid with automerge.

**Comment by tmatsuo** [comment]
Maybe it's easier to implement a new bot with Github's Automerge feature ...

**Comment by chingor13** [comment]
Yeah, talking with @SurferJeffAtGoogle, it may be worth waiting for GitHub's built-in merge queue + automerge when it leaves limited public preview.

**Comment by tmatsuo** [comment]
Github's built-in merge queue doesn't take care of updating PRs when I tested

**Comment by tmatsuo** [comment]
Ah actually I haven't tested Github's built-in merge queue ...

**Comment by tmatsuo** [comment]
Do you still need this?
