### ISSUE TITLE
Merge on Green: Bot commented twice after 3 hours

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#433]
Merge on Green `automerge` label commented twice with the same comment at the same time:

https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1044#issuecomment-608091697

Also, strangely enough, the comment is different than the one that commented 3 hours later... so maybe there's an old version running somewhere?

**Comment by sofisl** [comment]
I think this should be solved by PR #475. Please let me know if you run into it again!
