### ISSUE TITLE
Surfacing bot logs to the repo owners

### ISSUE THREAD

**Issue by simonz130** [googleapis/repo-automation-bots#434]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
When having multiple bots enabled on a repo, sometimes the behavior of the bot differ from what is expected. In order to understand why, it would be useful to look at the bot logs (only the logs that are associated with the activity of the bot on a given repo).

 **Describe the solution you'd like**
Upon configuring the bot, I'd like to specify where to send the logs that the bot generates as a result of processing activities on my repo. This could be a storage bucket or pub/sub topic or something else where I have access. Every time the bot emits a log as a result of activity on my repo, I want it to also send the log wherever I specified.

 **Describe alternatives you've considered**
Pinging bot owner to understand why the behavior doesn't match my expectations

 **Additional context**
-

**Comment by tmatsuo** [comment]
This is a very cool idea, but practically, it is way easier for us to create a log sink to a GCS bucket or BigQuery or whatever, then allow googlers access to that log.

**Comment by tmatsuo** [comment]
I believe all the cloud dpes have logs viewer access now. Let me close this, but feel free to reopen.
