### ISSUE TITLE
Owlbot is not copying over some parts of googleapis-gen

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#4351]
When running owlbot locally on [nodejs-workflows](https://github.com/googleapis/nodejs-workflows), I expect to see these [generated samples](https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/workflows/v1/workflows-v1-nodejs/samples/generated/v1). However, they do not appear in the owlbot-staging directory (which also confirms it is not a problem with the post processor). This agrees with the fact that these samples were never proposed by owlbot (none of [these ](https://github.com/googleapis/nodejs-workflows/pulls?q=is%3Apr+is%3Aclosed+samples) contain the generated samples).

Steps to reproduce:

1. Clone nodejs-workflows locally (`git clone git@github.com:googleapis/nodejs-workflows.git`)
2. Clone googleapis-gen using `git clone git@github.com:googleapis/googleapis-gen.git /tmp/googleapis-gen`
3. Then run: 
```
docker run --rm --user $(id -u):$(id -g) \
 -v $(pwd):/repo -v /tmp/googleapis-gen:/googleapis-gen -w /repo \
 --env HOME=/tmp \
 gcr.io/cloud-devrel-public-resources/owlbot-cli:latest copy-code \
 --source-repo=/googleapis-gen
``` 
in nodejs-workflows
5. Check the owlbot-staging directory, it will not contain generated samples

**Comment by SurferJeffAtGoogle** [comment]
The existing [deep-copy-regex parameters](https://github.com/googleapis/nodejs-workflows/blob/ce8fb0f19788a4d7e95a3cdcc41432a7307e2275/.github/.OwlBot.yaml#L20) didn't list the samples directory to be copied.

Here's an example that copies the samples directory.
https://github.com/googleapis/nodejs-workflows/compare/fix4351?expand=1

Here's an example that copies everything.  It's much simpler, but it probably copies a lot of files you don't want.
https://github.com/googleapis/nodejs-workflows/compare/fix4352?expand=1

**Comment by sofisl** [comment]
That makes sense, thank you for investigating. I will update accordingly!
