### ISSUE TITLE
[cherry-pick]: does not work when comments are added on unmerged pull requests

### ISSUE THREAD

**Issue by eddycharly** [googleapis/repo-automation-bots#4364]
From the docs:

> ## On Unmerged Pull Request
> If you add/edit the comment on an unmerged pull request, it will not do anything immediately. When the pull request is merged, cherry-pick-bot will scan all the comments on the pull request, collect valid target branches to cherry-pick to, and then attempt to cherry-pick each one.

This does not seem to work, when the PR merges it doesn't trigger a cherry-pick PR even if there's a comment for it.

**Comment by eddycharly** [comment]
Do we have access to the logs of the bot ?

**Comment by eddycharly** [comment]
cc @tmatsuo

**Comment by chingor13** [comment]
> Do we have access to the logs of the bot ?

We do, but unfortunately, we cannot make them public at this time. I am looking into this today.

**Comment by chingor13** [comment]
Also, I would double-check your permissions on the repo - we try to ensure that you are allowed to make changes to the repo by checking the authorized user's permissions on the repo: https://github.com/googleapis/repo-automation-bots/blob/main/packages/cherry-pick-bot/src/bot.ts#L30-L34

**Comment by eddycharly** [comment]
@chingor13 I checked the permissions, they are ok.

Look at this one https://github.com/kyverno/kyverno/pull/4596 :
First realshuting commented before the PR was merged but it didn't trigger a cherry pick PR. Then prateek commented after the PR was merged and it worked correctly this time.

**Comment by chingor13** [comment]
@eddycharly Thanks, I found the issue from this repro - it's trying to iterate over the comments and the first comment is not a cherry-pick comment and it's returning rather than continuing: https://github.com/googleapis/repo-automation-bots/blob/bba97031e2b7004ccc79fb025ecfbf9474ec818a/packages/cherry-pick-bot/src/bot.ts#L206

**Comment by eddycharly** [comment]
Ah yes, good catch !
I think, I read this code 10 times without spotting the mistake :rofl:
