### ISSUE TITLE
[owlbot]: changes mirrored from synthtool include reference to issue # in originating repository

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#4365]
When someone merges a change into synthool with the default GitHub format, which includes the PR # at the end of the commit message:

<img width="1329" alt="Screen Shot 2022-09-08 at 1 09 12 PM" src="https://user-images.githubusercontent.com/194609/189184156-a1b48078-78cf-4807-a049-c012c223ab9b.png">

☝️ this issue # is mirrored upstream by OwlBot (in this case `#1553`).

Because this issue # refers to the synthtool repo, and not the repository that changes are mirrored to, this creates dead links when a CHANGELOG entry is created for the mirrored change:

You can find an example of these dead links [here](https://github.com/googleapis/nodejs-bigtable/releases/tag/v4.0.2).

## Potential fix

During the mirroring process, if we see the commit message ends with `\(#[0-9]+\)`, we could drop this trailing value.

**Comment by SurferJeffAtGoogle** [comment]
Fixed by https://github.com/googleapis/synthtool/pull/1580
