### ISSUE TITLE
sync-repo-settings not adding admin language teams

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#438]
This method here:
https://github.com/googleapis/repo-automation-bots/blob/master/packages/sync-repo-settings/src/sync-repo-settings.ts#L149

Should have updated https://github.com/googleapis/gax-java/ to make sure the `yoshi-java-admins` team had admin access.  I had to add it manually :(  It looks like something isn't working quite right.  

cc @chingor13

**Comment by bcoe** [comment]
sync-repo-settings wasn't turned on yet, due to a bug in which is wasn't respecting ignored repos.

This has been fixed by @sofisl [here](https://github.com/googleapis/repo-automation-bots/pull/439) and the bot will be running tonight 👌
