### ISSUE TITLE
Owlbot is validating test fixtures

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4381]
It appears owlbot is opening issues for badly formatted owlbot YAML configs :+1: . However, we have some template/test fixtures that should be ignored by OwlBot. Example: https://github.com/googleapis/synthtool/issues/1576

We can fix the format, but we don't actually want owlbot to run on that test subdirectory.

Perhaps we could add a way to ignore certain directories?

**Comment by SurferJeffAtGoogle** [comment]
@chingor13 What do you think of leaving a comment in [tests/fixtures/nodejs_mono_repo_with_staging/packages/gapic-node-templating/.OwlBot.yaml is broken. #1576](https://github.com/googleapis/synthtool/issues/1576), downgrading it to P4, and closing this issue?  If there's another repo with a template .OwlBot.yaml that fails like this, we can re-open the issue.

**Comment by chingor13** [comment]
Commented on that issue. We will reopen if this continues to be an issue with more repositories.
