### ISSUE TITLE
repo-metadata-lint doesn't have secrets in secret manager

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4409]
The bot has a webhook handler for pull_request and because there's no secrets, the bot is throwing 400 errors for those webhook requests, but well, funny enough, the handler only emits a log and exit, so it's ok for now.

**Comment by chingor13** [comment]
We do have a secret named `repo_metadata_lint`

**Comment by chingor13** [comment]
We had a webhook secret in our secrets, but the bot was not configured to use it. They secrets now match and requests look like they are processing.
