### ISSUE TITLE
bug(snippet-bot): snippet-bot dies when failed to download the PR diff

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4442]
Example PR: https://github.com/googleapis/google-cloud-java/pull/8435

Even the Github web UI cannot show the diff.

**Comment by suztomo** [comment]
FYI, that pull request is trying to compare two branches that have history diverged.

**Comment by tmatsuo** [comment]
Thanks! It helps. I don't think we should prioritize this error.
