### ISSUE TITLE
[cherry-pick-bot] comment on PR if cherry-pick fails

### ISSUE THREAD

**Issue by eddycharly** [googleapis/repo-automation-bots#4507]
We are using the `cherry-pick-bot`.

It works great, except on one PR (https://github.com/kyverno/kyverno/pull/4608), it didn't open the corresponding cherry-pick PR an we have no idea why.

Any reason why this can happen ? A conflict maybe ?

**Comment by eddycharly** [comment]
Also, could the bot post a comment to the PR thread if something wrong happens ?
If so I can take some time to contribute such a feature.

**Comment by eddycharly** [comment]
Looks like a conflict issue, I could reproduce locally.

**Comment by chingor13** [comment]
Related error report: #4501

We could probably have the bot catch this case and comment on the issue.

**Comment by eddycharly** [comment]
Thanks for confirming, shall I give it a try ?

**Comment by eddycharly** [comment]
@chingor13 shall I open a PR to make the bot comment on the issue ?
