### ISSUE TITLE
Owlbot PR not being created for gke-connect-gateway repos

### ISSUE THREAD

**Issue by lqiu96** [googleapis/repo-automation-bots#4547]
Copying information from internal chat:

Cloud Java team is not seeing an owlbot PR being created for the recent protobuf version upgrade: https://github.com/googleapis/java-gke-connect-gateway/pulls?q=is%3Apr+label%3Aowl-bot-copy+is%3Aclosed+sort%3Aupdated-desc. We were expecting something similar to this pull request: "chore(bazel): update protobuf to v3.21.7".  Java-AccessApproval for example: https://github.com/googleapis/java-accessapproval/pull/849

From: https://dashboards.corp.google.com/view/_3be71818_e474_47a0_9450_7f14515dff9e?f=cl:in:477955264 -- I don't see that it created one for the gke-connect-gateway repository

The underlying commit (https://github.com/googleapis/googleapis-gen/commit/4abcbcaec855e74a0b22a4988cf9e0eb61a83094) does touch files like google/cloud/gkeconnect/gateway/v1beta1/google-cloud-gkeconnect-gateway-v1beta1-java/grpc-google-cloud-gkeconnect-gateway-v1beta1-java/src/main/java/com/google/cloud/gkeconnect/gateway/v1beta1/GatewayServiceGrpc.java

Could someone take a look and see why Owlbot wasn't able to create the PR?

**Comment by suztomo** [comment]
https://screenshot.googleplex.com/446eaQtk5Lixdah.png (visible internally)

**Comment by tmatsuo** [comment]
Looking at the directory in `googleapis-gen`

https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/gkeconnect/gateway/v1beta1/google-cloud-gkeconnect-gateway-v1beta1-java

It says the last commit was 29 days ago.

Somehow bazel rule is broken now? I'll try to look at bazel log around that time.

**Comment by tmatsuo** [comment]
I checked the files locally with googleapis-gen by

```
$ git show --name-only 4abcbcaec855e74a0b22a4988cf9e0eb61a83094 > 4abcbcaec855e74a0b22a4988cf9e0eb61a83094-commit.txt
```

Only file modified in this commit under gkeconnect is:

google/cloud/gkeconnect/gateway/v1beta1/google.golang.org/genproto/googleapis/cloud/gkeconnect/gateway/v1beta1/gateway.pb.go

**Comment by tmatsuo** [comment]
Then the question is:

Why we don't we have the file generated by bazel bot?

**Comment by tmatsuo** [comment]
Here is the summary.

The commit in googleapis:
https://github.com/googleapis/googleapis/commit/a724450af76d0001f23602684c49cd6a4b3a5654

The corresponding commit in googleapis-gen:
https://github.com/googleapis/googleapis-gen/commit/4abcbcaec855e74a0b22a4988cf9e0eb61a83094

There are no files were updated under https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/gkeconnect/gateway/v1beta1
for java

Actually, no other languages got updates. Only the go file was updated:
https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/gkeconnect/gateway/v1beta1/google.golang.org/genproto/googleapis/cloud/gkeconnect/gateway/v1beta1

**Comment by suztomo** [comment]
```
~/googleapis-gen $ git show --name-status 4abcbcaec855e74a0b22a4988cf9e0eb61a83094 |grep gkeconnect
M	google/cloud/gkeconnect/gateway/v1beta1/google.golang.org/genproto/googleapis/cloud/gkeconnect/gateway/v1beta1/gateway.pb.go
```

The last owl-bot-copy pull request in java-gke-connect-gateway: https://github.com/googleapis/java-gke-connect-gateway/pull/206/files "chore(bazel): Update WORKSPACE files for rules_gapic, gax_java, generator_java versions" on Sep 7th. This doesn't have many files.

Maybe the proto file is so simple that the protoc version change (3.21.3 -> 3.21.7) did not affect any of the code. 

https://github.com/googleapis/java-gke-connect-gateway/tree/main/proto-google-cloud-gke-connect-gateway-v1beta1/src/main/java/com/google/cloud/gkeconnect/gateway/v1beta1

**Comment by tmatsuo** [comment]
Sounds like that's the case! Thanks for the update, closing
