### ISSUE TITLE
bug(owlbot-bootstrapper): owlbot bootstrapper fails to clone repo

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#4576]
#### Steps to reproduce

  1. Run `bootstrapper run-trigger pre-process   --apiId="google.cloud.datastream.v1"   --language="nodejs" `
  2. The build fails with `"Error: spawnSync /bin/sh ENOENT"`. See build log [here](https://pantheon.corp.google.com/cloud-build/builds;region=global/cf3dce16-9e4c-4347-a9ff-015e15cf6521;step=0?project=owlbot-bootstrap-prod). `git clone` appears to be failing

See the issue that was opened on `google-cloud-node` [here](https://github.com/googleapis/google-cloud-node/issues/3435).

**Comment by SurferJeffAtGoogle** [comment]
The issue is that the x-access-token is missing.  It looks like it's usually provided by automation.  I'm not sure how it's supposed to be provided via the command line.  Let's wait for @sofisl to return from vacation.

**Comment by parthea** [comment]
@bcoe helped me to resolve this issue. I had an old installation of owlbot bootstrapper cli.
