### ISSUE TITLE
Secret Rotator: Request to force rotate new secret cloud-java-ci-it-service-account

### ISSUE THREAD

**Issue by burkedavison** [googleapis/repo-automation-bots#4595]
I'm following internal documentation titled "Using the Secret Rotator Service".

I am a Googler without permissions to view `secret-rotator-prod`. This morning I added the `cloud-java-ci-it-service-account` cron job, and am looking for it to be run so it can populate the new secret.

Thank you!

**Comment by chingor13** [comment]
I force ran that rotate job. I was under the impression that our terraform configs supported granularly adding permissions to a team/user that could force trigger that rotator job (it was part of the design IIRC). We'll have to update the terraform configs to grant permissions to teams.

**Comment by burkedavison** [comment]
Thank you!

**Comment by sofisl** [comment]
I don't think we can granularly assign permissions to cron jobs. @burkedavison, can you send me an alias for a group that will need permissions to force rotate the secret?

**Comment by sofisl** [comment]
Addressed in cl/486005339
