### ISSUE TITLE
fix(mono-repo-publish): Refactor `rmSync` Usage

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/repo-automation-bots#4634]
`@google-cloud/mono-repo-publish` is using `rmSync`, which isn't available until Node 14: https://nodejs.org/api/fs.html#fsrmsyncpath-options

This is causing [googleapis/google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client/) to quietly fail to publish packages for some time:
- https://github.com/googleapis/google-api-nodejs-client/issues/3095
- Relevant log: https://fusion2.corp.google.com/invocations/ce800de6-6e12-4286-905c-a8fafc253718/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Frelease%2Fgoogleapis%2Fgoogle-api-nodejs-client%2Fpublish/log

And therefore, a number of packages, such as [`@googleapis/youtube`](https://github.com/googleapis/google-api-nodejs-client/tree/main/src/apis/youtube), hasn't been published [in several months](https://www.npmjs.com/package/@googleapis/youtube).

**Recommendation**: `@google-cloud/mono-repo-publish` can use `unlinkSync` (and related) instead: https://nodejs.org/api/fs.html#fsunlinksyncpath

**Comment by chingor13** [comment]
@sofisl is looking to the release issues (downgrading to rmSync is a possible solution)

**Comment by sofisl** [comment]
I think these packages have been published now: https://fusion2.corp.google.com/invocations/2b858743-8a3b-474c-bcc3-0795038f51be/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Frelease%2Fgoogleapis%2Fgoogle-api-nodejs-client%2Fpublish/log 

(There's an issue with a camelcase repo)

@bcoe, I heard that you tried to fix this publication. Did you fix the rmSync problem permanently, or was it a force-publish?

**Comment by sofisl** [comment]
I think this has been fixed as of now.
