### ISSUE TITLE
[Owl Bot bootstrapper] Can bootstrapper avoid creating a new issue if there's existing one?

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#4648]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

I'm always frustrated when Owl Bot bootstrapper creates an GitHub issue for my experiment.

<img width="587" alt="Screen Shot 2022-11-02 at 8 49 21 AM" src="https://user-images.githubusercontent.com/28604/199493847-0c6531d3-68c5-457b-a349-32d500f2cc10.png">

 **Describe the solution you'd like**

Owl Bot bootstrapper should not create an issue if there's existing one for the same API. In that case, a new comment would be enough to know there's a failure.

 **Describe alternatives you've considered**

Suppressing issue creation completely when I pass a flag.

 **Additional context**

The command I ran:

```
suztomo@suztomo:~/repo-automation-bots$ C=1ee4f0eed30c; bootstrapper run-trigger pre-process \
  --apiId=apikeys \
  --language=java \
  --languageContainer=$C \
  --repoToClone=[git@github.com](mailto:git@github.com):googleapis/google-cloud-java.git
```

**Comment by chingor13** [comment]
An alternative is to use `@google-automations/issue-utils` which provides an [`addOrUpdateIssue` helper](https://github.com/googleapis/repo-automation-bots/blob/6daf0d7c9b178dd4542cd297c1026cf472e90fb2/packages/issue-utils/src/issue-utils.ts#L98)
