### ISSUE TITLE
.OwlBot.lock.yaml not receiving automated PRs to update digest in PHP MonoRepo

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/repo-automation-bots#4670]
When a new post processor image is published, it would be very helpful to have the [OwlBot lock file](https://github.com/googleapis/google-cloud-php/blob/main/.github/.OwlBot.lock.yaml) update automatically. Currently this behavior seems to not exist or perhaps is broken (https://github.com/googleapis/google-cloud-php/pull/5068#issue-1116816127).

**Comment by chingor13** [comment]
Upodate: the subscription exists already. Digging into why we're not getting updates

**Comment by SurferJeffAtGoogle** [comment]
This is working as intended.

Originally, Owl Bot opened a new pull request for every new docker image, but maintainers complained that they were getting too many pull requests with no meaningful changes.  So we fixed Owl Bot to only open a pull request when the new docker image actually generates code that's different than the previous docker image.

The new post processor docker image also ran on the [manual PR that update the digest](https://github.com/googleapis/google-cloud-php/pull/5068#issue-1116816127), and the result was no changes to any other files in the repo.  The same thing happened when Owl Bot tried updating the docker image digest, so it decided not to open a new pull request.

If this is troublesome, please open a feature request for a flag in .OwlBot.yaml to control this behavior.
