### ISSUE TITLE
secret-rotator timeout without retry

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4698]
It looks like one of our secret rotator jobs failed with a timeout (trace=projects/secret-rotator-prod/traces/e405d31910521e2757dab3c701d39aac). There's no retry mechanism so that secret ended up expiring (key expires after 3 months, rotation set to every 2 months so a single failure would let the key expire).

- [x] we should be notified on these errors
- [x] we should have some kind of retry mechanism for these transient failures
- [x] we should extend the timeout - it was probably a service cold start
- [x] we could spread the cron jobs out so they do not all run immediately at midnight on the same day after 0 traffic for a month

**Comment by sofisl** [comment]
Fixed with cl/506436972
