### ISSUE TITLE
Octokit auth deprecation notice

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#473]
I'm seeing a lot of these warnings in the logs (for example, execution ID 1119117730021191). Can/should we do something about it?

```
{ Deprecation: [@octokit/rest] Setting the "new Octokit({ auth })" option to an object without also setting the "authStrategy" option is deprecated and will be removed in v17. See (https://octokit.github.io/rest.js/#authentication)
```

From the trace, it looks like it might be coming from Probot -- maybe we need an upgrade?

**Comment by sofisl** [comment]
I think this was solved with our upgrade to Probot 10.
