### ISSUE TITLE
FR(owl-bot): break up very large PRs that touch all APIs

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#4763]
Some PRs touch all APIs, see: https://github.com/googleapis/google-cloud-node/pull/3698

Ideally, this PR would be broken up at least partially by some APIs, which would produce two benefits:

1) It would make it easier to review and approve PRs as a human, 
2) It would likely cause less stress on tests and other automations, for example, the post-processor.

Other alternatives considered:

1) Submit PRs by individual APIs (this would cause too many PRs)
2) Make automation more durable (increase timeout, have each run take less time) -- > This can and should be done in parallel.

**Comment by SurferJeffAtGoogle** [comment]
@dazuma and @jskeet,

The Ruby and .NET repos also see massive PRs that touch 150+ APIs.  What if these massive PRs were broken into smaller PRs of roughly 20 APIs at a time?

**Comment by jskeet** [comment]
That would work for me, yes.

**Comment by sofisl** [comment]
@SurferJeffAtGoogle, I think the temporary solution suffers in the interim as well (extending the timeout for the post processor):

https://pantheon.corp.google.com/cloud-build/builds;region=global/099bfff2-0c10-488a-b1a5-3374715a9896?project=repo-automation-bots

I think the JWT expires by the time the post processor has finished running, so owlbot cannot commit the results of running the post processor.

**Comment by dazuma** [comment]
@SurferJeffAtGoogle Smaller sets are fine. I don't mind either way.

**Comment by SurferJeffAtGoogle** [comment]
Thanks everyone!  I'll implement it.
