### ISSUE TITLE
Include in the conventional-commit-lint message if PR and single commit message differ

### ISSUE THREAD

**Issue by apeabody** [googleapis/repo-automation-bots#4765]

**Comment by apeabody** [comment]
Hi @tmatsuo! - Based on recent feedback I'm thinking of a slightly different direction, here is our use case:

We want to include conventional-commit-lint as a mandatory check, but we only use merge commits with "Default to Pull Request Title" in our repos.  So we don't want the check failure on differing commit vis PR title, as long as the PR title is correct.  

To maintain existing behavior, one option would be a new parameter which when enabled the linter only validates the PR title, even for single commit PRs.  This would enable the check to "pass" as long as the PR title is valid, as that is what we use for the commit.

Let me know you thoughts.  Thanks!

**Comment by tmatsuo** [comment]
@apeabody 

You can enable automerge feature on the repo, then use automerge with squash. In that case, the bot knows Github will use PR title, so the check will succeed.

Is this not enough?

**Comment by tmatsuo** [comment]
Potential problem of only depending on the bot config is that, someone can still merge the PR with other method (merged commit, instead of squash), then your commit message will be the bad one.

**Comment by apeabody** [comment]
Hi @tmatsuo - That is a potential risk, although we disable merge commit on our repos.  Let me discuss with the team next week.

For context: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1304#issuecomment-1341636666

**Comment by tmatsuo** [comment]
If the config is opt-in, it might be fine though.
Sure, we will happily accept feature request and/or a PR for it.

**Comment by tmatsuo** [comment]
Actually I created #4769

**Comment by apeabody** [comment]
Closed in favor of https://github.com/googleapis/repo-automation-bots/issues/4769
