### ISSUE TITLE
feat(ccl): introduce a config for always check against PR title

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4769]
Github repository can be configured for only using squash commit and use the PR title for the final commit message. In this case, you may want to always check the PR title for conventional commit spec.

Related:
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1304#issuecomment-1341636666

cc @apeabody

**Comment by apeabody** [comment]
Thanks @tmatsuo!
