### ISSUE TITLE
gsuiteaddons-v1-nodejs: protos directory not updated

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/repo-automation-bots#4780]
In the most recent `googleapis`, run:

```
bazel build //google/cloud/gsuiteaddons/v1:gsuiteaddons-v1-nodejs
tar tfz bazel-bin/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs.tar.gz | grep protos/google/apps/script/type
```

The resulting tarball will have `gsuiteaddons-v1-nodejs/protos/google/apps/script/type/docs/docs_addon_manifest.proto`.

For some reason, it's not in the most recent https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs/protos/google/apps/script/type.

The proto files are produced for as long as 2 years (starting from [this commit](https://github.com/googleapis/googleapis/commit/5c0c233c33ecca53acb0b37111830b893bba70e2)), but even the corresponding [commit](https://github.com/googleapis/googleapis-gen/commit/33e247e02259906cdc97ea96947a8ff62e96635c) to `googleapis-gen` did not include the `docs/` directory. Maybe its gets filtered out for whatever reason?

**Comment by SurferJeffAtGoogle** [comment]
Debugging note #1:

[Github got it wrong](https://github.com/googleapis/googleapis-gen/commits/master/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs/protos/google/apps/script/type).  There was no change to the .../type directory in August.



```
rennie@rennie2:~/gitrepos/googleapis-gen/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs/protos/google/apps/script/type$ git log .
commit 54f6b94ed7259fd6299a017941e5fc65e6a162aa (tag: googleapis-d606bb4a7852604e4045948d6340e73cb0d1d70b)
Author: Bazel Bot <bazel-bot-development[bot]@users.noreply.github.com>
Date:   Thu May 20 20:33:47 2021 +0000

    fix: add outer classname for addon_widget_set proto for java
    
    Committer: @neenushaji
    PiperOrigin-RevId: 374926588
    
    Source-Link: https://github.com/googleapis/googleapis/commit/d606bb4a7852604e4045948d6340e73cb0d1d70b

commit 33e247e02259906cdc97ea96947a8ff62e96635c (tag: googleapis-5c0c233c33ecca53acb0b37111830b893bba70e2)
Author: Bazel Bot <bazel-bot-development[bot]@users.noreply.github.com>
Date:   Thu Mar 18 20:31:57 2021 +0000

    fix: pass all proto dependencies to Node.js build target
    
    Committer: @alexander-fenster
    PiperOrigin-RevId: 363729504
    
    Source-Link: https://github.com/googleapis/googleapis/commit/5c0c233c33ecca53acb0b37111830b893bba70e2
rennie@rennie2:~/gitrepos/googleapis-gen/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs/protos/google/apps/script/type$ 
```

**Comment by chingor13** [comment]
This is happening because the generator is creating a `.gitignore` file that includes `docs/`: https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/gsuiteaddons/v1/gsuiteaddons-v1-nodejs/.gitignore

This is causing the [`git add` command](https://github.com/googleapis/repo-automation-bots/blob/d7479c90c9e4156f8b8a4aae1ed8bc97f372dcff/packages/bazel-bot/docker-image/generate-googleapis-gen.sh#L134) to ignore those files.

**Comment by chingor13** [comment]
FWIW, even if bazel-bot put this into googleapis-gen, it likely would have been ignored in the end repo also because of the generated .gitignore file

**Comment by SurferJeffAtGoogle** [comment]
Thanks for investigating Jeff.  I'll close this bug now.
