### ISSUE TITLE
Flakybot: comments multiple times on the same issue at the same time

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#483]
If two builds finish at the same time, separate invocations of the Build Cop Bot can lead to two (or more) duplicate comments on an issue. Similarly, two invocations can try to close the issue at the same time.

There is some logic in place to only comment with one failure per commit. However, it doesn't handle this race condition.

We should consider some sort of distributed lock to make sure only one instance of the bot comments on it at a time.

For example, see https://github.com/googleapis/google-cloud-go/issues/1840#issuecomment-601197212 and https://github.com/googleapis/google-cloud-go/issues/1915 (different types of comments, same race condition).

P2 because while this is annoying, nothing is broken and requiring immediate attention.

**Comment by tmatsuo** [comment]
FWIW, I'm building a distributed lock backed by datastore at: https://github.com/googleapis/repo-automation-bots/pull/1732
Once it works for blunderbuss, we can factor it out to gcf-utils and use it from flakybot too.
