### ISSUE TITLE
Build Cop: don't change priority or type of issues

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#484]
If an issue already has `priority: pN` or `type: foo` labels, the bot should not add the `priority: p1` or `type: bug` labels. The bot should be helpful, not persnickety.

If there is no `priority` label, the bot should re-add `priority: p1` (for example, https://github.com/googleapis/google-cloud-go/issues/1840). If there is no `type`, it should add `type: bug`.

I don't think this requires an explanatory comment from the bot ("Looks like the `priority` label was removed, re-adding the default `priority: p1`.") But, I could be convinced.

Regardless of type, issues should always have a `priority` label.

cc @JustinBeckwith @meredithslota

**Comment by JustinBeckwith** [comment]
Thank you for your use of `persnickety`
