### ISSUE TITLE
Allow forward slash for branch name in cherry-pick-bot

### ISSUE THREAD

**Issue by PascalArevalo** [googleapis/repo-automation-bots#4851]
Greetings,

I noticed that the cherry-pick-bot does not work if the branch contain a forward slash in its name.
e.g. it doesn't work if you type `/cherry-pick release/1.2.x`

#### Steps to reproduce

  1. Install cherry-pick-bot
  2. type `/cherry-pick release/1.2.x`

Also, I found this (#3177) PR and I suppose a similar fix can be done for this issue, I can create the corresponding PR if you want.

Thanks for your time

**Comment by chingor13** [comment]
Thanks for this report! Yes, we would be willing to accept a PR to fix this.
