### ISSUE TITLE
Merge-on-green: logs errors when checking pages of statuses that do not exist

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#487]
MOG will leave the following error message when it checks a certain page of status checks or check runs that do not exist:

```Error in getting statuses: Cannot read property 'context' of undefined```

I believe this functionality is caused by the iterateGetStatusi and iterateGetCheckRuns functions, because they basically call 10 pages of these checks/statuses in a loop. Currently, this actually helps the bot function because it will exit out of the loop once it gets to a page that it cannot read and continue on with the rest of the function. However, should we consider a different implementation that doesn't rely on failure (or, should we just not log the failures?)

@bcoe and @tbpg, would love your thoughts on this!

**Comment by tbpg** [comment]
I think it would be better to not rely on the error triggering and stopping execution. If needed, we can check if `=== undefined` and return early.
