### ISSUE TITLE
pass PR user info to owlbot postprocessor container

### ISSUE THREAD

**Issue by codyoss** [googleapis/repo-automation-bots#4940]
**Is your feature request related to a problem? Please describe.**

It would be great if an owlbot postprocessor was shared the info of the person that created the PR -- or even just if it was from the owlbot user. There is certain logic in our Go post processor that should really only happen on owlbot PRs. For instance snippet generation in Go today is done via post-processing(moving in the future). It does not feel great is a change to a manual causes some changes in our snippets and owlbot commits some changes like this to the users PR. From the docs it seems like exposing or at least passing through this information was originally considered as a documented substitution in the readme is _PR_USER. But if you look in the code this was never plumbed through.

 **Describe the solution you'd like**

1. The code to pass through such a value. It is available in the `prData` already under `prData.user.login`
2. The update-pr.yaml would need to be updated to accept this value.
3. This value is passed to the postprocessor container as an environment variable that could be optionally checked against. 

 **Describe alternatives you've considered**

I am not sure, but I am open to suggestions.

**Comment by SurferJeffAtGoogle** [comment]
Owl bot invokes the post processor in the repo directory, so you can observe the commit history.  IIRC, you haven't asked Owl Bot to squash the post-processor commit into the original commit, so a couple shell commands can tell you the author of the first commit:

```sh
# What's the last commit that this branch and main had in common?
$ git merge-base HEAD main
3cc72e12cba20480a948a9ad3bfe973b84ff52e7
# What was the first commit in this branch to diverge from main?  Show me the author.
$ git rev-list 3cc72e12cba20480a948a9ad3bfe973b84ff52e7..HEAD -1 --format=%ae
commit 7ade9a5d25995794c81efa8a2f14f8bd140ac469
somebody@somewhere.com
```

**Comment by codyoss** [comment]
@SurferJeffAtGoogle I was actually going to do something like this yet today as a soft-workaround. I don't think it is a desired solution though because of the clone depth of the update-pr job. https://github.com/googleapis/repo-automation-bots/blob/5e60ab5043759ae9ae8ceb102ee56587f619b376/packages/owl-bot/cloud-build/update-pr.yaml#L52

**Comment by SurferJeffAtGoogle** [comment]
I see.  So, the laziest solution I see is to change that 2 to 100 or whatever number you like.

**Comment by codyoss** [comment]
That would be totally fine with me. I think we could even go lower than that. Maybe 20ish would be a good place to start that leaves a nice buffer?

**Comment by codyoss** [comment]
Actually more would need to be done with the clone operation after some initial testing. Because the clone is a branch at a depth the git history has no idea what main is in this case. Perhaps there is another flag to add to also pull branch refs or something
