### ISSUE TITLE
Post processor reports failure when it was actually a success 

### ISSUE THREAD

**Issue by codyoss** [googleapis/repo-automation-bots#4946]
I have an OwlBot PR that is reporting an "unkown build failure" but if I drill into the build everything passed. Have seen this a couple times now:

- PR: https://github.com/googleapis/google-cloud-go/pull/7290

From a side chat @chingor13 mentioned it might be related to handling of a lock.

**Comment by chingor13** [comment]
From the logs: `triggerPostProcessBuild: timed out waiting for build 51f32ea1-1593-435f-bd96-34bba4285316`

https://github.com/googleapis/repo-automation-bots/blob/424f3e348ff8f40953919a1f1750134b0800f007/packages/owl-bot/src/core.ts#L155-L157

**Comment by chingor13** [comment]
Looks like we wait ~20 minutes (20000ms * 60 attempts) for the post-processor to run. The GCB job has a higher timeout so it succeeds, but the request that is watching the state of the GCB job gives up.

**Comment by codyoss** [comment]
Got it, sounds good. We have an PR in the works to limit the amount of work done by the post processor for most change. This should in term reduce the time well under the 20 minute time it is today. Although I suspect the tail end build time to still be long when all client get touched right now. We have a seperate project underway that is moving snippet generation into the generator and out of the post processor. Once this is complete this should not be an issue at all.
