### ISSUE TITLE
scaffolding: our bot generation script has some bugs in the newest version of probot

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#495]
1. the logic for instantiating a mock probot app is slightly different:

```js
    probot = new Probot({});
    probot.app = {
      getSignedJsonWebToken() {
        return 'abc123';
      },
      getInstallationAccessToken(): Promise<string> {
        return Promise.resolve('abc123');
      },
    };
    probot.load(myProbotApp);
```

2. The dependencies have drifted a bit out of date, we're now explicit with the `@octokit/rest`, `probot`.
3. we aren't on the latest version of `gts`.
4. we don't include a `files` field in the package.json, so were triggering the `eslint-plugin-node/no-unpublished-import` linting rule.

see: https://github.com/googleapis/repo-automation-bots/pull/486

**Comment by sofisl** [comment]
Closing issue for now, please feel free to reopen if bots continue to have bugs!
