### ISSUE TITLE
Secret Rotator fails without notification

### ISSUE THREAD

**Issue by burkedavison** [googleapis/repo-automation-bots#4966]
The secret rotator's job scheduler failed in executing a rotation for google-cloud-java's service account, but we didn't know until the credentials stopped working. Manually running the job resolved our credentials issue.

There are several other jobs that have status 'Failed', and as @chingor13 mentioned in chat:
> It defeats the whole point if the rotation fails and we aren't proactively notified. Especially when it only runs like every other month

Please contact me in chat for any links or further details, if needed.

**Comment by chingor13** [comment]
Notes: from the logs I see `The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#abort-request` (example log insert id: 63b13d810003da0a088fbb00)

**Comment by sofisl** [comment]
Fixed with  cl/506436972
