### ISSUE TITLE
failure-checker should say which packages failed to publish

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#4977]
Failure checker tells me some releases may have failed, but not which: 
https://github.com/googleapis/google-cloud-node/issues/3975

I went through and manually confirmed which ones didn't release, but it would be great if the bot could say it in the description (specifically for monorepos).

**Comment by chingor13** [comment]
This is not really feasible. The bot does not have access to logs nor should it be able to parse them to determine what failed.

**Comment by sofisl** [comment]
How does failurechecker determine that something was not published?

**Comment by sofisl** [comment]
Ok, I think this is actually a broken-clock-is-right-twice-a-day bug. I've confirmed that all the packages in [this release](https://github.com/googleapis/google-cloud-node/pull/3898) have been published, and yet failurechecker keeps opening up a new bug. See latest here: https://github.com/googleapis/google-cloud-node/issues/3981 (but there are many open for the same release)

**Comment by sofisl** [comment]
Talked to Ben, seems like I need to remove the `autorelease: failed` label.
