### ISSUE TITLE
How do I get owlbot to ignore a template file?

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#4980]
https://github.com/googleapis/google-cloud-node/issues/3888

This file isn't a real .Owlbot.yaml file, but I cannot close the issue for good.

**Comment by SurferJeffAtGoogle** [comment]
No solution comes to mind.  @sofisl Have you thought about a solution?

**Comment by sofisl** [comment]
Can we add a specific excludes list? It's probably very small.
