### ISSUE TITLE
Policy bot not working as expected

### ISSUE THREAD

**Issue by jackwotherspoon** [googleapis/repo-automation-bots#4988]
We recently enabled Policy Bot on some of our team's repos and it doesn't seem to be working very well.

1) The bot keeps raising an issue on the Python Connector [#638](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/638) for not having branch protection enabled ... but the repo does have branch protection enabled from what i can tell. If I close the issue, the bot opens a new one the next day 😢 

2) The bot was configured on multiple of our repos a week ago but has not run yet on them. Is there a way to tell why this is happening? Two of the repos that have not seen any issues or PRs from policy bot yet are [cloud-sql-go-connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector) and the [cloud-sql-jdbc-socket-factory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory)

Please let me know if there are ways to fix the two issues mentioned. Is the policy bot is actively maintained and recommended to be used?

Any info would be greatly appreciated, thanks so much :)

**Comment by chingor13** [comment]
It looks like the bot is looking for the "Require review from Code Owners" setting to be enabled as well: https://github.com/googleapis/repo-automation-bots/blob/main/packages/policy/src/policy.ts#L240-L243

In some orgs, an expansive group of people have write access to repos, so CODEOWNERS limits approval to a select group.

**Comment by jackwotherspoon** [comment]
Thanks for the quick response @chingor13! 

Any clue why policy bot hasn't created issues/PRs on some of the repos that have the bot configured on them? Do I need to grant specific permissions or write access to certain accounts?

**Comment by chingor13** [comment]
From the bot logs, I see that it's running against those repos, but there was no data in BQ for them. Then I found: https://github.com/googleapis/repo-automation-bots/blob/main/packages/policy/src/bot.ts#L60-L62 which only includes repos if there are repository topics of `samples` or `libraries` :shrug: . Not entirely sure why that is there, but if you add one of those topics to the repo, then you should see it working.
