### ISSUE TITLE
owlbot does not create PRs when post-processor is updated

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#5024]
1. Change was committed to synthtool:  https://github.com/googleapis/synthtool/pull/1782
2. New docker image was created: https://screenshot.googleplex.com/4h9tMsdmTDZGkBi, https://pantheon.corp.google.com/gcr/images/cloud-devrel-public-resources/global/owlbot-nodejs-mono-repo?jsmode=O&mods=allow_workbench_image_override&project=cloud-devrel-public-resources
3. No new PRs for this docker image were sent to google-cloud-node.

**Comment by sofisl** [comment]
Recently, the Node team has submitted more changes to synthtool. 

See PR: https://github.com/googleapis/synthtool/pull/1795

And ensuing new container: https://pantheon.corp.google.com/cloud-build/builds;region=global/12cfdaa0-c848-439b-81a1-d0b98b3da4f4;step=1?jsmode=O&mods=allow_workbench_image_override&project=repo-automation-bots

It runs, and says the post-processor did not create any changes: https://pantheon.corp.google.com/cloud-build/builds;region=global/4cfd1660-19ba-428c-98b6-28ffaaf032ef;step=11?jsmode=O&mods=allow_workbench_image_override&project=repo-automation-bots

However, there definitely are changes to be made to the current code, with tests to confirm it. I've also tried running the post-processor locally. I didn't run it all the way through, since it takes too long, but I ran it for a few packages and I see the changes in the links get proposed (ignore changes from `main` --> `master`, that is just a missing env variable):

https://github.com/googleapis/google-cloud-node/pull/4242

See for example this change:


```
# [Google Analytics Data: Node.js Client](https://github.com/googleapis/google-cloud-node) 
--> 
# [Google Analytics Data: Node.js Client](https://github.com/googleapis/google-cloud-node/tree/main/packages/google-analytics-data)
```

**Comment by SurferJeffAtGoogle** [comment]
Step 9 in the [cloud build log](https://pantheon.corp.google.com/cloud-build/builds;region=global/4cfd1660-19ba-428c-98b6-28ffaaf032ef;step=9?jsmode=O&mods=allow_workbench_image_override&project=repo-automation-bots) ran the docker image:
```
Already have image (with digest): gcr.io/cloud-devrel-public-resources/owlbot-nodejs-mono-repo:latest@sha256:1eb185b0427bb3d87cb6b2ea968ed33c812b3669bbf3b763593a9f39ca59eb31
+ RELATIVE_DIRS=
+ python -m synthtool.languages.node_mono_repo
```
It took 2 seconds to complete, which is very suspicious.
![image](https://github.com/googleapis/repo-automation-bots/assets/11778530/325f2c36-a611-435e-bbc5-365f9bbb076e)

**Comment by SurferJeffAtGoogle** [comment]
I find no possible explanation for the docker image taking only 2 seconds and doing nothing.  I ran the docker image manually and it hasn't finished running yet.  It's busy compiling protos and reformatting code.

My unsatisfying and unlikely conclusion is that this was a glitch in Cloud Build, the first I've seen.

It's too late to click the Rebuild button:
![image](https://github.com/googleapis/repo-automation-bots/assets/11778530/59c3690d-8586-4fbb-a352-0e07b7f09e48)

If this happens again, please re-open this bug and click the Rebuild button once.
