### ISSUE TITLE
Owlbot should keep track of custom modifications to templates

### ISSUE THREAD

**Issue by kolea2** [googleapis/repo-automation-bots#5045]
We have some examples of libraries that make modifications to otherwise standard templates. For example, https://github.com/googleapis/java-bigtable/blob/main/.kokoro/presubmit/integration.cfg#L9-L12 adds custom IT args to this standard template: https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/.kokoro/presubmit/integration.cfg. As such, we need to exclude it from owlbot and any new iterations of these templates need to be handled manually (see https://github.com/googleapis/java-bigtable/pull/1255 and fix https://github.com/googleapis/java-bigtable/pull/1258).

It would be great if owlbot could preserve known additions to templates so we can still receive updates without having to do manual work on them in a repeated way.

**Comment by SurferJeffAtGoogle** [comment]
If you add integration.cfg to the list of excludes here
https://github.com/googleapis/java-bigtable/blob/722c6c58e42c51ac414a7e189c711e844447b9ce/owlbot.py#L98
then Owl Bot won't touch it.  Will that satisfy your needs?

**Comment by kolea2** [comment]
`integration.cfg` is already excluded. I would like to not exclude **any** templates, but have owlbot insert custom arguments specific to the library (in this case, `INTEGRATION_TEST_ARGS`).

**Comment by SurferJeffAtGoogle** [comment]
I see.  That logic can be coded into owlbot.py and synthtool.  In other words, it's a feature request for your post processor (https://github.com/googleapis/synthtool).
