### ISSUE TITLE
Error: Text data outside of root node.

### ISSUE THREAD

**Issue by diptanshumittal** [googleapis/repo-automation-bots#5071]
Logs [link](https://pantheon.corp.google.com/logs/query;query=error_group%2528%22CNfSleWMspGHcg%22%2529%0AlogName:%22cloudfunctions.googleapis.com%252Fcloud-functions%22%0Aresource.type%3D%22cloud_function%22%0Aresource.labels.project_id%3D%22repo-automation-bots%22%0Aresource.labels.function_name%3D%22flakybot%22%0Aresource.labels.region%3D%22us-central1%22;timeRange=P30D;cursorTimestamp=2023-05-26T17:32:35.328208Z?jsmode=O&mods=allow_workbench_image_override&project=repo-automation-bots).

**Comment by SurferJeffAtGoogle** [comment]
I think it was a one time thing.
