### ISSUE TITLE
Error: could not handle getContent result.

### ISSUE THREAD

**Issue by diptanshumittal** [googleapis/repo-automation-bots#5072]
Logs [link](https://pantheon.corp.google.com/logs/query;query=error_group%2528%22CM-8t6Sx39286gE%22%2529%0AlogName:%22cloudfunctions.googleapis.com%252Fcloud-functions%22%0Aresource.type%3D%22cloud_function%22%0Aresource.labels.project_id%3D%22repo-automation-bots%22%0Aresource.labels.function_name%3D%22sync_repo_settings%22%0Aresource.labels.region%3D%22us-central1%22;timeRange=P30D;cursorTimestamp=2023-05-23T16:17:58.872226Z?jsmode=O&mods=allow_workbench_image_override&project=repo-automation-bots).

**Comment by SurferJeffAtGoogle** [comment]
Twice in the past 30 days with no observable consequenc.
