### ISSUE TITLE
flakybot is not working on google-cloud-node for continuous tests

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#5092]
Flakybot is not working for continuous tests, it errors with:

```
Step #2 - "run-tests": Calling flakybot --repo googleapis/google-cloud-node --commit_hash 0234fd0ce2da9e5fbae5c1da4a346179d0ca7091 --build_url https://console.cloud.google.com/cloud-build/builds;region=global/c0ed7a4a-73ce-4417-810f-0012839590fc?project=long-door-651
Step #2 - "run-tests": /bin/flakybot: line 1: Not: command not found
```

To reproduce:

1. Go to the GCP project for long-door-651, and under Cloud Build > [Triggers](https://pantheon.corp.google.com/cloud-build/triggers?mods=logs_tg_prod&project=long-door-651)
2. Go to `[system-continuous-node14]`
3. Click `Run`
4. Change the Branch Name to `fixFlakyBot` (which already contains some changes I've been experimenting with to see if it works, namely, adding some missing environment variables)
5. See failure in Build

See https://github.com/googleapis/google-cloud-node/issues/3381

**Comment by chingor13** [comment]
That error implies that the /bin/flakybot binary does not have the correct content -- perhaps when it was downloaded it was a 404 (so the file is a text file with "Not found")?

**Comment by sofisl** [comment]
I can confirm this is happening. How can I download the binary correctly? For reference, we are using this code: https://github.com/googleapis/google-cloud-node/blob/7778345f3d7089e3bdc1294beb4005cfa8793012/ci/Dockerfile#L30-L32
