### ISSUE TITLE
[auto-approve] Docker digest PRs not auto-approved

### ISSUE THREAD

**Issue by bourgeoisor** [googleapis/repo-automation-bots#5097]
It seems that Docker PRs where only the digest changes are not getting auto-approved.

e.g. https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1586 (can provide more examples if needed)

According to this requirement, they should be, since a digest is non-major, but I wonder if perhaps the code is only looking at minor and patches, and omitting digest changes? "Increase the non-major package version of a dependency or the tag"

**Comment by sofisl** [comment]
Hi Olivier! This PR didn't get merged because the filetype is not a Dockerfile (which you described here: https://github.com/googleapis/repo-automation-bots/issues/5006). Do you have any examples in which they were Dockerfiles? OR should we expand the rule to include `.yaml` files?
