### ISSUE TITLE
Build Cop: add test failure log to issues

### ISSUE THREAD

**Issue by ace-n** [googleapis/repo-automation-bots#513]
As title. 🙂

If this log is _not_ included, it can cause spurious (and practically un-debuggable! 😱) failures like [this one](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1758) if the log cannot be retrieved in some other way.

**Comment by tbpg** [comment]
Thanks! One concern to keep in mind is that failure logs can be long. So, we might want to wrap the log in a collapsible element. Emails would still be long, but I think that's OK.

**Comment by tbpg** [comment]
Thank you for the feature request! Feel free to file another issue if there is anything else we can improve (or this doesn't work as expected). :)
