### ISSUE TITLE
"Owl bot check failed" missing from GitHub.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#5174]
Example:
https://github.com/googleapis/google-cloud-node/pull/4480

We used to see failed checks here:
![image](https://github.com/googleapis/repo-automation-bots/assets/11778530/029da447-6bf0-4a3f-b7fc-a31d32f57a31)

Without the failed check, maintainers have no link to the failure log.

CC @alexander-fenster

**Comment by alexander-fenster** [comment]
My understanding is that we do have checks for OwlBot processing on someone else's PRs (e.g. when I make a PR, OwlBot comes to apply post-processing to check that the PR does not change anything auto-generated, and adds a link to its log in the checks section), but I don't remember seeing checks for `owl-bot-copy` PRs. Would be nice to have it!

**Comment by SurferJeffAtGoogle** [comment]
Yes, an OwlBot check used to appear with a link to the log.  Example: https://github.com/googleapis/google-cloud-node/pull/3684

![image](https://github.com/googleapis/repo-automation-bots/assets/11778530/e5b7aff2-ae2b-4252-bd36-afe0e9d1dcff)

**Comment by SurferJeffAtGoogle** [comment]
This may be related to the post processor exceeding the 10-minute TTL for the GitHub token.

**Comment by SurferJeffAtGoogle** [comment]
I'm thinking this is another symptom of https://github.com/googleapis/repo-automation-bots/issues/5046.

Is it possible to reduced the Node post-processor run time to less than 10 minutes?

**Comment by alexander-fenster** [comment]
It takes just a minute or two when run locally, definitely not 10 minutes. I guess the next step would be to figure out what took so long in the OwlBot run.

**Comment by alexander-fenster** [comment]
Local invocation:

```
$ export IMAGE=gcr.io/cloud-devrel-public-resources/owlbot-nodejs-mono-repo@sha256:353f74808df01ad8a4af996cac8acffcd9c087590743340bda440874cf55d566
$ time docker run --rm --user $(id -u):$(id -g) -v $(pwd):/repo -w /repo $IMAGE
...
2023-08-03 20:14:17,381 synthtool [DEBUG] > Post-processing completed
DEBUG:synthtool:Post-processing completed
.eslintignore
.eslintrc.json
.gitattributes
.mocharc.js
.nycrc
.prettierignore
.prettierrc.js
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
README.md
samples/README.md

real	2m11.666s
user	0m0.043s
sys	0m0.064s
$ echo $?
0
```

**Comment by SurferJeffAtGoogle** [comment]
I think we saw this error because we ran out of GitHub quota, which is a transient issue.  I added more logging so the next time this happens we will be better able to diagnose.
