### ISSUE TITLE
owlbot processing not starting, PR stuck as draft with staging directory

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/repo-automation-bots#5179]
PR: https://github.com/googleapis/google-cloud-node/pull/4498

Created 2+ hours ago with `owl-bot-staging` directory; the processing has never started and there is no note from Owlbot left in the CI section.

I know for sure that if I add `owlbot:run` to that PR it will get processed, but leaving it as is for now so you could investigate.

**Comment by SurferJeffAtGoogle** [comment]
I expect https://github.com/googleapis/repo-automation-bots/pull/5181 to have fixed it.  If not, I'll flip a flag so Owl Bot generates pull requests that are not drafts.

**Comment by SurferJeffAtGoogle** [comment]
Yay!  Owl Bot ran the post processor for this draft PR:
https://github.com/googleapis/google-cloud-node/pull/4536
