### ISSUE TITLE
[repo-metadata-lint]: false negative for `short_name` validation

### ISSUE THREAD

**Issue by coryan** [googleapis/repo-automation-bots#5194]
repo-metadata-lint created this bug:

https://github.com/googleapis/google-cloud-cpp/issues/12552

It is complaining about the `short_name` field here:

https://github.com/googleapis/google-cloud-cpp/blob/5c780b27aa2bd4a6df14760b749dd84fdef123ad/google/cloud/config/v1/.repo-metadata.json#L3

It seems to expect `config`.  However, the service YAML file calls itself `infra-manager`:

https://github.com/googleapis/googleapis/blob/eda81ef50cbc08ddf39e9e0689e116421581a234/google/cloud/config/v1/config_v1.yaml#L110

A few thoughts come to mind:

- If the `short_name` must always match the `api_id` then I am not even sure why we have a `short_name` field in the `.repo-metadata.json` file.  It would also be unclear why the YAML file has a `api_shortname` field.
- If the `short_name` should be `infra-manager` then this is a bug in the lint tool.

It is possible the C++ generator should not be using the `api_shortname` YAML file as its source of truth for this field.  That still makes me wonder why we would have these fields then.

**Comment by SurferJeffAtGoogle** [comment]
Assigning @bcoe who implemented this validation in https://github.com/googleapis/repo-automation-bots/pull/3017.

**Comment by bcoe** [comment]
@coryan the expectation is that `short_name` should be DNS subdomain of an API. It seems to me like the value in `service.yaml` is incorrect.

Perhaps you could update your tooling to simply grab the subdomain, rather than grabbing the shortname out of service.yaml?

**Comment by coryan** [comment]
> Perhaps you could update your tooling to simply grab the subdomain, rather than grabbing the shortname out of service.yaml?

Will do.

> @coryan the expectation is that `short_name` should be DNS subdomain of an API.

As I argued elsewhere (and above).  That suggest the `short_name` field is redundant and should be removed.  Instead of adding more complexity to verify the fields are "consistent" we should just remove the redundancy.

> It seems to me like the value in `service.yaml` is incorrect.

Possibly.  Since I am going to start ignoring this field I will also stop worrying about this.
