### ISSUE TITLE
owlbot-bootstrapper: bad source-link URL

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/repo-automation-bots#5230]
The owlbot-bootstrapper PRs include an invalid link to googleapis-gen in the PR description. For example, https://github.com/googleapis/google-cloud-python/pull/11665 says `Source-Link: https://googleapis/googleapis-gen@c72f454842b1af459b4e2d70e851008046172b2f`, but that's a bad URL.

**Comment by chingor13** [comment]
Looks like the URL should be `https://github.com/<owner>/<repo>/commit/<commit-sha>`
