### ISSUE TITLE
Release-Please should open an issue if something fails

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#527]
Currently, a failure in a release strategy will silently fail and no release PR is created. It's difficult to debug what's happening.

We should catch any exceptions and maintain an issue on the repo.

**Comment by chingor13** [comment]
This might actually be a candidate for our wrapper to handle. Is it possible to wrap this behavior for every bot?

**Comment by bcoe** [comment]
@chingor13 we actually have a retry approach built with tasks, but have only turned it on for publish, and I think one other.

**Comment by tmatsuo** [comment]
As a generic and very cheap solution, how about to create an issue on repo-automation-bots when retry count is exhausted?

**Comment by tmatsuo** [comment]
Be careful if the reporting part crashes, we'll have an infinite loop 😅

**Comment by chingor13** [comment]
Part of our rotation is to monitor exceptions in our bots. If it's a huge burden, we will look into a more generalized approach.
