### ISSUE TITLE
bug(owlbot): `owlbot:run` label does not trigger owlbot; `owlbot:run` label is not removed

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#5295]
In https://github.com/googleapis/python-ndb/pull/949 and https://github.com/googleapis/python-datastore/pull/525, I've added the `owlbot:run` label but it is not triggering owlbot to run.

It also appears to be stuck in other repositories. The first 19 pages of the results show PRs which still have the `owlbot:run` label which were opened in the last 24 hours.

https://github.com/search?q=org%3Agoogleapis+is%3Apr+is%3Aunmerged++is%3Aopen+label%3A%22owlbot%3Arun%22&type=pullrequests&s=created&o=desc&p=19

**Comment by arpan14** [comment]
Facing the same issue for Spanner PR - https://github.com/googleapis/java-spanner/pull/2927

**Comment by shivgautam** [comment]
Same for google-cloud-ruby as well. Example PR: https://github.com/googleapis/google-cloud-ruby/pull/24939

**Comment by chingor13** [comment]
From the logs, I am seeing a lot of `fetch failed` errors during the removal of the label:

```
HttpError: fetch failed
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:110:11
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async removeOwlBotLabel (/usr/src/app/build/src/owl-bot.js:324:9)
    at async Object.handlePullRequestLabeled (/usr/src/app/build/src/owl-bot.js:290:9)
    at async /usr/src/app/build/src/owl-bot.js:106:9
    at async Promise.all (index 0)
    at async /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:404:25
```

**Comment by chingor13** [comment]
After migrating traffic back to the previous owlbot revision, it can remove the label and proceed again. Looking into options for fixing this.
