### ISSUE TITLE
WebAssembly.compile() error

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/repo-automation-bots#5320]
When I try to run

```
node build/cli.js run-trigger pre-process --apiId=google.cloud.visionai.v1 --language=python --languageContainer=gcr.io/cloud-devrel-public-resources/python-bootstrapper:latest --repoToClone=git@github.com/googleapis/google-cloud-python.git --sourceCl=629822288
```

I get the error

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[CompileError: WebAssembly.compile(): expected 48120 bytes, fell off end @+1361]
```

This is happening on two separate machines of mine. @sofisl and @parthea  both tried the same command and it worked for them, so this strongly suggests it's something in my environment. We need to find out what it is so we can prevent it or warn people about it.

**Comment by chingor13** [comment]
@vchudnov-g Can you add your environment details? Like node and npm version?

**Comment by vchudnov-g** [comment]
Still getting the error:
```
❯ npm --version
10.8.0
 
❯ node --version
v18.19.1
```

**Comment by yushko** [comment]
@vchudnov-g  I had the same issue. Upgrading to Node v18.20.3 helped

**Comment by chasinandrew** [comment]
Upgrading worked for me too. Seems like an issue with v18.19.1.
