### ISSUE TITLE
Flakybot: parse and comment with affected region tags

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#543]
Region tags are included in a couple ways in some XML logs. Some are in the test name or class name, some are in test case properties, like this:

```
<testcase classname="http" name="TestCORSEnabledFunctionAuth" time="0.000">
	<properties>
		<property name="region_tags" value="functions_http_cors_auth"></property>
	</properties>
</testcase>
```

We could parse those properties to pull out which regions were affected by a failed test. If there is another property name used for region tags, we'd need to add it, too.

cc @ace-n.

**Comment by tmatsuo** [comment]
What's the real benefit from adding this information? Flakybot already reports failure with filename and testname. So isn't it easily obvious when you look at the line?

Maybe it's useful for some automated solution though.

**Comment by tbpg** [comment]
Closing as I don't think we need this anymore.
