### ISSUE TITLE
Who Should Use This?

### ISSUE THREAD

**Issue by mattfarina** [googleapis/repo-automation-bots#5528]
I've noticed some open source projects using the [cherry-pick-bot](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot). This includes CNCF projects where the maintainers are not associated with Google.

As a maintainer on a couple of other CNCF projects, that do no currently use the cherry-pick-bot, I was wondering who is ok to use the the cherry-pick-bot and other bots here.

I ask because the readme states that these are for Google management projects on GitHub.

**Comment by burkedavison** [comment]
As you mentioned, these projects are not officially supported products. No future availability guarantees are provided.
