### ISSUE TITLE
`gcf-owl-bot` not creating PRs for googleapis/python-bigquery-dataframes

### ISSUE THREAD

**Issue by chelsea-lin** [googleapis/repo-automation-bots#5544]
The gcf-owl-bot hasn't created any automatic pull requests to update owlbot-python packages for the [googleapis/python-bigquery-dataframes](https://github.com/googleapis/python-bigquery-dataframes) repository since September. Could you please investigate why this is happening?

Addtional Information:
* Last Pull Request Status for `gcf-owl-bot`: https://github.com/googleapis/python-bigquery-dataframes/pulls?q=is%3Apr+author%3Aapp%2Fgcf-owl-bot+is%3Aclosed
* Manual Update Recently: https://github.com/googleapis/python-bigquery-dataframes/commit/b0e5124d2b645380e038bbe522078f835b8b66f4
* OwlBot post-processor works well.

**Comment by suztomo** [comment]
@chelsea-lin "owl-bot-update-lock" pull requests came back! 
https://github.com/search?q=org%3Agoogleapis+label%3A%22owl-bot-update-lock%22+is%3Aopen+type%3Apr&type=issues

Details in b/375509303.
