### ISSUE TITLE
New Bot: Surface area semver diff labels

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#56]
For languages that support static analysis, identify breaking surface area changes and label the semver version change required to accept the PR.

**Comment by tmatsuo** [comment]
My guess is it is very language specific and it is way easier to have a CI build for that purpose. For example, cpp library has a step in their build process for comparing the ABI dump and report failure if there's a breaking change.

**Comment by tmatsuo** [comment]
Let me close this, but feel free to reopen.
