### ISSUE TITLE
New Bot: Triage me

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#57]
Label untriaged issues with a "triage me" label.

**Comment by JustinBeckwith** [comment]
As of right now we tend to do this on a cron, and check to see if the issue is at least 24 hours old (I think ...) before applying the `triage me` label.  If we care about keeping that feature, we would be blocked on https://github.com/googleapis/repo-automation-bots/issues/31

**Comment by chingor13** [comment]
This should be handled by slo-bot.
