### ISSUE TITLE
label-sync: labels not populated in my repo, what should I expect?

### ISSUE THREAD

**Issue by grayside** [googleapis/repo-automation-bots#577]
Possibly related to #575, I have enabled auto-label and label-sync on https://github.com/GoogleCloudPlatform/cloud-run-samples but do not see any changes in available labels. Is there repo-level configuration I need? I see no documentation.

**Comment by bcoe** [comment]
@grayside do you want all of the standard labels including product names?

The workflow is a little clunky, as soon as you delete a label, or create a new label, I believe it currently kicks off the sync... this isn't very clear.

**Comment by grayside** [comment]
Mainly I need the triage labels, not sure if the product labels have a role to play in a product-specific repo, though in theory it would be good to ensure all those issues include `api: run` for consistency in queries.

I'll go ahead and arrange a spurious label change.

**Comment by grayside** [comment]
I created "internal_cleanup" label and didn't see any change. Is there a way to verify that it bot installed correctly?

**Comment by sofisl** [comment]
Hi @grayside - I made it so that autolabel should backfill on a nightly basis if the repo is new. Did you see this work yet?

**Comment by grayside** [comment]
Ben previously kicked off a label sync for me by deleting a label, the previous trigger.

Whether addressed here or as another point for #575, I think a little more documentation is called for. (In general, the README's in this repo do not provide much context or instructions beyond a one-line description and boilerplate development instructions.)
