### ISSUE TITLE
Please-release complains about the merged PR that it is in the pending state

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/repo-automation-bots#582]
The bot complains about the merged PR that it is in the pending state. Closing such issues does not help, the bot shortly submits a new issue like:
https://github.com/googleapis/java-storage/issues/334

Probably removal of the `autorelease:tagged` label from the PR will solve the recurrent warning issue, but the bot logic should be improved.

**Comment by bcoe** [comment]
@dmitry-fa this is caused by the `autorelease:pending`, or `autorelease:tagged` label not being removed after a publish, which should be part of the publication step.

I believe this might be a bug with how the library was published to maven? The label is actually removed by a kokoro job.

**Comment by bcoe** [comment]
I looked at some recent releases from this library, and the `autorelease: published` tag has been added. I believe the underlying cause of this was potentially an issue with credentials in `autorelease`, which we addressed last month.
