### ISSUE TITLE
blunderbuss: assigns issue before auto-label runs

### ISSUE THREAD

**Issue by codyoss** [googleapis/repo-automation-bots#599]
I currently work in a mono-repo that makes use of both `blunderbuss` and `auto-label`. I would like it if auto-label ran before bunderbuss as the assignee changes based on the product label.

Example:
- Issue is opened: https://github.com/googleapis/google-cloud-go/issues/2469
- `blunderbuss` assigns the issue to me as I am the fallback: https://github.com/googleapis/google-cloud-go/commit/9c1faca4ed66376b73e1bd7a39076c5838ae7f52#diff-30872c876afbce72ad8d68bc80238c6cR22
- `auto-label` adds the `api: storage` label, as it should have

If `blunderbuss` ran after `auto-label` it would have correctly assigned someone else: https://github.com/googleapis/google-cloud-go/commit/9c1faca4ed66376b73e1bd7a39076c5838ae7f52#diff-30872c876afbce72ad8d68bc80238c6cR8

**Comment by tbpg** [comment]
Two ideas:
* If there is an `assign_issues_by` config, wait N seconds before fetching assignees and checking there are still none.
* Import the auto-label logic and don't assign the issue if it's about to be labeled. The label action will retrigger Blunderbuss.
