### ISSUE TITLE
Errors when following instructions to run Buildcop locally

### ISSUE THREAD

**Issue by dinagraves** [googleapis/repo-automation-bots#604]
I tried these [instructions](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop#buildcopgo) and got the following error:

```
dinagraves$ go build ./buildcop -repo=GoogleCloudPlatform/cloud-run-samples
can't load package: package ./buildcop: cannot find package "." in:
	/Users/dinagraves/Workspace/DevRel/repo-automation-bots/packages/buildcop/buildcop
can't load package: package -repo=GoogleCloudPlatform/cloud-run-samples is not in GOROOT (/usr/local/go/src/-repo=GoogleCloudPlatform/cloud-run-samples)
```

**Comment by tbpg** [comment]
If you do `go get github.com/googleapis/repo-automation-bots/packages/buildcop`, you don't have to build the code. The binary will be added to `$GOPATH/bin`. Hopefully, that path is already on the `PATH` for the `golang` Cloud Build image. So, you would change the invocation to:

```
buildcop -repo=GoogleCloudPlatform/cloud-run-samples
```

(No `./` at the beginning.)

Thank you for figuring all of this out!

**Comment by dinagraves** [comment]
Thanks!  That works for Cloud Build, but it didn't work for me locally:

```
dinagraves$ go get github.com/googleapis/repo-automation-bots/packages/buildcop
go: downloading github.com/jstemmer/go-junit-report v0.9.1
go: downloading honnef.co/go/tools v0.0.1-2020.1.3
go: downloading golang.org/x/sys v0.0.0-20200331124033-c3d80250170d
go: downloading golang.org/x/tools v0.0.0-20200331025713-a30bf2db82d4
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading google.golang.org/appengine v1.6.5
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading golang.org/x/mod v0.2.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
dinagraves$ buildcop -repo=GoogleCloudPlatform/cloud-run-samples
-bash: buildcop: command not found
dinagraves$ go run buildcop -repo=GoogleCloudPlatform/cloud-run-samples
package buildcop is not in GOROOT (/usr/local/go/src/buildcop)
```
Trying to figure out the right way to do this locally, so we can update the README documentation!   Is there another step I have to take to set up the environment or something?

**Comment by tbpg** [comment]
Try `$(go env GOPATH)/bin/buildcop`. Looks like `$(go env GOPATH)/bin` isn't on your `PATH`.

**Comment by dinagraves** [comment]
that works! thank you!

**Comment by tbpg** [comment]
Marking this as fixed.
