### ISSUE TITLE
Drop dependency on `repos.json`

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#623]
We are trying to [delete repos.json](https://github.com/googleapis/sloth/issues/730) from sloth.  This repository takes a dependency on the file, even though it _probably_ shouldn't be using it.  Adding this to track the work.  

## Label Sync bot
The label sync bot uses `repos.json` to find all repositories it should update when the main list of available labels changes.  It wants to go to every repository, and trigger an update of its labels.  Using `repos.json` for this is not good, because it will miss repositories that have the bot installed, but aren't in `repos.json`.  The offending code is here:
https://github.com/googleapis/repo-automation-bots/blob/2e999b00724d1c1b9ad7a6d2922ad32f09c140cb/packages/label-sync/src/label-sync.ts#L94-L109

I am pretty sure we should instead interrogate GitHub to find which repositories have the `label-sync` application installed instead.  I think you use this API to do that:
https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-app-installation

The challenge is that this API requires an [installation access token](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation), and I have little idea how Probot manages getting it.  Some poking about landed me on this issue:
https://github.com/probot/probot/issues/1003

It looks like we would want to do something like:

```js
// Find every repository that has this GitHub Application installed.
// To access the apps/installation list endpoint, you need to have a
// JWT obtained via createInstallationToken.
const github = await app.auth();
const token = await github.apps.createInstallationToken({
  installation_id: context.payload.installation.id
});
const ok = new Octokit({
  auth: token,
});
const res = await ok.apps.listRepos();
```

I ran into issues with `context.payload` not having an `installation` property, so someone will need to dig further into this.  I also have no earthly idea how I would have tested my code. 

## GCF Utils
The same story plays out in GCF Utils, specifically while figuring out which repositories to run cron jobs against.  *We shouldn't use repos.json for this, rather we should use the list of repositories on which the app is installed*.  The offending code is here:
https://github.com/googleapis/repo-automation-bots/blob/2e999b00724d1c1b9ad7a6d2922ad32f09c140cb/packages/gcf-utils/src/gcf-utils.ts#L198-L205

Independent of my desire to drop `repos.json`, I think we should clean these up because it creates unintended consequences for consumers of the app.  It's entirely unclear that I need to be registered in sloth in order to use one of these bots.

**Comment by azizsonawalla** [comment]
```
I ran into issues with context.payload not having an installation property, so someone will need to dig further into this. I also have no earthly idea how I would have tested my code.
```
When you tested this, was the webhook delivery to a registered GitHub App or simply to an endpoint (settings > webhook > url)? According to [this documentation](https://developer.github.com/webhooks/event-payloads/#installation):  "Webhook payloads contain the `installation` property when the event is configured for and sent to a GitHub App."

**Comment by JustinBeckwith** [comment]
To clarify - the `installation` property wasn't available in the *TypeScript* types.  I haven't tried running the code I pasted in there in any environments yet.  This was just early investigation.

**Comment by bcoe** [comment]
@JustinBeckwith @azizsonawalla our automation bots have a JWT as their auth token, based on the installation ID already, I managed to list repositories for a given installation, using this approach:

```js
    app.on(events, async (context) => {
        const { owner, repo } = context.repo();
        try {
            console.info(`the installation id: ${context.payload.installation.id}`);
            // call the preview API /installation/repositories, this is why I'm setting the Accept header:
            // https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-app-installation
            const {data} = await context.github.request('/installation/repositories', {
                headers: {
                    'Accept': 'application/vnd.github.machine-man-preview+json'
                }
            })
            console.info(data); // <-- this will have all the repositories (405! I noted).
        } catch (err) {
            console.error(err);
        }
        await reconcileLabels(context.github, owner, repo);
    });
```

**Comment by JustinBeckwith** [comment]
Re-opened because it's still used in `sync-repo-settings`, and appears in a few tests that give me pause as well.

**Comment by sofisl** [comment]
Do we want to also use the same strategy for SRS, using the list of repos it's currently installed on?

**Comment by JustinBeckwith** [comment]
Yes!  Anywhere we iterate over a collection of repositories, we should use the installation list instead of repos.json.

**Comment by JustinBeckwith** [comment]
This was completed in #706 - thank you folks!
