### ISSUE TITLE
test dependencies differ from deployment

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#63]
When developing and running tests (locally and on CI), tests can pass while deployment fails.

An example is the `release-please` bot passed tests, but at deployment time, we discovered that it's missing `@types/semver`.

**Comment by bcoe** [comment]
I think this is a reality of the Node.js development stack, when we deploy our functions they will be installed with `--production`, which includes only `dependencies` not `development` dependencies.

Where we might be able to fix this is in [gts](https://github.com/google/gts), we do have a rule that is supposed to detect development dependencies in a production context, but in testing it didn't seem to work too well.
