### ISSUE TITLE
Merge on Green: attempts to merge after the label has been removed

### ISSUE THREAD

**Issue by tbpg** [googleapis/repo-automation-bots#638]
### Expected behavior:
Merge on Green doesn't merge or try to merge the PR after the `automerge` label has been removed.

### Actual behavior:

https://github.com/GoogleCloudPlatform/golang-samples/pull/1540
1. I added the `automerge` label.
2. I noticed an issue with the PR, so I removed the `automerge` label.
3. gcf-merge-on-green commented that the PR had attempted to merge for 3 then 6 hours.
![DqifJs3kHiH](https://user-images.githubusercontent.com/26876514/86243704-d4434400-bb74-11ea-8ce1-c26898b75d25.png)

**Comment by sofisl** [comment]
I think this was solved in PR #625 
 ```
  if (!mogLabel) {
    console.log(`${owner}/${repo}/${pr} does not have the required labels`);
    return true;
  }
```
This should cause the variable ```remove``` to return true, removing the PR from the Datastore table. Please reopen if you see this reoccurring!
