### ISSUE TITLE
Add lock mechanism

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#660]
For some bots (like release-please), we only want a single instance running at a time or weird race conditions may happen (2 instances trying to write to the same branch)

We should support some kind of atomic worker queue such that a bot can run one instance at a time (per repository or globally).

**Comment by tbpg** [comment]
This would also be nice for the Build Cop bot to avoid race conditions while updating issues.

**Comment by bcoe** [comment]
@tbpg I was talking to @chingor13 about this, an idea I had rather than an atomic worker queue, was a cloud function that acts as a semaphore using long polling.

**Comment by tbpg** [comment]
Could we use Firestore with strongly consistent operations? I'm not sure I understand the Cloud Function + long polling idea.

**Comment by bcoe** [comment]
@tbpg I'm picturing that a step in the processing flow that needs to be serial, would make a request to a cloud function asking for a lock. If a lock is available, the HTTP request returns immediately, if no lock  is available, the HTTP connection stalls for up to N seconds (where N is some upper bound on execution time we expect, such that we don't ever permanently lock bots).

**Comment by tbpg** [comment]
Why not access the lock directly? Why go through a separate Cloud Function?

**Comment by tmatsuo** [comment]
FYI, I'm building a datastore based lock at: https://github.com/googleapis/repo-automation-bots/pull/1732
Once it works for blunderbuss, I'll factor it out to gcf-utils so that anyone can use it.

**Comment by tmatsuo** [comment]
Now the new package [`@github-automations/datastore-lock`](https://www.npmjs.com/package/@github-automations/datastore-lock) is available, which is used by blunderbuss: https://github.com/googleapis/repo-automation-bots/blob/0008d5d3d5b532225881c2f78baeb6d5f6388756/packages/blunderbuss/src/blunderbuss.ts#L97

Closing
