### ISSUE TITLE
nock for probot config requires extra mocks for 404s

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#68]
When mocking a 404 for `context.config('filename')`, we need to do something like:

```ts
      const requests = nock('https://api.github.com')
        .get(
          '/repos/<owner>/<repo>/contents/.github/release-please.yml'
        )
        .reply(404)
        .get(
          // why is this necessary?
          '/repos/<owner>/.github/contents/.github/release-please.yml'
        )
        .reply(404);
```

**Comment by bcoe** [comment]
👋 I ultimately figured out why this is, it's actually probot behaving as expected.

It checks a `.github` folder in your existing repository, and if not found, checks for a `.github` repository in your organization (which can be used to store central config for a bot).

**Comment by bcoe** [comment]
I'm actually going to go ahead and close this, as I think that it's behaving as expected (it just took us a while to notice that probot checks two repos for config).
