### ISSUE TITLE
googleapis/aip opted into Node checks on branch protection.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/repo-automation-bots#721]
This seems not ideal. :-)

**Comment by lukesneeringer** [comment]
Are you sure this is exempted? I had to fix it again today.

**Comment by sofisl** [comment]
@lukesneeringer - would you mind letting us know if you have to fix it again tomorrow? If you don't have to, I think we can close the issue. Thanks!

**Comment by sofisl** [comment]
Confirmed it stuck!
