### ISSUE TITLE
setting-sync-bot: incorrectly setting required checks

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#778]
Some java libraries are getting incorrect required checks.

Example: https://github.com/googleapis/java-notebooks/pull/7 This repo should be getting the default java checks which are mostly GitHub actions + Integration/Samples tests on Kokoro.

**Comment by stephaniewang526** [comment]
Bumping this -- also observed in various BigQuery Java client repos. e.g. https://github.com/googleapis/java-bigquery/pull/630

**Comment by chingor13** [comment]
Should have been fixed in #800
