### ISSUE TITLE
Support @octokit/webhooks versions > 7.1.1 by changing import strategy

### ISSUE THREAD

**Issue by azizsonawalla** [googleapis/repo-automation-bots#792]
[@octokit/webhooks.js](https://www.npmjs.com/package/@octokit/webhooks) changed the way they export the `Webhooks` type i[n a recent commit](https://github.com/octokit/webhooks.js/commit/12a266a34ad4781975038a8a78908481460f5fce#diff-41df78d86ed4de80aae9b0b9560feb2b) and this [breaks the release-please tests](https://github.com/googleapis/repo-automation-bots/pull/791/checks?check_run_id=939823269#step:8:1) for versions above 7.1.1. The fix should be fairly straightforward but it will require some testing to ensure nothing else is broken. 

https://github.com/octokit/webhooks.js/pull/113

**Comment by sofisl** [comment]
When this is addressed we can reopen #797.
