### ISSUE TITLE
bug(gcf-utils): binding trigger information to logger causes information bleed b/w bot executions

### ISSUE THREAD

**Issue by azizsonawalla** [googleapis/repo-automation-bots#808]
**The issue**:

A new feature in gcf-utils [was released](https://github.com/googleapis/repo-automation-bots/commit/157c768e6de8e3067e24a6dd17be152ae98c25d8) that would bind the trigger information for the bot execution (i.e. whether it was triggered by GitHub/Scheduler/etc) to every log statement that comes out of that execution. However, when I looked at the logs the JSON looked something like this:

```
{
    trigger_type: "Cloud SchedulerCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud TaskCloud"
}
```
whereas the expected value is just `{ trigger_type: "Cloud Scheduler" }` or `{ trigger_type: "Cloud Task"}`.

What's weirder here than the fact that multiple values are being concatenated, is that the *values are coming from different executions of the bot*. `Cloud Scheduler` and `Cloud Task` trigger types are never assigned in the same execution, so somehow the values that I bind to the logger in the previous executions are being passed on to the logger instance in the next execution.

**Investigating:**

I first thought this was an issue with the logging library that gcf-utils uses (Pino), so I ran some test code *outside* of GCF:

```
const pino = require('pino');

const bindings = {
  foo: 'bar'
}

let logger = pino();
logger.info('Log entry with no bindings');

logger = logger.child(bindings);
logger.info('Log entry with binding once');

logger = logger.child(bindings);
logger.info('Log entry with binding twice');
```
output:

```
{"msg":"Log entry with no bindings"}
{"foo":"bar","msg":"Log entry with binding once"}
{"foo":"bar","foo":"bar","msg":"Log entry with binding twice"}
```
and while the bindings did show up twice, they weren't concatenated like in Cloud Logs. And in fact, re-parsing these logs as JSON removes the duplicate keys and does not concatenate the values. So GCF is doing something extra here.

So I test the same code in GCF, and sure enough, here's the output:

```
{"msg":"Log entry with no bindings"}
{"foo":"bar","msg":"Log entry with binding once"}
{"foo":"barbar","msg":"Log entry with binding twice"}
```
So instead of having duplicate values, or simply overriding duplicate keys, GCF is concatenating the values. 

But the question still remains - *how are values from different executions bleeding into one another?*

**My theory:**

My best guess is that Pino is being cached between GCF executions and with it the bindings are also being maintained between runs. This is where my knowledge of GCF reaches its limit though - so anyone have any ideas on how or why this might be happening?

The logger in question is instantiated here: https://github.com/googleapis/repo-automation-bots/blob/92401b245cd5de1638b7057a53fe13b85c968e98/packages/gcf-utils/src/gcf-utils.ts#L57

And then values are bound here: https://github.com/googleapis/repo-automation-bots/blob/92401b245cd5de1638b7057a53fe13b85c968e98/packages/gcf-utils/src/gcf-utils.ts#L193

**Comment by tmatsuo** [comment]
On Cloud Function, yeah global variables are cached.

Maybe we can just remove the bindings in `bindPropertiesToLogger`?

**Comment by tmatsuo** [comment]
I believe this issue is already fixed by this line:
https://github.com/googleapis/repo-automation-bots/blob/5995efb3ed735e3fad9be48c0d95105a6e1dfa28/packages/gcf-utils/src/gcf-utils.ts#L275
