### ISSUE TITLE
bug(buildcop): some new missing reports on python-docs-samples

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#832]
[Build](https://source.cloud.google.com/results/invocations/97357480-466d-4978-bb58-f36f4a87843b/targets)

There are 3 failed tests:
- python-docs-samples/jobs/v3/api_client
- python-docs-samples/memorystore/redis
- python-docs-samples/translate/cloud-client

The first one was reported:
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4476

The second and the third one are not.

buildcop ids:

The second one:
```
[Buildcop] Published sponge_log.xml (1420619926135544)!
```

The third one:
```
[Buildcop] Published sponge_log.xml (1420640008749563)!
```

**Comment by tbpg** [comment]
Translate issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4475

The memorystore/redis issue is because the failure shows up as an `error` instead of a `failure`:
```
<testsuites>
<testsuite errors="1" failures="0" hostname="kokoro-gcp-ubuntu-prod-13339050" name="pytest" skipped="0" tests="1" time="134.531" timestamp="2020-08-11T11:29:15.048360">
<testcase classname="memorystore.redis.cloud_run_deployment.e2e_test" name="test_end_to_end" time="134.482">
<error message="failed on setup with "subprocess.CalledProcessError: Command '['gcloud', 'redis', 'instances', 'create', 'test-instance-44d74c74c5', '--region=us-central1', '--network', 'test-network-44d74c74c5', '--project', 'python-docs-samples-tests']' returned non-zero exit status 1."">Traceback (most recent call last):
  File "/workspace/memorystore/redis/cloud_run_deployment/e2e_test.py", line 70, in services
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gcloud', 'redis', 'instances', 'create', 'test-instance-44d74c74c5', '--region=us-central1', '--network', 'test-network-44d74c74c5', '--project', 'python-docs-samples-tests']' returned non-zero exit status 1.
</error>
</testcase>
</testsuite>
</testsuites>
```

You can download this XML from the artifacts tab of the build.

We need to update the parsing here to handle `failure` or `error`: https://github.com/googleapis/repo-automation-bots/blob/05254b6ef863cf6b58b1362c7912ff159aa65006/packages/buildcop/src/buildcop.ts#L836-L855
