### ISSUE TITLE
feat: provide common helper for validating bot configuration

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#870]
- [ ] The bot should not crash on parsing issues
- [ ] *Bonus*: lint against a schema like SLO bot
- [ ] *Bonus*: adding a status check on a pull request that fails the build if the configuration file is touched and is invalid

**Comment by tmatsuo** [comment]
FYI, snippet-bot is only enabled if there's a config file. It is great if the helper considers this use case.

How about to have another bonus for allowing the bot to read the config file from PR?

**Comment by chingor13** [comment]
> How about to have another bonus for allowing the bot to read the config file from PR?

Do you mean using the configuration from the PR? That could be potentially dangerous as anyone could send anything in a PR.
