### ISSUE TITLE
Hourly blast of "Unable to fetch events" errors in the logs

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#876]
Looking through the logs, I'm seeing an hourly blast of error messages for hundreds of repositories that look like this:
```
Failed to fetch events for googleapis/python-firestore: 
{
  "name": "HttpError",
  "status": 403,
  "headers": {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
    "connection": "close",
    "content-length": "250",
    "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'",
    "content-type": "application/json; charset=utf-8",
    "date": "Wed, 19 Aug 2020 19:00:04 GMT",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "server": "Varnish",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-github-media-type": "github.v3; format=json",
    "x-github-request-id": "4B3B:492D:2F279C:4E6F1F:5F3D76B3",
    "x-ratelimit-limit": "60",
    "x-ratelimit-remaining": "0",
    "x-ratelimit-reset": "1597864605",
    "x-xss-protection": "1; mode=block"
  },
  "request": {
    "method": "GET",
    "url": "https://api.github.com/repos/googleapis/python-firestore/events",
    "headers": {
      "accept": "application/vnd.github.v3+json",
      "user-agent": "octokit-rest.js/18.0.3 octokit-core.js/3.1.1 Node.js/12.18.3 (linux; x64)"
    },
    "request": {}
  },
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

It appears that we're blowing up some kind of quota, but I have no idea why we would be en masse calling out to that events API endpoint.  I have no idea what if anything this is breaking.

**Comment by azizsonawalla** [comment]
This is coming from monitoring-system's [GitHub Data Processor](https://github.com/googleapis/repo-automation-bots/blob/master/packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts). It's trying to fetch GitHub Events data for repositories that call repo automation bots but sometimes it hits the rate limit. It's not an error coming from any of the bots. 

There should be a fix for reducing the number of API calls made (but maybe I forgot to deploy it). I'll try to make these go away. 

If it's messing with tracking bot errors, you can filter by `resource: cloud_function` because this thing is deployed on Cloud Run

**Comment by sofisl** [comment]
@JustinBeckwith, @chingor13, Is this issue persisting? Is it specific to a given bot? This issue is about to go OOSLO, just trying to figure out if this is still a bug/what needs to get done.

**Comment by JustinBeckwith** [comment]
I don't think it's specific to any given bot - as Aziz mentioned, it's this stat collector thing that's running [here](https://github.com/googleapis/repo-automation-bots/blob/master/packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts).  If we want to know if it's still in the logs - go to the repo-automation-bots GCP project, and check the error logs!  This may be benign, but I don't know if we're counting on these metrics to be correct.  Even if we aren't, we don't want the error log spammy spammed.

**Comment by bcoe** [comment]
let's try to address this when when/if we dust off the data processor, if we have need of tracking events through the entire system as our systems become more complex.
