### ISSUE TITLE
testing: use the same nodejs version as the production

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#892]
I think now we're using different nodejs versions in our tests and the production environment.

In https://github.com/googleapis/repo-automation-bots/pull/889, I tried to use `fs.rmdirSync(tmpDir.name, {recursive: true});`. The test passes locally, as well as in our CI builds.

`recursive` option was introduced in nodejs 12.10.0:
https://nodejs.org/en/blog/release/v12.10.0/

Our cloud function environment says it's nodejs 10.

I think we should use the same version in our CI builds.

**Comment by tmatsuo** [comment]
This is kind of solved by migrating to nodejs12 for now, but in the long run, we should consider better testing strategy.

**Comment by JustinBeckwith** [comment]
Nah - I think we're good.  Moving forward we should just be more careful to snap the testing version in `ci.yaml` to the version tied to the runtime.  Calling this one done :)

**Comment by tmatsuo** [comment]
I'd like to have a capability of really matching the versions, so I opened #922
