### ISSUE TITLE
docs(header-checker-lint): migrate config file to `.github/header-checker-lint.yml`.

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#897]
https://github.com/googleapis/repo-automation-bots/tree/master/packages/header-checker-lint

still uses `.bots/header-checker-lint.json`.

**Comment by chingor13** [comment]
Looks like the code was changed in https://github.com/googleapis/repo-automation-bots/pull/432 to use the built-in `context.config()` but the documentation was not updated
