### ISSUE TITLE
Access Token Deprecation

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#906]
Today we got this message from GitHub for snippet-bot and merge-on-green:

> 
> On August 25th, 2020 at 18:10 (PDT) your application "Snippet Bot" issued a request using the deprecated endpoint for creating access tokens. GitHub has deprecated this undocumented endpoint. Its replacement, which accepts the same arguments, is available now.
> 
> This endpoint will be removed on October 1st, 2020.
> 
> Please visit https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint for more information about suggested changes, brownouts, and removal dates.

We should figure out what's up there :)

**Comment by JustinBeckwith** [comment]
I think I started a thread on this, and I assume we would have heard the screams if things were broken :)

**Comment by bcoe** [comment]
confirming that I did  `grep` of the codebase, and don't see us hitting these URLs.
