### ISSUE TITLE
improvement: stop using types from octokit

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#91]
We keep bumping into types incompatibilities between Octokit and probot; Let's look into instead using the types exporte by probot.

related: https://github.com/googleapis/repo-automation-bots/pull/89

CC: @orthros

**Comment by orthros** [comment]
Disclaimer: I am not a full time Node/Typescript aficionado, so this may not be the right answer.

The only way I can see getting this to work is to have Probot declare Octokit as a `peerDependency` and force the upstream consumer (our library) to provide the dependency.

Does this track with your understanding?

**Comment by bcoe** [comment]
@orthros I'm suspicious that probot might have the octokit types buried somewhere in what it ships, haven't dug yet though.
