### ISSUE TITLE
Infra: Create Email or Issue on failing bot based on OWNERS file

### ISSUE THREAD

**Issue by orthros** [googleapis/repo-automation-bots#95]
Due to the mono-repo nature of our project and our deployment pattern, there is no "baked in" way of forwarding errors that occur in a Bot to the given owners of a bot without subscribing to the "firehose" of all errors (like I have).

I propose that we create a serverless job that when an error occurs, it parses the bot the error occurred in, looks up who the OWNERS of the bot are via a code OWNERS file in this repository, then creates an issue assigned to those owners. 

Extra credit would be to send an email to the owners in addition to the Issue, though that has other implications.

A problem I can see with this is accidentally including PII or other sensitive information in the created Issue. The body of the Issue may need to be ran through [DLP](https://cloud.google.com/dlp/) before creating it, or we may need to have a "generic" body with a short stack trace to minimize this risk.

**Comment by tmatsuo** [comment]
It seems like this issue is stale. Closing, but feel free to re-open.
