### ISSUE TITLE
New Bot: linkinator bot

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#957]
Shared bot that scans README files for broken links. 

- [ ] (P0) Create a presubmit check failure if the README is touched and has broken links.
- [ ] (P1) Nightly run to scan for broken links, file an issue on broken links.

Node.js client libraries run linkinator to test README links.

**Comment by JustinBeckwith** [comment]
This is a nut I haven't figured out how to crack yet.  I know we can do scanning of README files specifically, but beyond that doc generation is such a bespoke process on a language by language and repo by repo basis that I couldn't figure out how to generalize the scanning beyond something like a GitHub Action that lets you serialize other steps first.  Wondering what y'all had in mind here :)

**Comment by bcoe** [comment]
could we just have config that points at files to scan in an output folder, in Node.js case I think linkinator looks at `.html` files in `docs/` right?

**Comment by bcoe** [comment]
... perhaps it makes more sense as an action than a bot, and then it could run a doc generation task that you provide as a command, and then run linkinator on a target.

**Comment by JustinBeckwith** [comment]
Heh, yeah the problem with the `docs/` folder bit is that first you need to generate the docs folder!  At least the way we do things now, we don't check those into source control.  I think this has to be an action if we do anything.  I'm curious if that makes this any easier to use than using `setup-node`  and `npx linkinator` though.

**Comment by bcoe** [comment]
@JustinBeckwith I think you could make a `linkinator` action, and then folks from other language teams could benefit from its functionality, without needing to even know it's Node.js (_gross 😝_).

**Comment by chingor13** [comment]
Justin wrote a GitHub action that can be used to this effect.

https://github.com/JustinBeckwith/linkinator-action
