### ISSUE TITLE
auto label bot should label any PR that touches files in a samples folder with the samples label

### ISSUE THREAD

**Issue by leahecole** [googleapis/repo-automation-bots#978]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Python sample owners receive a lot of PRs from the library, but only need to pay attention when they have to do with samples. If possible, it would be super if we could label the PRs with the `samples` label to make it easier. We are also considering using blunderbuss to properly assign PRs, but I see blunderbuss as a solution that would complement this, not necessarily be an alternative.

**Comment by leahecole** [comment]
Lol @ the robot labeling this samples 🤖 😆

**Comment by tmatsuo** [comment]
I think it's relatively easy to implement. We'll likely need to revisit the bot permissions on the repos.

**Comment by JustinBeckwith** [comment]
Dammit the robots are doing the best they can Leah

**Comment by tmatsuo** [comment]
Also `examples/` too

**Comment by nicoleczhu** [comment]
fyi: I recently updated auto-label to label PR with languages, based on directory paths. i.e. users can [configure labels by folder paths](https://github.com/googleapis/repo-automation-bots/tree/master/packages/auto-label#language-label). 

I think it's fast extend the PR & let users get rid of the "language" prefix if that works for your use case @leahecole :)

**Comment by leahecole** [comment]
I'm watching your starter project now and am jumping for joy because I think it's exactly what we need @nicoleczhu !!!

**Comment by tmatsuo** [comment]
@nicoleczhu Thanks, closing.

**Comment by nicoleczhu** [comment]
Ah so, right now it will auto inject the "lang:" prefix to the labels. Though you can definitely define the specific path labels you want. 

I'll make a quick patch tomorrow to make it such that **you can get rid of the prefix**, and effectively label non-languages as well.
